### ISSUE TITLE
Inquiry about using dw_prestress term 

### ISSUE THREAD

**Issue by JongwonB** [sfepy/sfepy#1011]
Hello,
I'm trying to calculate the stress/strain and displacement with prestress (or initial stress) conditions using dw_lin_prestress term.
However, prestress are still remaining after solving progress.
We think that initial stress will be relaxed because it is only driving force to deform shape.
(for example, in abaqus, implementing prestress (using predefined field), all of the initial stress relaxed) 
Is that available using sfepy?

I attached the example code. 
Many thanks,
[prestress_example.txt](https://github.com/sfepy/sfepy/files/12168943/prestress_example.txt)

John.

**Comment by rc** [comment]
Hi @JongwonB, you would need to add the prestress to the total stress, and then still the resulting stress would not be zero in general - it would be balanced by the reaction forces in the fixed nodes. Try using boundary conditions that only fix rigid body modes without preventing other movement and a finer mesh. Let me know if that helps.

**Comment by JongwonB** [comment]
> Hi @JongwonB, you would need to add the prestress to the total stress, and then still the resulting stress would not be zero in general - it would be balanced by the reaction forces in the fixed nodes. Try using boundary conditions that only fix rigid body modes without preventing other movement and a finer mesh. Let me know if that helps.

Hi @rc, your comment work well!, I really appreciate it

**Comment by JongwonB** [comment]
> Hi @JongwonB, you would need to add the prestress to the total stress, and then still the resulting stress would not be zero in general - it would be balanced by the reaction forces in the fixed nodes. Try using boundary conditions that only fix rigid body modes without preventing other movement and a finer mesh. Let me know if that helps.

Hi @rc, your comment work well!, I really appreciate it. Many Thanks,
