### ISSUE TITLE
Building wheel for sfepy (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by benwebr** [sfepy/sfepy#1019]
I am trying to install sfepy with pip on Windows 11 and the following environment:

PS C:\Users\benwe> python --version
Python 3.10.11

PS C:\Users\benwe> cmake --version
cmake version 3.27.4

PS C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools> cl
Microsoft (R) C/C++-Optimierungscompiler Version 19.37.32822 für x86
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

--------------------------------------
I get the following error:

 Building wheel for sfepy (pyproject.toml) did not run successfully.
  exit code: 1

From what I see, this might be the problem:

Error compiling Cython file:
  ------------------------------------------------------------
  ...
  cimport cython
  
  import numpy as np
  cimport numpy as np
  
  from types cimport int32, float64, complex128
  ^
  ------------------------------------------------------------
  
Here is the entire error log
=================

  C:\Users\benwe\AppData\Local\Temp\pip-install-6augszt1\sfepy_a11cdfbcef814484b04892a31abe5eaa\sfepy\discrete\common\e
xtmods\assemble.pyx:10:0: 'types.pxd' not found
[sfepy_errors.txt](https://github.com/sfepy/sfepy/files/12511028/sfepy_errors.txt)

**Comment by rc** [comment]
This is IIRC caused by an old scikit-build - try `pip install -U scikit-build`.

**Comment by benwebr** [comment]
Thanks for thefast reply. I updated scikit-build, but obtained some similar errors as before. See attached log.
[sfepy_errors2.txt](https://github.com/sfepy/sfepy/files/12511871/sfepy_errors2.txt)

**Comment by rc** [comment]
I noticed that you have Cython >= 3.0 - try using the git version of sfepy, where Cython is constrained to < 3.0. Let me know if you need help with that.

**Comment by benwebr** [comment]
I am new to the python installation process and will need some time to understand the different packages and the way they are installed. Since pip did not work, I tried the Anaconda distribution and suceeded, after updating vkt. So I could finally run the tutorial :-).

**Comment by rc** [comment]
Glad to hear that!
