### ISSUE TITLE
truss bridge examples broken

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#1035]
It seems that #1033 broke the truss bridge examples - they are not tested in `sfepy/tests/test_declarative_examples.py`.

**Comment by rc** [comment]
More broken examples:
```
sfepy-run  sfepy/examples/homogenization/nonlinear_hyperelastic_mM.py
sfepy-run  sfepy/examples/homogenization/nonlinear_homogenization.py
```

**Comment by vlukes** [comment]
This  #1037 should fix the issue.
