### ISSUE TITLE
Zero displacements everywhere except for applied boundary conditions

### ISSUE THREAD

**Issue by dalek-caan11** [sfepy/sfepy#1043]
Hello,

I've been having a play with sfepy and think it's great! I have run a few of the examples and successfully modified some too. I've now tried to make an interactive electrodynamic one. However, when I run it and look at the results, they are all zeros except for the boundary conditions I've applied to a single node. I have most likely missed something or done something silly but I've been through line by line comparing to similar examples and cannot spot it. Please could you help?

This is my code:

#!/usr/bin/env python

from argparse import ArgumentParser
import numpy as nm

import sys
sys.path.append('.')
from sfepy.base.base import output, Struct, IndexedStruct
from functools import partial
from sfepy.base.base import IndexedStruct
from sfepy.discrete import (FieldVariable, Material, Integral, Function,
                            Equation, Equations, Problem)
from sfepy.discrete.fem import Mesh, FEDomain, Field
from sfepy.terms import Term
from sfepy.discrete.conditions import Conditions, EssentialBC
from sfepy.discrete.conditions import Conditions, InitialCondition
from sfepy.solvers.ls import ScipyDirect
from sfepy.solvers.nls import Newton
from sfepy.mechanics.matcoefs import stiffness_from_lame
import sfepy.mechanics.matcoefs as mc
from sfepy.solvers import Solver
from sfepy.solvers.ts_solvers import SimpleTimeSteppingSolver
from sfepy.solvers.ts_solvers import BatheTS
from sfepy.solvers.ts_solvers import CentralDifferenceTS
from sfepy.solvers.ts_solvers import VelocityVerletTS
from sfepy.solvers import Solver

def main():
    mesh = Mesh.from_file('C:\\Temp\\block.mesh')
    domain = FEDomain('domain',mesh)

    omega = domain.create_region('Omega', 'all')
    gamma1 = domain.create_region('Gamma1',
                                  'vertices in y < -0.109',
                                  'facet')
    tx = domain.create_region('Tx','vertex 0','vertex')

    field = Field.from_args('fu', nm.float64, 'vector', omega,approx_order=2)

    u = FieldVariable('u', 'unknown', field)
    du = FieldVariable('du', 'unknown', field)
    ddu = FieldVariable('ddu', 'unknown', field)
    v = FieldVariable('v', 'test', field, primary_var_name='u')
    dv = FieldVariable('dv', 'test', field, primary_var_name='du')
    ddv = FieldVariable('ddv', 'test', field, primary_var_name='ddu')

    E = 200.0e9 ; nu = 0.3 ; rho = 7800.0
    lam, mu = mc.lame_from_youngpoisson(E, nu)
    m = Material('m', D=stiffness_from_lame(dim=3, lam=lam, mu=mu),rho=rho, lumping=0.0, beta=0.0)

    # Longitudinal and shear wave propagation speeds.
    cl = nm.sqrt((lam + 2.0 * mu) / rho)
    cs = nm.sqrt(mu / rho)

    integral = Integral('i', order=1)

    # Time-stepping parameters.
    # Note: the Courant number C0 =  dt * cl / H
    dt = 2.0e-8
    print('dt=', dt)

    t1 = Term.new('dw_volume_dot(m.rho, ddv, ddu)',integral, omega, m=m, ddv=ddv, ddu=ddu) 
    #t1 = Term.new('de_mass(m.rho,m.lumping, m.beta, ddv, ddu)',integral, omega, m=m, ddv=ddv, ddu=ddu) 
    t2 = Term.new('dw_zero(dv, du)',integral, omega, dv=dv, du=du)
    t3 = Term.new('dw_lin_elastic(m.D, v, u)',integral, omega, m=m, v=v, u=u)

    eq = Equation('balance',t1+t2+t3)
    eqs = Equations([eq])

    def shift_u_fun(ts, coors, bc=None, problem=None, shift=0.0):
        print('lalala:'+str(ts.time))
        if ts.time < 2.0e-5:
            val = 0.00001 * nm.sin(ts.time * 50000.0*nm.pi*2.0)
            print(val)
        elif ts.time >= 2.0e-5:
            val = 0.0 * nm.sin(ts.time * 50000.0*nm.pi*2.0) 
        return val
    
    bc_fun = Function('shift_u_fun', shift_u_fun)
    shift_u = EssentialBC('shift_u', tx, {'u.0' : bc_fun, 'du.all' : 0.0, 'ddu.all' : 0.0})
    fix_u = EssentialBC('fix_u', gamma1, {'u.all' : 0.0, 'du.all' : 0.0, 'ddu.all' : 0.0})
    #in_u = InitialCondition('in_u', omega, {'u.all' : 0.0})
     
    
    #ls = ScipyDirect({'use_presolve' : True})
    ls = ScipyDirect({})
    nls_status = IndexedStruct()
    nls = Newton({}, lin_solver=ls, status=nls_status, i_max=1, eps_a=1.0e-6, eps_r=1.0e-6)

    pb = Problem('elasticity', equations=eqs)
    #pb.save_regions_as_groups('regions')
  

  
    tss = SimpleTimeSteppingSolver({'t0' : 0.0, 't1' : 2.0e-6, 'n_step' : 100}, nls=nls, context=pb, verbose=True, save_times=all)
    var_names = {'u' : 'u', 'du' : 'du', 'ddu' : 'ddu'}
    #tss = BatheTS({'t0' : 0.0, 't1' : 2.0e-6, 'n_step' : 100, 'is_linear' : True, 'var_names' : var_names}, nls=nls, context=pb, verbose=True)
    #tss = VelocityVerletTS({'t0' : 0.0, 't1' : 2.0e-6, 'n_step' : 100}, is_linear=True, var_names=var_names, nls=nls, context=pb, verbose=True)
    #tss = CentralDifferenceTS({'t0' : 0.0, 't1' : 2.0e-6, 'n_step' : 100, 'is_linear' : True, 'var_names' : var_names}, nls=nls, context=pb, verbose=True)
  
  

    #pb.set_bcs(ebcs=Conditions([shift_u,fix_u]))
    pb.set_bcs(ebcs=Conditions([shift_u]))
    #pb.set_ics(ics=Conditions([in_u]))
    pb.set_ics(ics=Conditions([]))
    

    pb.set_solver(tss)
    #pb.time_update(ebcs=Conditions([shift_u,fix_u]))
    #pb.update_materials()

    status = IndexedStruct()
    variables = pb.solve(status=status)

    #print('Nonlinear solver status:\n', nls_status)
    print('Stationary solver status:\n', status)

    pb.save_state('linear_elasticity.vtk', variables)

#    out = []
#    pb.solve(save_results=False, step_hook=partial(apply_sensor, out=out))
#    usens = nm.concatenate(out)

#def apply_sensor(pb, ts, state, out):
#    us = state['u'].get_state_in_region(pb.domain.regions['Gamma1'])
#    output('tx', ts.step, us)
#    out.append(us)

if __name__ == '__main__':
    main()

**Comment by rc** [comment]
I am assuming you are using the mesh `meshes/3d/block.mesh`. When I look at your regions, it seems that Tx (which should move) is inside Gamma1 (which is fixed). That would be OK, as BCs are applied in alphabetical order (key is the BC name), but the Gamma1 region seems to cover not only the surface facets but the whole cells. Then nothing can move.

**Comment by dalek-caan11** [comment]
Thank you very much for getting back to me on this, it is much appreciated. Yes, it is meshes/3d/block.mesh that I am using. 

Thank you for pointing out my potential silly mistake of having conflicting boundary conditions. I originally had Gamma1 fixed but I think I have taken that out of the boundary conditions by only including shift_u here: pb.set_bcs(ebcs=Conditions([shift_u])), unless I have misunderstood that command? 

To be sure, I have also instead just tried running with:

gamma1 = domain.create_region('Gamma1',
                                  'vertices in y > 0.99',
                                  'facet')

and pb.set_bcs(ebcs=Conditions([shift_u,fix_u]))

so that fix_u is included and I still have the same problem of zeroes everywhere. Any other suggestions?

**Comment by rc** [comment]
Try the following:

- Set the quadrature order to 2 * approximation order.
- Specify ordering of variables:
  ```
    u = FieldVariable('u', 'unknown', field, 0)
    du = FieldVariable('du', 'unknown', field, 1)
    ddu = FieldVariable('ddu', 'unknown', field, 2)
  ```
- All variables must have exactly the same DOFs constrained - they are not indepentent, so:
  ```
    shift_u = EssentialBC('shift_u', tx, {'u.0' : bc_fun, 'du.0' : 0.0, 'ddu.0' : 0.0})
  ```
  but this is OK only for constant bc_fun. For a varying one you need to replace the zeros by the derivatives w.r.t. time.
- Start with an implicit solver, e.g.
  ```
    tss = NewmarkTS({'t0' : 0.0, 't1' : 2.0e-7, 'n_step' : 10, 'is_linear' : True, 'var_names' : var_names}, nls=nls, context=pb, verbose=True)
  ```

Then there is a non-zero displacement visible.

**Comment by dalek-caan11** [comment]
This has sorted the problem, thank you so much!
