### ISSUE TITLE
sfepy-view doesn't work

### ISSUE THREAD

**Issue by TaoChee** [sfepy/sfepy#1046]
![issue_sfepy-view_01](https://github.com/sfepy/sfepy/assets/135580111/c48e8f70-fe37-4f72-80cb-a13e63a31208)
![issue_sfepy-view_02](https://github.com/sfepy/sfepy/assets/135580111/d8e75e27-8dc6-40ce-a3db-ced700ce35b6)
Hi all,
I am new to the sfepy. Currently I am trying to follow the example (i.e., linear_elastic_interactive.py) in the Tutorial. It works fine and the result (linear_elasticity.vtk) can also be read by the ParaView.
However, the command "sfepy-view linear_elasticity.vtk" in the Anaconda Prompt doesn't work and the error is as below:
    ImportError: DLL load failed while importing vtkFiltersParallelDIY2: The specified module could not be found.
Then I checked the site-packages folder and could find the file "vtkFiltersParallelDIY2.pyi". Could it be an issue that the file is .pyi type, not .py? How can I solve the issue?
Looking foreward to the answer, thank you very much!
Chee

**Comment by rc** [comment]
FWIW, I have managed making pyvista (and hence sfepy-view) work on Windows with conda by installing miniconda instead of anaconda. It seems that some package in anaconda causes a VTK version mismatch.

**Comment by TaoChee** [comment]
Thank you Robert. I am using the company laptop, I cannot try with miniconda at the moment. But I will keep this in mind.

**Comment by TaoChee** [comment]
After some updates on my laptop, the problem was solved. No idea how it really worked, but I can now use the sfepy-vew.
