### ISSUE TITLE
`ValueError: warp violation!` on a simple problem

### ISSUE THREAD

**Issue by numenic** [sfepy/sfepy#1077]
Hello, 
I'm trying sfepy since a couple of days and stuck on a weired issue.

Ubuntu 22.04, main libraries:

* Sfepy 2023.4
* meshio 5.3.5
* numpy 1.26.4
* pyvista 0.43.3
* gmsh 4.12.2

I reduced the issue to the two two provided test-cases, which are roughly similars. One (S0) is working fine, the second one (S1) is failingwith a ``warp violation`` error.

The 2D (made of quads) test case consists in a plate clamped at its top and bottom edge, and loaded in-plane by several nodal loads (issue is the same with a single load). 

The only difference between those test-cases is the meshing process. But checking the meshes (in GMSH or Paraview) does not reveal anything wrong with S1.

Both meshes run fine on NASTRAN, but S1 is failing with Sfepy

In each Zip you will find the original mesh (``.msh``), the converted input mesh (``.vtk``) and the sfepy script ran using ``sfepy-run``.

[S0.zip](https://github.com/sfepy/sfepy/files/14226367/S0.zip)
[S1.zip](https://github.com/sfepy/sfepy/files/14226368/S1.zip)

by the way, I'm really impressed by sfepy. Congratulations guys!

**Comment by numenic** [comment]
OK, I found a workaround by removing 1D elements that were still there after the mesh. I still don't understand why it is working in one case, and not in the second one.

Maybe it could be use full to raise the "warp violation" with failing cells Ids?

**Comment by rc** [comment]
FWIW, this error occurs when there are cells with negative volumes. @vlukes recently added some support for meshes with entities with several topological dimensions, but there might be some rough edges. It is safer to remove the unneeded cells as you did.
