### ISSUE TITLE
QUESTION: How to create Regions from mesh file using cell IDs specified in file?

### ISSUE THREAD

**Issue by jaimeag2000** [sfepy/sfepy#1086]
I have a mesh from file `Mesh.from_file()` in the **_.hmascii_** format. 
I am trying to create regions based on asssigned poperties and element types.
What I want to accomplish is the following **(bold):**

**Intersecting regions: Create regions based on cell type and property assignment**

For instance, let's say 'Property 1' in the imported file has been previously assigned to both quad elements and tria elements. And I want to create two subregions out of it in orde to solve a linear elastic PDE:  One with the quad elements and another one with trias.

ASSUMPTIONS: 
1. I have a mesh of 1370 elements (let's say) with 1300 quads and 70 trias (2D elements in 3D space)
2. I am able to read the contents of the file separately, so although mesh does not have property information, I am able to retrieve which cell IDs have which property in the imported file.

Using `mesh.cmesh.cell_types` I am able to get a list of 1370 elements with the type of element given as an integer.
Since I have the internal IDs, I can connect the previous list with the corresponding cell.

PROBLEM:
The problem arises whenever I read a file with non-supported elements such as CFAST, CBUSH, etc.
For example, in a file of 1380 elements: 1300 quads, 70 trias and 10 cfast. `Mesh.from_file()`, ignores those elements so I have 1370 elements. Therefore, I have a mismatch between internal cell IDs assigned by cmesh and the actual internal IDs. 

QUESTIONS:
Does cmesh store cell IDs (image below) anywhere instead of internal IDs, and is there a way to access them?
![image](https://github.com/sfepy/sfepy/assets/162987554/f8bb69c2-efca-4472-96fc-94fb1ef3bcc6)

Thank you very much in advanced for your help!

**Comment by rc** [comment]
The original cell IDs are not stored in cmesh. But maybe you can use `cmesh.cell_groups`? See `Mesh._get_io_data()` for how to obtain all the data from a cmesh instance. Does it help?

**Comment by vlukes** [comment]
I suggest using [meshio](https://pypi.org/project/meshio/) to preprocess your mesh file. Remove the unsupported elements and set 'mat_id' cell data in order to distinguish different quads and trias regions. For instance: quadrilateral regions have 'mat_id' 101, 102, ..., and triangular regions 201, 202, ... Then use `regions = {'quad1': ' cells of group 101', 'tri1': 'cells of group 202', ...}` to define regions in SfePy.

**Comment by jaimeag2000** [comment]
Thank you both for your reply @rc @vlukes !

@rc : `cmesh.cell_groups` is somewhat similar to `cmesh.cell_types` for what I want to accomplish, but I'll look into `Mesh._get_io_data()` to see if I can get it. Thank you!

@vlukes : I had not thought about that. I am not familiar with how Meshio works, but maybe in that way I can reduce several lines of code. Thank you as well!

I am currently trying to do it the inefficient way via substracting actual internal ID vs expected internal ID since I know that my unsupported elements are located at the beginning of the file.

I'll close the issue and reopen it once I try both of your suggestions.

**Comment by jaimeag2000** [comment]
Could not find a general way to do so, but I was able to manage it somehow with the functions inside cmesh as proposed by @rc 
Examples: 
```aaaa = mesh.cmesh.cell_types
bbbb = mesh.cmesh.get_conn(0, 3).indices
eeee = mesh.cmesh.cell_groups
ffff = mesh.cmesh.conns```

Closing the issue
