### ISSUE TITLE
Working with Shell10X using imported file

### ISSUE THREAD

**Issue by jaimeag2000** [sfepy/sfepy#1093]
Dear all,

I have been looking at the interactive example of the Shell10X cantilever beam, and from what I understand, the core concept of working with dw_shell10x is to 'transform' the 2D mesh into 3D by adding zeros into the third coordinate of the mesh. 

Nevertheless, I wanted to seek advice on how to procedd with an imported 2D mesh. Is there any way to do this transformation? I was thinking that like in the example:
```
    coors = nm.c_[_mesh.coors, nm.zeros(_mesh.n_nod, dtype=nm.float64)]
    coors = nm.ascontiguousarray(coors)

    conns = [_mesh.get_conn(_mesh.descs[0])]

    mesh = Mesh.from_data(_mesh.name, coors, _mesh.cmesh.vertex_groups, conns,
                          [_mesh.cmesh.cell_groups], _mesh.descs)
```
should work fine. However, this transformation might change connectivities and thus cell IDs, which is a problem to assign regions or materials.

I have been working with this simple .hmascii example as to try it: 
- Region1 (grey) with material 1 and Region 2 (maroon) with material 2.
- Three clamped BCs plus a point load, all defined as EBCS
[square_trial.txt](https://github.com/sfepy/sfepy/files/14736426/square_trial.txt)
![image](https://github.com/sfepy/sfepy/assets/162987554/9d0b3bca-83fb-4f00-8aa0-614019b566a2)
The goal is to do a linear elastic analysis with two integrals (one per region). For instance:

```
ftest = Field.from_args(f'fu', dtype = np.float64, shape = 6, region = omega, approx_order=1, poly_space_base = 'shell10x')
nu = FieldVariable(f'u', 'unknown', field = ftest)
nv = FieldVariable(f'v', 'test', ftest, primary_var_name=f'u')


## Setting-up the equation
ti = []
integral = []
qp_coors_list = []; qp_weights_list = []


for i, region in enumerate(regions):

    matKey = regions[i].name

    custom_integral = Integral('i', order=3)
    qp_coors, qp_weights = custom_integral.get_qp(qp[i])
    qp_coors_list.append(qp_coors)
    qp_weights_list.append(qp_weights)
    #qp_coors_list[i][:, 2] = 0
    qp_weights_list[i] *= thickness[i]

    integral.append(Integral('i', coors = qp_coors_list[i], weights = qp_weights_list[i], order='custom'))

    ti.append(Term.new('dw_shell10x(m.D, m.drill, v, u)', integral[i], regions[i], m=matSections[matKey], v=nv, u=nu))
    if i == 0:
        t2 = ti[i]
    else:
        t2 = t2 + ti[i]


eq = Equation('balance_of_forces: shell', t2)
eqs = Equations([eq])

## Setting-up the solver
ls = ScipyDirect({})
nls_status = IndexedStruct()
nls = Newton({'i_max': 1, 'eps_a': 1e-10}, lin_solver=ls, status=nls_status)

## Setting-up the problem

pb = Problem('elasticity', equations=eqs)


conditions = Conditions(bc)

# Then, use the dictionary when setting the boundary conditions
pb.set_bcs(ebcs=conditions)
```

Thank you and kind regards

**Comment by rc** [comment]
Some notes:

- In the `shell10x_cantilever_interactive.py` example, the manual addition of the zeros z coordinate is required because of the limitations of the `gen_block_mesh()` function. You could generate such planar 3D mesh directly using a different software, then no 2D -> 3D transformation would be needed.
- When you do want to use `gen_block_mesh()`, then there is no problem with changing the cell connectivity and ids.

So what about generating your .hmascii file already with the third coordinate? @vlukes recently added support for reading 3D meshes with lower dimensional entities, so I am curious whether that would work in your case.

**Comment by jaimeag2000** [comment]
Dear @rc thank you for your response. Thank you as well for the cIarifications regarding the 2d->3d transformation. I managed to make it work as you explained. Kind regards!
