### ISSUE TITLE
Output data not found

### ISSUE THREAD

**Issue by songhanzhang** [sfepy/sfepy#1121]
![Screenshot 2024-06-25 103804](https://github.com/sfepy/sfepy/assets/67284799/3f56f0ed-a270-47bd-a11f-402936583f0b)

Hi, I am a freshman in SfePy, and I am trying to follow the example "linear_elastic.py" (where a few dictionary issues have been fixed from my side).

When I click the "run" button, the example codes can now be executed without any error message, and I expect that the output "displacement of each vertex" will be saved to the file "cylinder.vtk" as described in the tutorial. However, I cannot find any updated "cylinder.vtk" file except for the original meshed model.

So, I assume that the example code is incomplete? Perhaps some additional commands should be added for solving and data saving?

**Comment by rc** [comment]
This example uses the declarative problem description, so simply running it with python does nothing besides importing the file. You need to run it using `sfepy-run linear_elastic.py` (assuming the file is in your working directory, or use the full path to the file). On windows, the runner script is probably called `sfepy-run.exe`.

**Comment by songhanzhang** [comment]
> This example uses the declarative problem description, so simply running it with python does nothing besides importing the file. You need to run it using `sfepy-run linear_elastic.py` (assuming the file is in your working directory, or use the full path to the file). On windows, the runner script is probably called `sfepy-run.exe`.

Many thanks for helping! I tried "sfepy -run linear_elastic.py", but it returns "'sfepy-run' is not recognized as an internal or external command, operable program or batch file.". I think a complete installation (in addition to downloading and extracting the source codes) is needed.

I tried to install following the instructions https://sfepy.org/doc-devel/installation.html. Unfortunately, none of the approaches works (see below) even I have already installed a huge amount of relevant packages as required.

![Screenshot 2024-06-25 115801](https://github.com/sfepy/sfepy/assets/67284799/a2af89f5-f5c4-45a8-aa5e-4573a6ccb3b9)

As I wish to connect SfePy with my self-developed mesh code (which generates the xxx.mesh for my own model), I need to include everything in a Python scrip (along with the downloaded SfePy source codes) avoiding switching between python and cmd (even now the commands do not work in cmd due to installation issues). Is there any instructions (preferably with examples) that can help to work with the source codes directly for solving?

Thank you!

**Comment by rc** [comment]
You can try
```
pip install -U "numpy<2"
```
followed by the instructions in https://github.com/sfepy/sfepy/issues/1118#issuecomment-2186774964

As for getting the sources:
```
git clone https://github.com/sfepy/sfepy.git
```
should work without any login.

**Comment by rc** [comment]
FYI: 2024.2 is out, and `pip install sfepy` should work correctly now.

**Comment by songhanzhang** [comment]
> FYI: 2024.2 is out, and `pip install sfepy` should work correctly now.

Thanks for the suggestion. I have now installed the miniconda and the analysis can be executed by "sfepy-run xxx.py".

**Comment by rc** [comment]
Glad to to hear that, closing.
