### ISSUE TITLE
Import self-created meshed model

### ISSUE THREAD

**Issue by songhanzhang** [sfepy/sfepy#1123]
Hi,

I have created a meshed model from my in-house python code, where the node and element information are written in numpy form such like:

Nodes = np.array([
[0,0,0],
[1,0,0],
[1,1,0],
[0,1,0],
[0,0,1],
[1,0,1],
[1,1,1],
[0,1,1],
])

Elements = np.array([
[1,2,3,4,5,6,7,8]
])

I would like to direct import such model for analysis (without needing any further mesh from SfePy). So, is there a simple approach that I can directly convert the variable Nodes and Elements into the mesh model such like:

Mesh = Sfepy.xxx(Nodes,Elements)

Thank you!

**Comment by rc** [comment]
See the function [`Mesh.from_data()`](http://sfepy.org/doc-devel/src/sfepy/discrete/fem/mesh.html#sfepy.discrete.fem.mesh.Mesh.from_data) as used e.g. in [this example](https://sfepy.org/doc-devel/examples/linear_elasticity-multi_point_constraints.html).

**Comment by songhanzhang** [comment]
Thanks for sharing the example. Problem solved!

**Comment by rc** [comment]
Hth, closing.
