### ISSUE TITLE
How to use the pre-defined sets in the .inp file of Abaqus?

### ISSUE THREAD

**Issue by TaoChee** [sfepy/sfepy#1133]
Hello,
I modelled a simple 2D disk in Abaqus and predefined some sets as shown below:
...
*Nset, nset=Set_All, generate
  1,  58,   1
*Elset, elset=Set_Left
  1, 12, 17, 44, 49, 51, 53
*Nset, nset=Set_Top
 2,
...
When I try to define a region by specifying the vertex number, it works as shown below.
regions = {
    'Top' : ('vertex 1', 'vertex'), 
}
However, how can I refer to the vertex ('Set_Top') I specified in the .inp file?

Thanks!
Br, Chee

**Comment by rc** [comment]
The Abaqus format is supported via the meshio package, I am not sure this is supported. It looks like the sfepy meshio reader supports only non-overlapping vertex groups, not possibly overlapping vertex sets. Is that so, @vlukes ?

**Comment by vlukes** [comment]
> The Abaqus format is supported via the meshio package, I am not sure this is supported. It looks like the sfepy meshio reader supports only non-overlapping vertex groups, not possibly overlapping vertex sets. Is that so, @vlukes ?

Yes, only non-overlapping vertex groups are supported in the sfepy reader.

**Comment by TaoChee** [comment]
Thank you for the comments.
This issue can be closed, since I will develop a converter for my applications to convert the Abaqus .inp files to .mesh.
