### ISSUE TITLE
Where to find the documentation for the Visualization?

### ISSUE THREAD

**Issue by TaoChee** [sfepy/sfepy#1134]
Hello,

There are quite a few examples in the sfepy_manual. But nowhere does it describe how to use the visualization function. For example, the following command line was given in the manual:
sfepy-view navier_stokes.vtk -f p:i5:p0 p:e:o.2:p0 u:t1000:p1 u:o.2:p1
But what does "-f" mean? and how about "p:i5:p0"?
Where can I find the relevant documentation for visualization?

Thanks!
Br, Chee

**Comment by rc** [comment]
The options are described in the help message of `sfepy-view` - try running `sfepy-view --help`.

**Comment by TaoChee** [comment]
Thank you Robert! It is helpful.

**Comment by rc** [comment]
Hth, closing... Feel free to ask more.
