### ISSUE TITLE
Can not create a movie

### ISSUE THREAD

**Issue by TaoChee** [sfepy/sfepy#1136]
Hello,
I have run the example of diffusion/time_poisson.py and got 11 .vtk results (cylinder.00.vtk to cylinder.10.vtk). I tried to create an animation using "sfepy-view cylinder.*.vtk -a mov.mp4" and received below error:

FileNotFoundError: File (D:\Others\Projects\Simulation\myModul\sFEpy\Ex02_04_Diffusion_Time_Poisson\cylinder.*.vtk) not found

If I run below code, I could create the movie.
sfepy-view cylinder.00.vtk cylinder.01.vtk cylinder.02.vtk cylinder.03.vtk cylinder.04.vtk cylinder.05.vtk cylinder.06.vtk -a mov.mp4

Does it mean I have to put all the .vtk files to the command line for creating a movie?

Thanks!
Chee

**Comment by rc** [comment]
It looks like the `*` wild card is not expanded properly. Maybe try a different shell?

**Comment by TaoChee** [comment]
Since i am using the company laptop, it is difficult to have another shell. I have to leave it as it is now :-(

**Comment by rc** [comment]
You can add `'output_format' : 'h5'` to the options dict and than have all the time steps in a single file.

**Comment by TaoChee** [comment]
Thank you very much! It works :-)
