### ISSUE TITLE
Thermal simulation error: Factor is exactly singular

### ISSUE THREAD

**Issue by TaoChee** [sfepy/sfepy#1138]
Hello,

I am trying to use the SfePy for thermal simulations. 
Therefore, I first created a model in Abaqus and did the simulation. Then I manually transferred the Abaqus mesh file (.inp) to .mesh  format which can be read by the SfePy. Finally I wrote the "Problem Description.py" and tried to run it by using "sfepy-run". However, I received the error message: "RuntimeError: Factor is exactly singular".

I attached all the relavent files below.
Can anyone be so kind to take a look and solve the issue?

Br, Chee

[Error Message_20240819.txt](https://github.com/user-attachments/files/16661012/Error.Message_20240819.txt)
[Problem Description_20240819.pdf](https://github.com/user-attachments/files/16661013/Problem.Description_20240819.pdf)
[Model.mesh.txt](https://github.com/user-attachments/files/16661029/Model.mesh.txt)
[Problem Description.py.txt](https://github.com/user-attachments/files/16661030/Problem.Description.py.txt)

**Comment by vlukes** [comment]
Hi,

You have a mesh with 126356 nodes

`sfepy:   number of vertices: 126356`

and the dimension of  the resulting linear system is 126356x126356

`sfepy: matrix shape: (126356, 126356)`

This means that the system is singular and can not be solved. You need to apply some boundary conditions to make the problem solvable. You can use either Dirichlet boundary conditions (`ebcs`) or linear combination boundary conditions (`lcbcs`), see eg. [this example](https://sfepy.org/doc-devel/examples/diffusion-laplace_coupling_lcbcs.html).

Regards
Vladimir

**Comment by vlukes** [comment]
Hi,

I think that the problem is in the definition of regions. `HeatSource` is a volume region, not a surface.  If I remove `'HeatSource': ('r.All_Si', 'facet')` and rename `All_Si` as `HeatSource` then it works for me even without boundary conditions.

VL

**Comment by TaoChee** [comment]
Hi,
That is the root cause! Thank you!!
Now i got the similar result as Abaqus (max. T:  78.6°C vs. 79.96°C; min. T: 25.3°C vs. 25.46°C).
The slight difference shall be caused by the material properties (In Abaqus, the temperature-dependent lambda is used, since I don't know yet how to introduce the T-dependent properties into SfePy. I will investigate later). 
![Results_20240820](https://github.com/user-attachments/assets/a94f884d-3cec-4f30-9dfd-4aa4b531b92b)
