### ISSUE TITLE
elastodynamic_identification.py fails with the external MUMPS wrappers

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#1159]
To run
```
python3 sfepy/examples/linear_elasticity/elastodynamic_identification.py
````
one needs first to increase `'memory_relaxation'` to 100, which was not required previously, and then the Jacobian calculation fails with nans in the solution. When debugging on line 580, the solutions are completely wrong. This happens both with `mumpspy` and `python-mumps`. Any ideas, @vlukes ?

**Comment by vlukes** [comment]
I will check it.
