### ISSUE TITLE
Linear elastic anisotropic materials

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#118]
We have functions for isotropic materials, can this function be extended to
deal with anisotropy.<p>Migrated from http://code.google.com/p/sfepy/issues/detail?id=116</p><hr/><h2>earlier comments</h2>

<p><strong>robert.cimrman said, at 2010-04-12T13:10:13.000Z:</strong></p>

<p>See dw_lin_elastic, which accepts the material parameters in the general tensor form
- example use is e.g. in examples/biot/biot_npbc.py ...

</p><p><strong>freevryheid said, at 2010-04-12T14:30:47.000Z:</strong></p>

<p>Please expand - to set the anisotropic material parameters in the 3 dimensions would
you need to do something like this:

        out['D'] = nm.tile(stiffness_tensor_lame(dim, lam=1.7, mu=0.3),
                           (coor.shape[0], 1, 1))
        out['D'] = nm.tile(stiffness_tensor_lame(dim, lam=2.7, mu=0.4),
                           (coor.shape[0], 2, 2))
        out['D'] = nm.tile(stiffness_tensor_lame(dim, lam=3.7, mu=0.45),
                           (coor.shape[0], 3, 3))

A
</p><p><strong>robert.cimrman said, at 2010-04-12T14:40:17.000Z:</strong></p>

<p>You do not need stiffness_tensor_lame() at all - this function just builds the tensor
using the two Lame constants.

So to have anisotropic material, set the components of D directly. It is a 6x6 tensor
in 3D, 3x3 in 2D, with the order of components described in [1] - it is 11 22 33 12
13 23 in 3D, 11, 22, 12 in 2D. There is also explained the relation of isotropic D to
the Lame constants.

As an example of anisotropic material, an orthotropic material can be defined as
described at [2].

[1] http://docs.sfepy.org/doc-devel/src/sfepy/mechanics/matcoefs.html
[2] http://en.wikipedia.org/wiki/Hooke%27s_law#Orthotropic_materials</p>

**Comment by ArvindChandramowliswaran** [comment]
Following from the conversation,

I want to explore anisotropic thermal expansions. (Have three different thermal expendabilities in three different directions for a 3D case!) 

I have taken the code snippet from https://sfepy.org/doc-devel/examples/multi_physics-thermo_elasticity.html

_eye_sym = np.array([[1], [1], [1], [0], [0], [0]], dtype=np.float64)
materials = {
    'solid' : ({
        'D' : stiffness_from_lame(3, lam=lam, mu=mu),
        'alpha' : (3.0 * lam + 2.0 * mu) * thermal_expandability * eye_sym
    },),_

Should I define thermal expandability as an array of three elements!?
I understand that eye_sym is the Kronecker Delta by theory! Do I have to change the eye_sym values to make 'alpha' anisotropic ?

Thank you for the help! Apologies for trivial mistaken assumptions as I am just learning!!

**Comment by rc** [comment]
The components in `alpha` are ordered as 11, 22, 33, 12, 13, 23. If you change them not to be a scalar multiple of `eye_sym`, you get anisotropy.

**Comment by ArvindChandramowliswaran** [comment]
> The components in `alpha` are ordered as 11, 22, 33, 12, 13, 23. If you change them not to be a scalar multiple of `eye_sym`, you get anisotropy.

Thank you for your response :)

Just to clarify!

Should I define alpha newly as..

Alpha = K(constant term with Lame's constants) * (( thermal_exp_1* eye_sim_1) + (thermal_exp_2*eye_sim_2) +(thermal_exp_3*eye_sim_3)) 

So that I "encapsulate" anisotropy together via the three individual scalar products!

Cheers,

**Comment by rc** [comment]
Yes, or just replace the ones in `eye_sym` by other values, to get an orthotropic material.
