### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#164]
As our dependencies are commencing to work in Python 3 (e.g. both NumPy and SciPy do), we should start thinking about it as well. I would like to have a single code base, that work for pythons 2.6(?) - 3.x (is this possible without too much hassle?).

Comment here, please, if you have some experience/thoughts in this area.
<p>Migrated from http://code.google.com/p/sfepy/issues/detail?id=162</p><hr/><h2>earlier comments</h2>
<p><strong>rashed.golam said, at 2011-12-21T12:52:06.000Z:</strong></p>
<p>we should make a dependencies list and see whats its status on porting to python 3.</p><p><strong>robert.cimrman said, at 2011-12-22T11:22:45.000Z:</strong></p>
<p>Yes - a new wiki page here (PortingToPython3) might work well for this purpose.</p>

**Comment by takluyver** [comment]
Hi all, I offered on the Scipy user mailing list to help with the porting effort.

The first thing is to make sure that all the dependencies support Python 3. I went through the list, and pysparse, which looks like a dead project, appears to be Python 2 only. I haven't looked at what sfepy does with it, but would it be possible to drop the dependency in favour of something maintained like scipy.sparse?

It's also not clear whether [igakit](https://bitbucket.org/dalcinl/igakit/src) supports Python 3. It still seems to be actively maintained however. Checking this would be a good first step for someone to do.

After that, a lot of the changes will be straightforward, and can be done by running [python-modernize](http://python-modernize.readthedocs.io/en/latest/) over the code base. This takes care of things like `print` -> `print()` and `except ValueError, e` -> `except ValueError as e`. Python-modernize is based on 2to3, but keeps the code Python 3 compatible. It's up to you how you want to commit these changes - I might run one fixer at a time and commit after each, but you could do it as one big change, or break it up by chunks of the project.

Finally, there will be some changes that python-modernize can't handle. Hopefully these won't be too numerous - I just ran `python-modernize` on the whole lot, and with <10 manual changes on top of that it's gone from all tests failing to only half of them.

**Comment by rc** [comment]
Wow that was quick, thank you! Either me or @BubuLK will look at this ASAP.

Dependencies:

- pysparse is used only for its (very good) eigenvalue problem solvers - it is an optional dependency. We use scipy.sparse for the sparse matrices and everything else.

- igakit is also only an optional dependency, so it is not critical to have it at the beginning. We can ping the author later.

SfePy uses ``output()`` function to print messages, so ideally, there should be no print statements - the ones left there are more or less debug stuff that could be removed - this should be pretty easy.

Are there any problems to be expected with the C/cython extension modules?

I will check python-modernize.

**Comment by takluyver** [comment]
> Are there any problems to be expected with the C/cython extension modules?

Stuff written in Cython should mostly be very easy - Cython already takes care of producing Python 2/3 compatible C code. If you have extension modules written directly in C, it's a bit trickier, and not something I know much about. The Python docs have a guide on [porting extension modules](https://docs.python.org/3/howto/cporting.html). At a quick look, though, it looks like the .c files are pure C code which are wrapped in Cython, so hopefully that's not necessary.

**Comment by rc** [comment]
Yes, everything is wrapped using Cython. Glad to hear that it should be a smooth ride.
