### ISSUE TITLE
Integration over mirror region - trace works only for the last argument

### ISSUE THREAD

**Issue by vlukes** [sfepy/sfepy#204]
Integration over mirror region - trace works only for the last argument

dw_jump.isurf.Gamma12_1(..., q1, p1, tr(p2))  - OK
dw_jump.isurf.Gamma12_1(..., q1, tr(p2), p1)  - doesn't work

**Comment by rc** [comment]
@vlukes does this still persists? Is it worth solving?

**Comment by vlukes** [comment]
Obsolete issue, no longer needed.
