### ISSUE TITLE
Improve documentation for interactive use

### ISSUE THREAD

**Issue by wd15** [sfepy/sfepy#265]
This issue was raised for an [exchange on the mailing list](https://groups.google.com/forum/#!topic/sfepy-devel/Zzzl1qz96zI).

In general Sfepy has too many examples of the sort that require "./simple.py example.py" to run as in the [linear elastic example](http://sfepy.org/doc-devel/examples/linear_elasticity/linear_elastic.html).

A number of these example could be switched over to interactive use as in [the tutorial](http://sfepy.org/doc-devel/tutorial.html#interactive-example-linear-elasticity).

Opinion: moving to an interactive approach is far superior and more Pythonic. Also moving away from using any strings for arguments can only be a good thing.

**Comment by rc** [comment]
FYI: http://sfepy.org/doc-devel/examples/standalone/interactive/modal_analysis.html

**Comment by rc** [comment]
There is now a number of interactive examples, so let us close this - we can add more specific issues/enhancement proposals in future.

**Comment by wd15** [comment]
@rc, that link doesn't seem to work.

**Comment by rc** [comment]
It has moved in the meantime to [1]. Note that there are also other new interactive examples, check [2] for those with _interactive in their name.

[1] http://sfepy.org/doc-devel/examples/linear_elasticity/modal_analysis.html
[2] http://sfepy.org/doc-devel/examples/index.html
