### ISSUE TITLE
use argparse instead of optparse

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#281]
As optparse is deprecated since Python version 2.7, it should be replaced by argparse (a part of Python standard library since 2.7).

**Comment by sukhbinder** [comment]
Hi RC, 

With kids and family visiting grandparents, I have some time and can take up this task during the summer. Let me know where to start. 

Thanks

**Comment by rc** [comment]
Great, thanks! It concerns the scripts in script/ and the top-level ones. It should be pretty straightforward, just follow [1]. Also, I will upgrade some of the scripts as an example.

[1] https://docs.python.org/2/library/argparse.html#upgrading-optparse-code

**Comment by sukhbinder** [comment]
Thanks RC. Thanks for the link. I am aware of it and will be using this. Maybe I will begin with the postproc.py script.

I will need your help in the github requests as I am new to it. Thanks

**Comment by rc** [comment]
Sure! Feel free to ask on our ML, or here.

**Comment by heczis** [comment]
Are there any tests for this? Should they be written at all?

**Comment by rc** [comment]
There are no tests, besides the ones in test_install.py.

I do not think we need tests for this - just a manual verification that each option works after the change as it used to work before should be enough. The only "tricky" options are the one with custom parsers and/or choices.
