### ISSUE TITLE
new logo?

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#303]
Two proposals for logos with snakes created by Serge-Étienne Parent:

![rect6236](https://cloud.githubusercontent.com/assets/44282/12918490/bceaac74-cf3f-11e5-87ca-248c224a23fc.png)

![rect6240](https://cloud.githubusercontent.com/assets/44282/12918480/b5065530-cf3f-11e5-8ec7-ad3bc79386df.png)

Comments and suggestions welcome!
r.

**Comment by BubuLK** [comment]
+1 for second version. Maybe in variant with FEM-like colors (oposit to not-so-easy-understand NTC-like colors).

**Comment by essicolo** [comment]
What do you mean by FEM-like colors?

**Comment by rc** [comment]
On 02/10/2016 05:14 PM, Serge-Étienne Parent wrote:
> What do you mean by FEM-like colors?

Probably coming from a problem solution on a snake-like mesh. The current logo 
is a view of a 3D Poisson problem solution on a cube.

**Comment by BubuLK** [comment]
Many thanks to Robert for explanation ;) and sorry for confusion :(

Please, let me a little bit to clarify my 'shortcut' comment:

  - I really like both logo proposals!
  - BTW: I'm ITC guy and don't really understand all the SfePy/FEM
    math/physics 'magic' :((
  - but...I really appreciate Robert's (and his co-workers)
    effort and really like his Python coding approach :)
  - I'm BIG fan of good typeseting/logos/presentation (including good old Knuth TeX style) 

As far as I understand, current logo proposal is base on
color scheme derived from 'visual style' of
'New Technologies Research Center of University of West Bohemia'
(aka NTC in Czech language, sorry :()
BTW: I'm not big fan of violet colors...

So, my proposal was to create alternative colors scheme (as explained
by Robert) for the Python (or part of them).
Of course, I can't imagine final results and understand possible
problems with printing such colorful logo.

Sorry for my really bad English and hopefully you understand
what I'm trying to explain :)

**Comment by rc** [comment]
On 02/10/2016 10:58 PM, Lubos Kejzlar wrote:
> Many thanks to Robert for explanation ;) and sorry for confusion :(

No need to apologize :)

> Please, let me a little bit to clarify my 'shortcut' comment:
>
>    - I really like both logo proposals!
>    - BTW: I'm ITC guy and don't really understand all the SfePy/FEM
>      math/physics 'magic' :((
>    - but...I really appreciate Robert's (and his co-workers)
>      effort and really like his Python coding approach :)
>    - I'm BIG fan of good typeseting/logos/presentation (including good old Knuth TeX style)
>
> As far as I understand, current logo proposal is base on
> color scheme derived from 'visual style' of
> 'New Technologies Research Center of University of West Bohemia'
> (aka NTC in Czech language, sorry :()
> BTW: I'm not big fan of violet colors...

IMHO the similarity of the colors with my department's 'visual style' was 
coincidental. :)

> So, my proposal was to create alternative colors scheme (as explained
> by Robert) for the Python (or part of them).
> Of course, I can't imagine final results and understand possible
> problems with printing such colorful logo.

**Comment by rc** [comment]
I have googlooked at the logos of other (scientific) Python-related projects. The logos seem to fall mostly into three (non-disjoint) groups:

- a "something", when a project's name is the "something"
- an idealized depiction of what a code does
- an artistic rendering of a projects's name

SfePy's name does not mean anything, so I would say the second point should apply.
In this respect, the snake's shape in the second logo seems sort of arbitrary. The first snake (in different colors as Lubos suggested, maybe with a superimposed solution of a problem), might be also a good choice. Anyway, we like snakes, right? :)

Another possibility might be to mesh the word "SfePy", and/or make the snake out of the "S".

That's my contribution to this topic for the moment, to make the choice even harder :)

**Comment by essicolo** [comment]
New proposals.

![rect4711](https://cloud.githubusercontent.com/assets/5118227/14578956/2a92c86e-0367-11e6-922c-de9d313f6a97.png)
![rect4689](https://cloud.githubusercontent.com/assets/5118227/14578957/2aaa62e4-0367-11e6-98e5-8e2675180a8c.png)

**Comment by rc** [comment]
Wow! I like the first one, but I guess it is too close to the dark side :)

As for "FEM" colors - they have some drawbacks [1] - no need to force them.

[1] https://jakevdp.github.io/blog/2014/10/16/how-bad-is-your-colormap/

The second logo is also cool. I made a little modification with my near-zero gimp skills:

![sfepy-logo-try](https://cloud.githubusercontent.com/assets/44282/14589072/80eeebca-04d9-11e6-97d4-cb5915d57be0.png)

- do not mind the colors - I wanted a white background, so I had used color inversion (but ended up not that bad) =:) Starting from that, I could imagine also the p meshed and enlarged (and maybe also in a circle that I made here by only coincidence), so that the logo is capitalized as in SfePy. Might that be feasible?

**Comment by essicolo** [comment]
Just as I do when I plot data, I first thought I should use colours that are printer- and colour-blind-friendly (http://colorbrewer2.org/), but I ended up piking colours I liked - a matter of taste. Anyways, a black and white logo can be used if the aim is for printing in black and white. I'm not sure how to integrate the S into the name, and adding another mesh for the P might add too much complexity. Just my opinion, I not a graphic designer. I'll browse logos through my spare time to see what I can do. Other comments are still welcomed!

**Comment by rc** [comment]
Hi @essicolo, still around? After a long time, @vlukes took the challenge and updated the sfepy website template - a work-in-progress version can be seen here: http://sfepy.org/new/. A slight modification of one of your logo proposals is used there, do you agree? Comments and suggestions welcome.

**Comment by essicolo** [comment]
Hi @rc , I lost the exact svg but still got the snake. I could create a white and light grey version if it suits you. Or any other version of the proposed logos!

**Comment by vlukes** [comment]
Hi @essicolo, please, could you create the dark and light versions (SVG) of the logo (the first proposal  at the top of this page)? Please do it transparent, without background.

**Comment by essicolo** [comment]
Light variant, for comments.

![sfepy-logo](https://user-images.githubusercontent.com/5118227/77980792-35d5e700-72d6-11ea-9a76-5cecacde412a.png)

**Comment by vlukes** [comment]
Hi @essicolo, great, thanks! I placed your new proposal to the [test web pages](http://sfepy.org/new). I have just one remark:

- The snake eye in the light version is not as distinct as in the dark version. How about making it transparent?

**Comment by rc** [comment]
Hi, nice! What about making the snake a bit smaller - I liked the proportions of the image @vlukes had originally:
![sfepy_logo](https://user-images.githubusercontent.com/44282/78015457-baae1880-7349-11ea-9b23-915c395f3215.png)

What do you think?

Anyway, I will make a release today, with the new web look, and possibly with one of the tentative logos above. We can change the logo at any time later.

**Comment by essicolo** [comment]
![light](https://user-images.githubusercontent.com/5118227/78029659-f7204b00-732e-11ea-8a03-e54286a3c3ba.png)

![dark](https://user-images.githubusercontent.com/5118227/78029653-f2f42d80-732e-11ea-8290-c20a5e5159d5.png)

**Comment by vlukes** [comment]
Nice! Thank you.

**Comment by rc** [comment]
The logo is up and running with the new pages, so we should somehow acknowledge its author (@essicolo, do you have a preference how? PR welcome :)), and close this issue. Thanks for the great work!

**Comment by essicolo** [comment]
Hi, no preference. No need for acknowledgement either. ;)
