### ISSUE TITLE
There is no colors on the Mesh just blue one [Cell_Data is constant in VTK File]

### ISSUE THREAD

**Issue by elbo-01** [sfepy/sfepy#308]
I have installed SfePy with all its dependencies without any errors. But i have encountered this weird problem:
When i run the command `sfepy-run simple examples/diffusion/poisson_short_syntax.py`, the command executed successfully (if i'm right) with cylinder.vtk generated and the output looks like this:
```
$ sfepy-run simple examples/diffusion/poisson_short_syntax.py 
sfepy: left over: ['verbose', '__builtins__', '__file__', '__doc__', '__name__', 'data_dir', '__package__', '_filename']
sfepy: reading mesh [line2, tri3, quad4, tetra4, hexa8] (/usr/local/lib/python2.7/dist-packages/sfepy/meshes/3d/cylinder.mesh)...
sfepy: ...done in 0.01 s
sfepy: creating regions...
sfepy:     Gamma_Right
sfepy:     Omega
sfepy:     Gamma_Left
sfepy: ...done in 0.03 s
sfepy: equation "Temperature":
sfepy: dw_laplace.i.Omega( coef.val, s, t ) = 0
sfepy: using solvers:
                ts: no ts
               nls: newton
                ls: ls
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.00 s
sfepy: matrix shape: (300, 300)
sfepy: assembling matrix graph...
sfepy: ...done in 0.00 s
sfepy: matrix structural nonzeros: 3538 (3.93e-02% fill)
sfepy: updating materials...
sfepy:     coef
sfepy: ...done in 0.01 s
sfepy: nls: iter: 0, residual: 1.176265e-01 (rel: 1.000000e+00)
sfepy:   rezidual:    0.01 [s]
sfepy:      solve:    0.01 [s]
sfepy:     matrix:    0.01 [s]
sfepy: nls: iter: 1, residual: 9.632786e-17 (rel: 8.189296e-16)
```
The same thing with : 
```
$ sfepy-run simple examples/acoustics/acoustics3d.py 
$ sfepy-run simple examples/linear_elasticity/its2D_1.py
```
But when i took a look to the generated VTK file using MayaVi, it doesn't look like what i have expected, everything is blue. (Screenshots and VTK files in the attached file).
[sfepy issue.zip](https://github.com/sfepy/sfepy/files/149952/sfepy.issue.zip)

SfePy version : 2016.1 (but i have the same problem with 2015.4)

**Comment by rc** [comment]
How did you run mayavi? I do see the color ranges as expected in your result files. I have used, for example:

```
sfepy-run postproc cylinder.vtk -b --wireframe
```

When you run directly

```
mayavi2 cylinder.vtk
```

you need to setup the visualisation pipeline manually.

**Comment by elbo-01** [comment]
I have Mayavi 4.4.3 and i am aware of this #292 , 
So i decided to run it directly from Mayavi without using `postproc.py`, can you give me the right visualization pipeline to get the desired result.
Thank you

**Comment by rc** [comment]
Check [1] - for the cylinder.vtk file, you would need (at least) the Surface module, and to select 't' as the point scalars name in the 'VTK file' source.

[1] https://enthought.github.io/mayavi/mayavi/application.html

**Comment by elbo-01** [comment]
Apparently it's my bad, i still need to know a little of Mayavi.
You can close the issue.
Thanks for your time.

**Comment by rc** [comment]
OK!
