### ISSUE TITLE
optional parameters?

### ISSUE THREAD

**Issue by vlukes** [sfepy/sfepy#312]
At least for dw_div_grad, the optional parameter does not work.

Try to remove it from 'examples/navier_stokes/stokes.py', line 140, and run simulation.

-->  ValueError: wrong arguments shapes for "dw_div_grad.2.Y1Y2(v, u)" term! (see above)

**Comment by rc** [comment]
The arg_shapes of dw_div_grad is wrong, it should be:

```
    arg_shapes = [{'opt_material' : '1, 1', 'virtual' : ('D', 'state'),
                   'state' : 'D', 'parameter_1' : 'D', 'parameter_2' : 'D'},
                  {'opt_material' : None}]
```

Can you try rc/sfepy master?

**Comment by vlukes** [comment]
Now it works. Thanks!

**Comment by rc** [comment]
ok
