### ISSUE TITLE
clean-up in terms

### ISSUE THREAD

**Issue by vlukes** [sfepy/sfepy#314]
I have a few suggestions how to simplify and clean up the terms:

 - d_diffusion_sa: rename to d_sd_diffusion
 - dw_bc_newton: remove, can be replaced by dw_surface_dot and dw_surface_integrate
 - dw_lin_elastic_iso: to remove??? always can be replaced by more general dw_lin_elastic + stiffness_from_*
 - *_th and *_eth terms: unify these terms, just one term with the optional material parameter
 -  dw_adj_convect1/2: unify terms -> dw_adj_convect

There are many specific terms, like dw_st_* or d_sd_st_*, so  I would suggest to move "stabilization" and e.g. "sensitivity analysis" terms from the main table into subtables.

**Comment by rc** [comment]
On 03/17/2016 12:16 PM, Vladimir Lukes wrote:
> I have a few suggestions how to simplify and clean up the terms:
>
>   - d_diffusion_sa: rename to d_sd_diffusion

OK

>   - dw_bc_newton: remove, can be replaced by dw_surface_dot and dw_surface_integrate

Yes, it can be replaced by the two terms. But I would keep it, as it implements 
a standard boundary condition, so a "shortcut" is handy.

>   - dw_lin_elastic_iso: to remove??? always can be replaced by more general dw_lin_elastic + stiffness_from_*

Could you measure the speed/memory difference? The only reason I kept 
dw_lin_elastic_iso around was that I assumed it would be more efficient.

If we supported variable number of material arguments in terms, we could merge 
the two terms in one.

>   - *_th and *_eth terms: unify these terms, just one term with the optional material parameter

While those are similar in spirit (but *_eth are not exact!), their 
implementation (and speed) is completely different. I would keep them separated.

>   -  dw_adj_convect1/2: unify terms -> dw_adj_convect

OK, this could be done.

> There are many specific terms, like dw_st_* or d_sd_st_*, so  I would suggest to move "stabilization" and e.g. "sensitivity analysis" terms from the main table into subtables.

OK - the term table is typeset using `script/gen_term_table.py` - it should not 
be difficult to modify it for this purpose.

Thanks for your proposals!
r.

**Comment by vlukes** [comment]
I have performed some speed measurements  with 'dw_lin_elastic_iso' and 'dw_lin_elastic' terms, the results are (execution time of 'eval_tangent_matrices()'):

eval_time_elastic_iso:  [2.458, 2.325, 2.368],  avg: 2.384
eval_time_elastic:        [2.518, 2.409, 2.491],  avg: 2.472

The mesh size was:
   Vertices: 56682
   Tetrahedra: 314248

I think, there are no important difference in speed. I would remove 'dw_lin_elastic_iso'.

VL

**Comment by rc** [comment]
It might be better to make it an alias to 'dw_lin_elastic', that would automatically convert lambda and mu to the stiffness tensor and call the function of  'dw_lin_elastic'. In that way the C functions could be removed, and nothing broken. Note that unlike the other terms, this one is IMHO heavily used.

**Comment by rc** [comment]
This was implemented by #315.
