### ISSUE TITLE
Issue when trying to install sfepy

### ISSUE THREAD

**Issue by nicolas-altran** [sfepy/sfepy#317]
Hi, i encounter some problems when trying to install sfepy with python(x,y). This is the error message i get :

C:\Users\ndelan\Downloads\sfepy>python setup.py build_ext --inplace --compiler=m
ingw32
mayavi (optional) is missing; you may get run-time errors
sympy (optional) is missing; some tests are going to fail!
igakit (optional) is missing; you may get run-time errors
petsc4py (optional) is missing; you may get run-time errors
mpi4py (optional) is missing; you may get run-time errors
pymetis (optional) is missing; you may get run-time errors
scikits.umfpack (optional) is missing; you may get run-time errors
running build_ext
running build_src
build_src
building library "sfepy_common" sources
building library "sfepy_terms" sources
building extension "sfepy.discrete.common.extmods._fmfield" sources
building extension "sfepy.discrete.common.extmods.mappings" sources
building extension "sfepy.discrete.common.extmods.assemble" sources
building extension "sfepy.discrete.common.extmods.cmesh" sources
building extension "sfepy.discrete.common.extmods.crefcoors" sources
building extension "sfepy.discrete.common.extmods._geommech" sources
building extension "sfepy.discrete.fem.extmods.bases" sources
building extension "sfepy.discrete.fem.extmods.lobatto_bases" sources
building extension "sfepy.discrete.iga.extmods.igac" sources
building extension "sfepy.linalg.extmods.crcm" sources
building extension "sfepy.terms.extmods.terms" sources
building data_files sources
build_src: building npy-pkg config files
No module named msvccompiler in numpy.distutils; trying from distutils
customize MSVCCompiler
customize MSVCCompiler using build_clib
building 'sfepy_common' library
compiling C sources
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox
/MD /W3 /GS- /DNDEBUG -D__SDIR__='"sfepy\discrete\common\extmods"' -DSFEPY_PLATF
ORM=1 -Isfepy\discrete\common\extmods -IC:\Python27\include -IC:\Python27\lib\si
te-packages\numpy\core\include /Tcsfepy\discrete\common\extmods\fmfield.c /Fobui
ld\temp.win32-2.7\sfepy\discrete\common\extmods\fmfield.obj -g -O2
Found executable C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.ex
e
cl : Ligne de commande warning D9002 : option '-g' inconnue ignorée
fmfield.c
sfepy\discrete\common\extmods\fmfield.c(21) : warning C4129: 'd' : caractère de
séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(21) : warning C4129: 'c' : caractère de
séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(21) : warning C4129: 'e' : caractère de
séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(21) : error C2015: trop de caractères da
ns la constante
sfepy\discrete\common\extmods\fmfield.c(39) : warning C4129: 'd' : caractère de
séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(39) : warning C4129: 'c' : caractère de
séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(39) : warning C4129: 'e' : caractère de
séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(39) : error C2015: trop de caractères da
ns la constante
sfepy\discrete\common\extmods\fmfield.c(82) : warning C4129: 'd' : caractère de
séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(82) : warning C4129: 'c' : caractère de
séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(82) : warning C4129: 'e' : caractère de
séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(82) : error C2015: trop de caractères da
ns la constante
sfepy\discrete\common\extmods\fmfield.c(101) : warning C4129: 'd' : caractère de
 séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(101) : warning C4129: 'c' : caractère de
 séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(101) : warning C4129: 'e' : caractère de
 séquence d'échappement non reconnu
sfepy\discrete\common\extmods\fmfield.c(101) : error C2015: trop de caractères d
ans la constante
error: Command "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe
 /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -D__SDIR__='"sfepy\discrete\common\extmods
"' -DSFEPY_PLATFORM=1 -Isfepy\discrete\common\extmods -IC:\Python27\include -IC:
\Python27\lib\site-packages\numpy\core\include /Tcsfepy\discrete\common\extmods\
fmfield.c /Fobuild\temp.win32-2.7\sfepy\discrete\common\extmods\fmfield.obj -g -
O2" failed with exit status 2

**Comment by rc** [comment]
This should be also fixed by #325 - could you give it a try?
