### ISSUE TITLE
Numpy error during compilation

### ISSUE THREAD

**Issue by moravveji** [sfepy/sfepy#326]
Hi.
I'm pretty new to sfepy, and would like to have it installed and running on my MacBook Pro.
During the installation of Mayavi, I had to downgrade numpy from v. 1.10, to 1.9.3 
I have to mention that I use anaconda Python distro, and also could not manage to install all (optional) dependencies.
After hitting "python setup.py install" in sfepy directory, I received the following error message:

`(mycond)cannon-2:sfepy ehsan$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    package_check('tables', INFO.PYTABLES_MIN_VERSION)
  File "/Users/ehsan/my/python/external/sfepy/build_helpers.py", line 303, in package_check
    __import__(pkg_name)
  File "/Users/ehsan/envs/mycond/lib/python2.7/site-packages/tables/__init__.py", line 82, in <module>
    from tables.utilsextension import (
  File "__init__.pxd", line 155, in init tables.utilsextension (tables/utilsextension.c:17736)
ValueError: numpy.dtype has the wrong size, try recompiling
`

I would be grateful to receive your assistance resolving this issue.

Kind regards,
Ehsan.

**Comment by rc** [comment]
Hi, did you install mayavi? If yes, try updating numpy - the mayavi installation in recent anaconda causes a numpy downgrade to a version that is not compatible with the pytables version installed.

**Comment by moravveji** [comment]
Hi, and thanks for your swift reply.
I installed mayavi through: `conda install mayavi` in the command line. As you noted, mayavi, then, required a numpy downgrade, which was unavoidable.
Are there better ways to proceed?

**Comment by moravveji** [comment]
OK. an update: I just updated my numpy, and succeeded to install sfepy.
Time to explore ...

**Comment by rc** [comment]
Good, let us close this. I do not know a better way, try asking anaconda maintainers. See also #292.
