### ISSUE TITLE
Problem installing sfepy at sagemath Cloud.

### ISSUE THREAD

**Issue by sakhan007** [sfepy/sfepy#327]
I hope that this is the right place to ask this..
When I approach SMC support to request installation of sfepy in one of my project, this is what they said:

    About sfepy, I'm not sure if that will work. One dependency is Mayavi, which requires a graphic user interface. SMC is a pure web-application and that won't really work.

Any help to overcome the issue?

**Comment by rc** [comment]
Mayavi is an optional run-time dependency, that is used only for post-processing/visualisation of results, so installation without it should be possible, as well as running simulations. Note that mayavi can also run without GUI (offscreen option) to produce results images directly.

**Comment by rc** [comment]
@sakhan007 , any updates?

**Comment by rc** [comment]
OK, let us close this.
