### ISSUE TITLE
sfepy: build using Python(x,y) error on windows

### ISSUE THREAD

**Issue by xiaoyang90** [sfepy/sfepy#335]
...................................................
building data_files sources
build_src: building npy-pkg config files
customize MSVCCompiler
customize MSVCCompiler using build_clib
'gcc' is not an internal or external command, nor a program that can be run
Batch file or batch file。
Building msvcr library: "C:\Python27\libs\libmsvcr90.a" (from C:\Windows\winsxs\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_e163563597edeada\msvcr90.dll)
error: [Error 2]
@LAPTOP-C7LARFAU[C:sfepy-2016.2]|6>

Python(x,y) budle the mingw, why it report can't find gcc?

**Comment by rc** [comment]
No idea. Can you try using anaconda instead?

**Comment by DengkeDu** [comment]
The new version Python(x,y) drop the mingw, using fficial MS VS2008 installer.
[Python(x,y)](http://python-xy.github.io/downloads.html)

**Comment by rc** [comment]
Thanks for the info. Any success with the issue?

**Comment by xiaoyang90** [comment]
I use the version 2.7.6.1 that contain the mingw 4.8.1, above find the gcc, but throw errors:
`
g++ -shared build\temp.win32-2.7\Release\sfepy\discrete\common\extmods\_fmfield.o -LC:\Python27\libs -LC:\Python27\PCbuild -Lbuild\temp.win32-2.7 -lsfepy_common -lpython27 -lmsvcr90 -o sfepy\discrete\common\extmods\_fmfield.pyd
Found executable C:\MinGW32-xy\bin\g++.exe
Warning: .drectve `/manifestdependency:"type='win32' name='Microsoft.VC90.CRT' version='9.0.21022.8' processorArchitecture='x86' publicKeyToken='1fc8b3b9a1e18e3b'" /DEFAULTLIB:"python27.lib" /DEFAULTLIB:"MSVCRT" /DEFAULTLIB:"OLDNAMES" ' unrecognized
Warning: .drectve `/manifestdependency:"type='win32' name='Microsoft.VC90.CRT' version='9.0.21022.8' processorArchitecture='x86' publicKeyToken='1fc8b3b9a1e18e3b'" /DEFAULTLIB:"python27.lib" /DEFAULTLIB:"MSVCRT" /DEFAULTLIB:"OLDNAMES" ' unrecognized
C:\Python27\libs/libpython27.a(dmmes00253.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'
C:\Python27\libs/libpython27.a(dmmes00245.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'
C:\Python27\libs/libpython27.a(dmmes01033.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'
C:\Python27\libs/libpython27.a(dmmes01035.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'
C:\Python27\libs/libpython27.a(dmmes01026.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'
C:\Python27\libs/libpython27.a(dmmes00976.o):(.idata$7+0x0): more undefined references to `_head_C__build27_cpython_PCBuild_libpython27_a' follow
collect2.exe: error: ld returned 1 exit status
error: Command "g++ -shared build\temp.win32-2.7\Release\sfepy\discrete\common\extmods\_fmfield.o -LC:\Python27\libs -LC:\Python27\PCbuild -Lbuild\temp.win32-2.7 -lsfepy_common -lpython27 -lmsvcr90 -o sfepy\discrete\common\extmods\_fmfield.pyd" failed with exit status 1

`

**Comment by xiaoyang90** [comment]
In this pages [sftpy installation guide](http://sfepy.org/doc-devel/installation.html#platform-specific-notes), who can tell me the version of Python(x,y) and sfepy for the windows. Thanks!

**Comment by rc** [comment]
@xiaoyang90 that documentation section was user-contributed and may be obsolete now. The platform-specific notes are usually contributed by people using sfepy on each of the platforms. You may want to try asking on the sfepy mailing list. But currently people seem to prefer anaconda, so be aware that you may not get a response.

As for the listing above, it looks like a problem with linking the python libs.

**Comment by DengkeDu** [comment]
Maybe you can turn to linux to slove it and start you main work quickly.

**Comment by xiaoyang90** [comment]
Thanks, linux is fine for sfepy!

**Comment by rc** [comment]
OK, let us know in case you succeed also with a windows installation - the info could be added to the docs.
