### ISSUE TITLE
AssertionError: File too large, got 540094507 triangles which exceeds the maximum of 100000000

### ISSUE THREAD

**Issue by xiaoyang90** [sfepy/sfepy#338]
When I run the tutorial step by step:　[mesh = Mesh.from_file('meshes/2d/rectangle_tri.mesh')](http://sfepy.org/doc-devel/tutorial.html#interactive-example-linear-elasticity)

It throw the error:
`AssertionError: File too large, got 540094507 triangles which exceeds the maximum of 100000000`

How can I import the mesh file? Thanks!

**Comment by rc** [comment]
This message is not printed by sfepy - it might be your meshing software? Also, the mesh in 'meshes/2d/rectangle_tri.mesh' is very small - maybe you replaced it by accident with a very large file?

**Comment by rc** [comment]
No further information provided -> let us close this.
