### ISSUE TITLE
"Latest snapshot" broken link

### ISSUE THREAD

**Issue by nicoguaro** [sfepy/sfepy#344]
In the [website](http://sfepy.org/doc-devel/downloads.html) appears the following link

    http://github.com/sfepy/sfepy/archives/master

But it leads to nowhere.

**Comment by rc** [comment]
Thanks for the report! Github have disabled that page recently. We can likely replace it by ``https://github.com/sfepy/sfepy/archive/master.zip``.

**Comment by rc** [comment]
It is fixed.
