### ISSUE TITLE
Question about how to implement Loubignac iterations

### ISSUE THREAD

**Issue by timmyL17** [sfepy/sfepy#357]
Hi,

I'd like to implement Loubignac iterations, described here
http://arc.aiaa.org/doi/pdf/10.2514/3.7464

It's simple conceptually, but I'm not sure how to do it in sfepy. It basically requires:
1. Timestepping the equations, and having access to the displacement and stress from the previous time step.
2. Averaging the stress at the nodes, then multiplying by the shape function matrix, then the strain displacement matrix.

Could anyone provide guidance on how to do this? Are there any examples I could build off of?

Thanks!

**Comment by rc** [comment]
@timmyL17 1. is no problem  (e.g. example [1] might be relevant) as well as averaging the stress at the nodes [2]. The rest of 2. is not readily available. One possibility how to implement that would be adding a new term. I could help you with that - it would be nice to have the stress postprocessing/smoothing in sfepy.

r.

[1] http://sfepy.org/doc-devel/examples/linear_elasticity/material_nonlinearity.html
[2] http://sfepy.org/doc-devel/primer.html#generating-output-at-element-nodes

**Comment by timmyL17** [comment]
@rc Thanks for the helpful response. I'd be happy to look into adding a new term, if you could provide guidance.

**Comment by rc** [comment]
@timmyL17 OK. Because adding new terms is not as easy as it should be for people not familiar with sfepy internals, I will add the term (or its initial version) myself in a branch and ping you back.

**Comment by rc** [comment]
@timmyL17 I have just realized, that the term is already there - [1] could be used to evaluate the right-hand side of (7) in the article. So if you sketch-up the code for the Loubignac iterations, I could fill-in the actual term evaluations.

[1] http://sfepy.org/doc-devel/src/sfepy/terms/terms_elastic.html#sfepy.terms.terms_elastic.LinearPrestressTerm

**Comment by timmyL17** [comment]
@rc Great! I'll sketch up code for the rest of it.

**Comment by timmyL17** [comment]
Hi @rc,

I think I have most of the code for the iterations in place. I've put what I have so far [here](https://www.dropbox.com/s/46xu4ay9ex4ishd/loubignac.py?dl=0). A post process hook stores the stress field, as well as the displacement field. In the post process hook, I add the previous displacement to the current one. I'm using a parameter field for the previous stress term. Just a couple of questions if you have time:

1.  For the first iteration, is the call to zeros_like on line 92 the correct way to do it (return zeros for the previous stress for the previous iteration)?

2. Is line 144 the correct way to get stress at the nodes?

3. When setting up the custom quadrature points for getting stress at the nodes, what is the parameter to geometry_data (line 9)? I'm assuming that means 2 dimensional, 3 nodes? So if would be 2_4 if I wanted to use quads? Is there anyway to do this automatically from the mesh that is loaded?

Thanks again for the help!

**Comment by rc** [comment]
@timmyL17 Could you provide also the mesh, so that I could run it?

**Comment by timmyL17** [comment]
@rc, Yes sorry I forgot. The mesh is here:

https://www.dropbox.com/s/nouja20csmz4iq3/beam.mesh?dl=0

Also, I updated the loubignac.py file to fix some bugs, so it actually runs now. The same link two posts above will get the new version now. One problem I'm not sure how to fix is the shape of the nodal stress variable. When evaluating it using vertices as quadrature points, it returns an array with shape (#elements, #dof per element, #components, 1). But when using this in equations,  I think it should be of shape (#vertices * #components,). Is there an easy way to do this reordering/deduplication?

Thanks.

**Comment by rc** [comment]
[loubignac_new.zip](https://github.com/sfepy/sfepy/files/690134/loubignac_new.zip)

@timmyL17, I think I have something, see the attachment. It runs, but you should verify that it converges. I rearranged the file a bit, and used eq. (6) from the article, so that we do not need to worry about technical details as whether we work with full displacements or just an increment.

I have also stumbled on several bugs/misfeatures in sfepy, that I will fix soon.

To make it more efficient, an "interactive" script might be more suitable, but I guess this is a workable start.

Does it work for you?

**Comment by timmyL17** [comment]
Thanks @rc, this seems to be working. One question: is there a good way to stop the iterations from the post_process hook? That seems like a logical place to compute the change from the previous displacements to the current ones. The paper suggests stopping iterations when that change gets small.

**Comment by rc** [comment]
@timmyL17 There is no recommended way, a post_process_hook function is meant to add derived quantities to the solution output. But you could hack it by checking the displacements, and when the difference is small enough, do one more iteration (to save the last result) and then just call `sys.exit()` in the  post_process_hook. Not nice, but should work.

A much better way would be to use a script for your problem, where you would control the loop explicitely. See, for example, [1], where an interactive use of a time stepper is shown. Note also, that for this kind of iteration you do not need a time stepper, a while loop would do as well. So maybe just follow [2] and add there the loop.

[1] http://sfepy.org/doc-devel/examples/diffusion/time_poisson_interactive.html
[2] http://sfepy.org/doc-devel/examples/linear_elasticity/linear_elastic_interactive.html

**Comment by timmyL17** [comment]
@rc, One more question. I might just be being dense, but I don't see how the linear prestress term corresponds to eq. 6 from the paper. The linear prestress term has strains, which are B * displacement, contracted with stress. But the term in eq. 6 only has the B matrix times the stress, no displacements. Am I missing something?

**Comment by rc** [comment]
@timmyL17 No, it is not B * displacement - that would be e_ij(u). The term has e_ij(v), and v is a test function. So, in fact, it is just B *.

**Comment by rc** [comment]
@timmyL17 Does the above answer your question, or, can I close this issue? :)

**Comment by timmyL17** [comment]
Yes, sorry, I forgot to close it.

**Comment by rc** [comment]
No problem, thanks!
