### ISSUE TITLE
docs: link terms with the example(s)

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#374]
It would be nice to have a list for each term of links to examples, where the term is used.

**Comment by rc** [comment]
On 10. 03. 21 15:47, Antony wrote:
> Hey,
> If this issue is still active, It would be a pleasure to help.
> 

Yes, that would be welcome! FWIW: There are a script that lists terms use in 
examples (script/show_terms_use.py) and a script that generates the term table 
document (script/gen_term_table.py).

**Comment by DuckNrOne** [comment]
Great! And the task consists of adding a new column to each [term table](http://sfepy.org/doc-devel/terms_overview.html#table-of-basic-terms) and each cell includes links to examples, that uses the term in the same row? Sounds like a job for me :D

**Comment by rc** [comment]
Yes, something like that. I am not sure about the PDF version of the docs, let's see how it goes.  :)

**Comment by DuckNrOne** [comment]
The PDF shouldn't be a problem, when I edit `gen_term_table` and the generation process of the PDF accesses this module in any way. Does it?

**Comment by rc** [comment]
Technically no problem, it is automatic (sphinx does all the work), but the PDF pages are not so wide/flexible as the html docs pages. The term table in the [manual](http://sfepy.org/doc/_downloads/63e3f3e0a0635ddc67af3c6e4d0f6b5f/sfepy_manual.pdf) is already rather cluttered, so I thought that maybe the links to the examples can be only in the html version of the docs.

**Comment by DuckNrOne** [comment]
I'll look into the module the next days if it possible to choose the columns of the generated table eg in the method call.

**Comment by rc** [comment]
OK, anyway, my concern is rather premature - maybe it will look fine in the pdf too - ignore it for now :)

**Comment by antonykamp** [comment]
I have a small question: Compiling the docs returns a warning (more an error) because sphinx cannot find [`examples/index`](https://github.com/sfepy/sfepy/blame/master/doc/examples.rst#L17). It could be possible that maybe autodoc doesn't work correctly in the toctree. Do you know why?
 More importantly: Because I would refer to the examples the same way, I don't know which links I should use given the name of an example. At the moment, I use [`examples/[example-name]`](https://github.com/antonykamp/sfepy/blob/e83e5ab12dcfdfa447e44cbd8b26a53061792fc5/script/gen_term_table.py#L133) :)

**Comment by rc** [comment]
Ah, you need to run ``python3 script/gen_gallery.py -n`` to generate doc/examples/. (``-n`` does not generate the images to speed things up.) Does it help?

Some info on this can be found [here](http://sfepy.org/doc/release_tasks.html), but do not hesitate to ask - the docs are scarse in this respect.

For the references , you can IMO use the labels defined on the first lines of the examples' rst files - it is essentially ``<example subdir>-<example name>``.

**Comment by antonykamp** [comment]
> Does it help?

That helped a lot (especially the *Things to check before a release*)! Now, sphinx can't find *only* five labels or so. I'll look into it in the next few days ;)
And the naming isn't perfect at the moment, eg:
![image](https://user-images.githubusercontent.com/45163503/111206809-27f1a280-85c9-11eb-8f55-d0add63c694c.png)

**Comment by rc** [comment]
Thanks for the update. The naming is OK, I thought originally just about reference-like links ([1], [2],...), but having some information on the kind of example in the link is better. :)
