### ISSUE TITLE
Term Overview

### ISSUE THREAD

**Issue by lbertolotti** [sfepy/sfepy#399]
SfePy documentation, April 20, 2017

some tables are almost unreadable:
![table](https://cloud.githubusercontent.com/assets/19675068/26029141/4e9732a4-3804-11e7-9b9e-d03dcb39cbd0.png)

**Comment by rc** [comment]
Thanks for reporting that. It looks like the table of basic terms is OK, and the other tables are shifted to the right. I do not see reason for that in the `doc/term_table.rst` file. @vlukes any ideas?

**Comment by lbertolotti** [comment]
SfePy, documentation, June 14, 2017
Problem persists

**Comment by rc** [comment]
We do not know yet, what causes the problems. All the tables are defined in the same way...

**Comment by rc** [comment]
Fixed by upgrading sphinx and forcing longtable for all term tables.
