### ISSUE TITLE
Linear Elasticity

### ISSUE THREAD

**Issue by lbertolotti** [sfepy/sfepy#401]
Sfepy Documentation, May 19, 2017
3.4
```
from sfepy.terms import Term
t1=Term.new('dw_lin_elastic_iso(m.lam, m.mu, v, u)', integral, omega, m=m, v=v, u=u)
t2=Term.new('dw_volume_lvf(f.val, v))', integral, omega, f=f, v=v)

eq=Equation('balance', t1+t2)
Traceback (most recent call last):

  File "<ipython-input-6-1dc9ac351995>", line 1, in <module>
    eq=Equation('balance', t1+t2)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 785, in __init__
    self.terms.setup()

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 288, in setup
    term.setup()

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 423, in setup
    self.setup_formal_args()

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 438, in setup_formal_args
    self.arg_desc = parser.parseString(self.arg_str)

  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1632, in parseString
    raise exc

ParseException: Expected end of text
```
What does "Expected end of text" means?
```

Equation('balance', t1)
Out[8]: Equation:balance

Equation
Out[9]: sfepy.discrete.equations.Equation

Equation('balance', t2)
Traceback (most recent call last):

  File "<ipython-input-10-c0442ea954fa>", line 1, in <module>
    Equation('balance', t2)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 785, in __init__
    self.terms.setup()

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 288, in setup
    term.setup()

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 423, in setup
    self.setup_formal_args()

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 438, in setup_formal_args
    self.arg_desc = parser.parseString(self.arg_str)

  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1632, in parseString
    raise exc

ParseException: Expected end of text
```

Also:

```
from sfepy.discrete.conditions import Conditions, EssentialBC

fix_u=EssentialBC('fix_u', gamma1, {'u.all' : 0.0})

def shift_u_fun(ts,coors,bc=None, problem=None, shift=0.0):
    val=shift*coors[:,1]**2
    return val

shift_u_fun
Out[14]: <function __main__.shift_u_fun>

bc_fun=Function('shift_u_fun', shift_u_fun, extra_args={'shift' : 0.01})
Traceback (most recent call last):

  File "<ipython-input-15-886bb7edabe7>", line 1, in <module>
    bc_fun=Function('shift_u_fun', shift_u_fun, extra_args={'shift' : 0.01})

NameError: name 'Function' is not defined
```
And:
```
from sfepy.solvers.nls import Netwon
Traceback (most recent call last):

  File "<ipython-input-25-50b88f8bac7c>", line 1, in <module>
    from sfepy.solvers.nls import Netwon

ImportError: cannot import name Netwon

```

**Comment by rc** [comment]
On 05/25/2017 04:38 AM, lbertolotti wrote:
> Sfepy Documentation, May 19, 2017
> 3.4
> ```
> from sfepy.terms import Term
> t1=Term.new('dw_lin_elastic_iso(m.lam, m.mu, v, u)', integral, omega, m=m, v=v, u=u)
> t2=Term.new('dw_volume_lvf(f.val, v))', integral, omega, f=f, v=v)

t2 has a superfluous ')' in its definition, try:

t2 = Term.new('dw_volume_lvf(f.val, v))', integral, omega, f=f, v=v)

> eq=Equation('balance', t1+t2)
> Traceback (most recent call last):
> 
>    File "<ipython-input-6-1dc9ac351995>", line 1, in <module>
>      eq=Equation('balance', t1+t2)
> 
>    File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 785, in __init__
>      self.terms.setup()
> 
>    File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 288, in setup
>      term.setup()
> 
>    File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 423, in setup
>      self.setup_formal_args()
> 
>    File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 438, in setup_formal_args
>      self.arg_desc = parser.parseString(self.arg_str)
> 
>    File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1632, in parseString
>      raise exc
> 
> ParseException: Expected end of text
> ```
> What does "Expected end of text" means?
> ```

It means, that the term definition (the string) cannot be parsed correctly.

> Equation('balance', t1)
> Out[8]: Equation:balance
> 
> Equation
> Out[9]: sfepy.discrete.equations.Equation
> 
> Equation('balance', t2)
> Traceback (most recent call last):
> 
>    File "<ipython-input-10-c0442ea954fa>", line 1, in <module>
>      Equation('balance', t2)
> 
>    File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 785, in __init__
>      self.terms.setup()
> 
>    File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 288, in setup
>      term.setup()
> 
>    File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 423, in setup
>      self.setup_formal_args()
> 
>    File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 438, in setup_formal_args
>      self.arg_desc = parser.parseString(self.arg_str)
> 
>    File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1632, in parseString
>      raise exc
> 
> ParseException: Expected end of text
> ```
> 
> Also:
> 
> ```
> from sfepy.discrete.conditions import Conditions, EssentialBC
> 
> fix_u=EssentialBC('fix_u', gamma1, {'u.all' : 0.0})
> 
> def shift_u_fun(ts,coors,bc=None, problem=None, shift=0.0):
>      val=shift*coors[:,1]**2
>      return val
> 
> shift_u_fun
> Out[14]: <function __main__.shift_u_fun>
> 
> bc_fun=Function('shift_u_fun', shift_u_fun, extra_args={'shift' : 0.01})
> Traceback (most recent call last):
> 
>    File "<ipython-input-15-886bb7edabe7>", line 1, in <module>
>      bc_fun=Function('shift_u_fun', shift_u_fun, extra_args={'shift' : 0.01})
> 
> NameError: name 'Function' is not defined
> ```

You should use:

from sfepy.discrete import Function

> And:
> ```
> from sfepy.solvers.nls import Netwon
> Traceback (most recent call last):
> 
>    File "<ipython-input-25-50b88f8bac7c>", line 1, in <module>
>      from sfepy.solvers.nls import Netwon
> 
> ImportError: cannot import name Netwon
> 
> ```
> 

Netwon -> Newton

Try running/checking the 
`examples/linear_elasticity/linear_elastic_interactive.py` - the commands are 
taken from there, right?

r.

**Comment by lbertolotti** [comment]
The commands are taken from Section 3.4
Also:
**3.4.1 Complete Example as a Script
The source code: linear_elasticity.py**

Which doesn't exist.

**Comment by rc** [comment]
I see - the tutorial text assumes running it with `ipython --profile=sfepy` which does not work with recent ipython (see #379), so it assumes some imports that are not explicitly stated in the text. You can download the script from the online version of the docs (http://sfepy.org/doc-devel/tutorial.html#complete-example-as-a-script) - it just points to the `examples/linear_elasticity/linear_elastic_interactive.py` file in the sfepy sources. In case you installed sfepy using anaconda or some other package manager, and do not use it in-place, the file can be found in `<the-dir-with-python-packages/sfepy/examples/linear_elasticity/linear_elastic_interactive.py>`. The name of the file will be fixed in the tutorial soon.

**Comment by lbertolotti** [comment]
That pretty much explains it.
![result](https://cloud.githubusercontent.com/assets/19675068/26517461/7313eee0-426f-11e7-88ed-d56fdadf031a.png)
I got this from IPython console.

**Comment by rc** [comment]
Looks OK to me!

**Comment by rc** [comment]
Fixed now in the master.
