### ISSUE TITLE
Regions

### ISSUE THREAD

**Issue by lbertolotti** [sfepy/sfepy#402]
How do I specify a circular boundary for a spherical domain?
![sphere](https://cloud.githubusercontent.com/assets/19675068/26607405/c001ce70-456c-11e7-88f1-b673e90e9893.png)
Also is this a regular face boundary?
![ring](https://cloud.githubusercontent.com/assets/19675068/26607429/d4b4d452-456c-11e7-96ce-810c8fae3440.png)

**Comment by rc** [comment]
Hi, you can get the whole surface of any domain by using `'vertices of surface'`. The most general way is the selection by a function, and/or you can also have some vertices/cells/vertex groups marked by your meshing software. The regions can be combined using set operations, see the user manual.

Also, please, prefer to use [the mailing list](https://mail.python.org/mm3/mailman3/lists/sfepy.python.org/) for these kinds of questions.

**Comment by rc** [comment]
Closing as non-issue.

**Comment by lbertolotti** [comment]
For the spherical domain:
```
In:print domain
FEDomain:domain
  _bnf:
    {StringStart Forward: ... StringEnd}
  _region_stack:
    list: []
  bmesh:
    None
  cmesh:
    CMesh: n_coor: 334, dim 3, tdim: 3, n_el 1203
  geom_els:
    dict with keys: ['3_4']
  mesh:
    Mesh:-0000000000000000001-0000000000000000001
  name:
    domain
  nurbs:
    None
  regions:
    list: [
      Region:Omega
        can:
          list: [True, True, True, True]
        can_cells:
          True
        can_edges:
          True
        can_faces:
          True
        can_vertices:
          True
        definition:
          all
        dim:
          3
        domain:
          FEDomain:domain
        entities:
          list: [array([  0,   1,   5, ..., 331, 332, 333], dtype=uint32), array([   0,    1,    2, ..., 1751, 1752, 1753], dtype=uint32), array([   0,    1,    2, ..., 2627, 2628, 2629], dtype=uint32), array([   0,    1,    2, ..., 1200, 1201, 1202], dtype=uint32)]
        is_empty:
          False
        kind:
          cell
        kind_tdim:
          3
        mirror_region:
          None
        n_v_max:
          334
        name:
          Omega
        parent:
          None
        parse_def:
          KW_All<>
        shape:
          Struct
        tdim:
          3
        true_kind:
          cell
    ]
  shape:
    Struct
  surface_groups:
    dict with keys: []
  verbose:
    False
  vertex_set_bcs:
    dict with keys: []

gamma_1 = domain.create_region('Gamma_1', 'vertices in (x==0)', 'vertex')
In: gamma_1
Out: Region:Gamma_1
```
But:
```
def get_circle(coors, domain=None):
    r = nm.sqrt(coors[:,0]**2.0 + coors[:,1]**2.0)
    return nm.where((r<70))[0]

get_circle_fun=Function('get_circle_fun', get_circle)

gamma_2 = domain.create_regions('Gamma_2', 'vertices by get_circle_fun')
sfepy:     creating regions...
Traceback (most recent call last):

  File "<ipython-input-10-680d1690fb47>", line 1, in <module>
    gamma_2 = domain.create_regions('Gamma_2', 'vertices by get_circle_fun')

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/discrete/common/domain.py", line 221, in create_regions
    graph, name_to_sort_name = get_dependency_graph(region_defs)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/discrete/common/region.py", line 28, in get_dependency_graph
    for sort_name, rdef in six.iteritems(region_defs):

  File "/usr/local/lib/python2.7/dist-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)

AttributeError: 'str' object has no attribute 'iteritems'

```
Even if:
```
In: circle_fun(domain.get_mesh_coors())
Out: array([  0,   1,   2, ..., 331, 332, 333])
```

**Comment by rc** [comment]
Try:

```
gamma_2 = domain.create_region('Gamma_2', 'vertices by get_circle_fun', functions=Functions([get_circle_fun]))
```

`domain.create_regions()` is another function that creates all the regions at once using the definitions as in a problem description file.

**Comment by lbertolotti** [comment]
```
In: gamma_2 = domain.create_region('Gamma_2', 'vertices by get_circle_fun', functions=Functions([get_circle_fun]), kind='vertex')
In: gamma_2
Out: Region:Gamma_2
ebc2=EssentialBC('ebc2', gamma_2, {'u.all' : 10.0})
```
![circular_boundary_1](https://user-images.githubusercontent.com/19675068/27160843-99525e38-514d-11e7-89be-eea4e9ae34ff.png)
create_region(self, name, select, kind='cell', parent=None, check_parents=True, functions=None, add_to_regions=True, allow_empty=False)
Region factory constructor. Append the new region to self.regions list.
There is a "functions" argument alright, but where is it specified that is an object  like:
```
In: Functions
Out: sfepy.discrete.functions.Functions

```
```
def get_circle(coors, domain=None):
    r = nm.sqrt(coors[:,0]**2.0 + coors[:,1]**2.0)
    return nm.where((r>65)&(r<75))[0]
ebc2=EssentialBC('ebc2', gamma_2, {'u.all' : 10.0})
```
![circular_boundary_2_a](https://user-images.githubusercontent.com/19675068/27160971-7ade74f4-514e-11e7-8f3a-86f7557152fb.png)
Looking at the other side we can see the same feature seen on the ring domain. Is this a result of the meshing (Salome), use of topological entities or the functions used?
![circular_boundary_2_b](https://user-images.githubusercontent.com/19675068/27160972-7ae4aad6-514e-11e7-8cc5-3c89e6ad3b85.png)
```
I fixed that by doing:
def get_circle_1(coors, domain=None):
    r = nm.sqrt(coors[:,0]**2.0 + coors[:,1]**2.0)
    return nm.where((r<51)&(r>49))[0]
    
def get_circle_2(coors, domain=None):
    r = nm.sqrt(coors[:,0]**2.0 + coors[:,1]**2.0)
    return nm.where((r<101)&(r>99))[0]
ebc_1=EssentialBC('ebc1', gamma_1, {'u.all' : 10.0})
ebc_2=EssentialBC('ebc2', gamma_2, {'u.all' : 10.0})
```
![ring](https://user-images.githubusercontent.com/19675068/27160975-7f1ef9e4-514e-11e7-8d7a-38a6c5f0e79f.png)

**Comment by rc** [comment]
You are right, that the arguments of  ``Domain.create_region()`` are not properly documented, and there is no interactive-usage example. Could you create a new issue for that?

As for missing some vertices in your examples, I would say it is a combination of:
- floating point comparisons - using ranges as you did should fix that
- the vertex positions of the sphere mesh being not completely symmetric (on the circles) - can the Salome mesher use some constraints?

Note that with a finer mesh, you would probably get more than a single strip of vertices in the circle.
