### ISSUE TITLE
Post-processing in Python 3.6 - Issue with mayavi

### ISSUE THREAD

**Issue by faraztehrani** [sfepy/sfepy#421]
I am new to SfePy. It looks like a great code with lot of potentials. So, thanks a lot for your efforts.

I just started testing some of the examples. I use Python 3.6 and imported SfePy in Anaconda. When I run the Interactive Example on linear elasticity, I get the following error:
ModuleNotFoundError: No module named 'enthought'.

This is related to mayavi, as far as I understood, and I realized that mayavi is not fully functional on Python 3.6. What is your suggestion? Should I use Python 2.7 to make the most out of SfePy?

**Comment by rc** [comment]
Thanks! You can save to VTK (which is the default) and then use any VTK-capable viewer, such Paraview, or visit. SfePy works with Python 2.7 (and still will for some years), but note that some packages such as IPython release new versions for 3.x only. So if Paraview (or other package) works well for you, it might be better to stick with 3.6.

**Comment by rc** [comment]
No more feedback, closing - feel free to reopen, or ask on the mailing list.
