### ISSUE TITLE
plot_displacements

### ISSUE THREAD

**Issue by lbertolotti** [sfepy/sfepy#440]
```
from sfepy.postprocess.domain_specific import plot_displacements
plot_displacements(source = view, position = '(x,y,z)', family='point', name="u", rel_scaling=1.0, kind='scalars', opacity=1.0)
```
```
Traceback (most recent call last):

  File "<ipython-input-57-e33f569909bd>", line 1, in <module>
    plot_displacements(source = view, position = '(x,y,z)', family='point', name="u", rel_scaling=1.0, kind='scalars', opacity=1.0)
```
This looks like a bug

**Comment by rc** [comment]
Hi,

what are you trying to achieve? The `plot_displacements()` function is not meant to be used directly - it is called by Viewer (see around https://github.com/sfepy/sfepy/blob/92049a46c91b67df17c7962f40e0bdff623c0dc0/sfepy/postprocess/viewer.py#L521 for its arguments). It is used in some examples - https://github.com/sfepy/sfepy/blob/92049a46c91b67df17c7962f40e0bdff623c0dc0/examples/linear_elasticity/shell10x_cantilever_interactive.py#L367 shows how to use it in a script, https://github.com/sfepy/sfepy/blob/92049a46c91b67df17c7962f40e0bdff623c0dc0/examples/linear_elasticity/shell10x_cantilever.py#L25 shows how to use it via ``postproc.py``.

**Comment by rc** [comment]
Closing old issues - feel free to create new if the problem persists.
