### ISSUE TITLE
update TetgenMeshIO to read vertex and cell groups

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#442]
Currently, the additional data in the .node, .ele are just thrown away.

**Comment by heczis** [comment]
Is there an example .node file? The examples at [1] only use the boundary marker, not the attribute(s).
Also, it seems to me that both formats (.node and .ele) allow for multiple attributes. Is it OK to let the attributes define possibly overlapping sets of entities?
And: [2] says that the nodal attributes
> ...are typically floating-point values of physical quantities (such as mass or conductivity) associated with the points...

Using these numbers to define vertex groups doesn't seem right to me.

[1] http://wias-berlin.de/software/tetgen/fformats.examples.html
[2] http://wias-berlin.de/software/tetgen/fformats.node.html

**Comment by rc** [comment]
@vlukes was this solved by using meshio?

**Comment by vlukes** [comment]
Not yet. I will prepare commit to meshio to fix this.

**Comment by rc** [comment]
OK, thanks!

**Comment by vlukes** [comment]
Resolved by nschloe/meshio#900.

**Comment by rc** [comment]
OK, let us close this. Thanks!
