### ISSUE TITLE
generate tables of availables solvers

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#447]
Similarly to the automatically generated tables of terms, tables of the various solvers could be generated to be included in the docs.

See `script/gen_term_table.py` and `doc/conf.py`.

**Comment by BubuLK** [comment]
Working on this issue (no duplicated work, please ;), PR will follow shortly, be patient...

**Comment by rc** [comment]
Great, thanks!

**Comment by rc** [comment]
BTW. I have just merged a branch adding new solvers - you may want to rebase...
