### ISSUE TITLE
University website link broken

### ISSUE THREAD

**Issue by furetosan** [sfepy/sfepy#450]
Hello there,

I've noted the link on the top of the sfepy.org website (http://www.zcu.cz/ntc/en/) is broken, and currently pointing to a 404 OpenCMS page. Possibly the fix would be to change it to http://www.zcu.cz/en/, which is the current University of West Bohemia English webpage.

Regards,
Fred

**Comment by rc** [comment]
Thanks for the report! It should be fixed now.

**Comment by furetosan** [comment]
Fix confirmed!

**Comment by rc** [comment]
OK, closing...
