### ISSUE TITLE
Slow varying EM field quasi electrostatic simulation

### ISSUE THREAD

**Issue by JeanRintoul** [sfepy/sfepy#453]
Are there any plans around EM simulation coming up? I'd like to do some AC modelling through a liquid medium and was wondering if there were any examples?

**Comment by rc** [comment]
None that I am aware of - vector elements (see, for example, [1]) would need to be implemented first. While it is technically possible, nobody implemented those (yet).

[1] http://www.iue.tuwien.ac.at/phd/nentchev/node33.html

**Comment by rc** [comment]
I am closing this issue, but feel free to post more to the thread or reopen.
