### ISSUE TITLE
--record {plist} leaves a stray record in the plist

### ISSUE THREAD

**Issue by yurivict** [sfepy/sfepy#455]
The plist file that is recorded by the ```--record``` command leaves this string:
```
/usr/local/lib/python2.7/site-packages/sfepy/meshes/
```
that shouldn't be in plist.

Found while trying to create the FreeBSD port. The error:
```
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%PYTHON_SITELIBDIR%%/sfepy/meshes/
===> Error: Plist issues found.
```

**Comment by rc** [comment]
What is the problem, and what can we do to fix that?

**Comment by yurivict** [comment]
> What is the problem

Stray file in plist.

> what can we do to fix that?

Remove it.

**Comment by rc** [comment]
Well, what is a plist?

**Comment by yurivict** [comment]
> Well, what is a plist?

The command
```python setup.py --record=plist.txt```

creates the file ```plist.txt``` that contains the list of installed files.
This is a standard feature of distutils.

**Comment by rc** [comment]
I see, thanks. If I try running (with distutils 2.7.12)

```
 python setup.py install --record=plist.txt --user
```

on a linux box, the generated file does not contain the .../sfepy/meshes/ directory - there are only the files .../sfepy/meshes/{filename}. Do you have an idea, why the problem happens on your platform?

**Comment by yurivict** [comment]
I don't know why this happens on FreeBSD.

**Comment by rc** [comment]
Closing old issues without solution/new discussion.
