### ISSUE TITLE
failing tests in latest build

### ISSUE THREAD

**Issue by awa5114** [sfepy/sfepy#476]
I have tried running the tests on what I think is the latest version of sfepy but got 5 failures out of 174 tests. Is this being addressed? Below is the failing test list:

 - test_homogenization_perfusion.py
 - test_input_linear_elastic_mM.py
 - test_input_navier_stokes2d_iga.py
 - test_hdf5_meshio
 - test_projection_iga_fem

Also how can we determine what revision broke these tests?

**Comment by vlukes** [comment]
Hi,

 >   * test_input_navier_stokes2d_iga.py
 >   * test_hdf5_meshio
 >   * test_projection_iga_fem

failed due to the missing igakit module and

 >   * test_homogenization_perfusion.py
 >   * test_input_linear_elastic_mM.py

probably failed because of wrong MPI configuration. Try to add

'multiprocessing': False

into 'options' in the problem description file. It should fix the issue. 
If not, run

./run_tests.py --debug tests/test_homogenization_perfusion.py

and send me the output.


Regards,
Vladimir

**Comment by awa5114** [comment]
In `perfusion_micro.py` I added `'multiprocessing':False` in the `options` and got the following error

```
(sfepy_env) D:\sfepy\sfepy>run_tests.py tests/test_homogenization_perfusion.py
Traceback (most recent call last):
  File "D:\sfepy\sfepy\run_tests.py", line 32, in <module>
    from sfepy.base.conf import ProblemConf, get_standard_keywords
  File "D:\sfepy\sfepy\sfepy\base\conf.py", line 14, in <module>
    from sfepy.base.base import (Struct, IndexedStruct, dict_to_struct,
  File "D:\sfepy\sfepy\sfepy\base\base.py", line 11, in <module>
    import scipy.sparse as sp
ImportError: No module named scipy.sparse
```

I'm also a bit confused that there are missing modules. I went through the following steps to run a development version of sfepy:

- create new `sfepy_env` environment
- install sfepy with `conda install -c conda-forge sfepy` to get necessary dependencies
- remove sfepy with `conda remove sfepy`
- fork & clone a copy of the repo to folder of my choosing
- run an in-place build `python setup.py build_ext --inplace`
- run tests through `sfepy_env`

I would have thought dependencies such as  your `igakit` module and `scipy` would have been taken care of in step 2 above. Why are the tests still complaining about them?

**Comment by vlukes** [comment]
The `igakit` module is optional. If you don't need the isogeometric 
analysis, just ignore the failures related to this.

 > ImportError: No module named scipy.sparse

This is really strange, because SfePy can not work without 
`scipy.sparse` at all. I guess a problem in the homogenization 
engine/script, but no important changes have been made there for a long 
time. Is the output of

	run_tests.py tests/test_input_linear_elastic_mM.py --debug

the same?

Regards,
Vladimir

**Comment by rc** [comment]
A few notes complementing what @vlukes wrote:

1. Do `import scipy` or `import scipy.sparse as sp` work in python/ipython shell?

2. Rerun `python setup.py build_ext --inplace` in the sfepy directory and write us the versions of dependencies it prints.

3. Maybe conda removes a package but also its dependencies, that are not needed by another package? Could you again `conda install sfepy` to see if it installs scipy?

Anyway, it is strange, without scipy, IMO the number of failed tests would be much higher.

**Comment by awa5114** [comment]
@Vladimir : yes the output of `run_tests.py tests/test_input_linear_elastic_mM.py --debug` is identical
@rc 

1. Yes both those commands work in python shell
2. Rerunning the in-place build shows the following output:
```
(sfepy_env) D:\sfepy\sfepy>python setup.py build_ext --inplace
mayavi (optional) is missing; you may get run-time errors
igakit (optional) is missing; you may get run-time errors
petsc4py (optional) is missing; you may get run-time errors
pymetis (optional) is missing; you may get run-time errors
scikits.umfpack (optional) is missing; you may get run-time errors
pysparse (optional) is missing; you may get run-time errors
running build_ext
running build_src
build_src
building library "sfepy_common" sources
building library "sfepy_terms" sources
building extension "sfepy.discrete.common.extmods._fmfield" sources
building extension "sfepy.discrete.common.extmods.mappings" sources
building extension "sfepy.discrete.common.extmods.assemble" sources
building extension "sfepy.discrete.common.extmods.cmesh" sources
building extension "sfepy.discrete.common.extmods.crefcoors" sources
building extension "sfepy.discrete.common.extmods._geommech" sources
building extension "sfepy.discrete.fem.extmods.bases" sources
building extension "sfepy.discrete.fem.extmods.lobatto_bases" sources
building extension "sfepy.discrete.iga.extmods.igac" sources
building extension "sfepy.mechanics.extmods.ccontres" sources
building extension "sfepy.terms.extmods.terms" sources
building data_files sources
build_src: building npy-pkg config files
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from
distutils
customize MSVCCompiler
customize MSVCCompiler using build_clib
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from
distutils
customize MSVCCompiler
customize MSVCCompiler using build_ext
extending extension 'sfepy.discrete.common.extmods._fmfield' defined_macros with
 [('SFEPY_PLATFORM', 1), ('inline', '__inline')]
extending extension 'sfepy.discrete.common.extmods.mappings' defined_macros with
 [('SFEPY_PLATFORM', 1), ('inline', '__inline')]
extending extension 'sfepy.discrete.common.extmods.crefcoors' defined_macros wit
h [('SFEPY_PLATFORM', 1), ('inline', '__inline')]
extending extension 'sfepy.discrete.common.extmods._geommech' defined_macros wit
h [('SFEPY_PLATFORM', 1), ('inline', '__inline')]
extending extension 'sfepy.discrete.fem.extmods.bases' defined_macros with [('SF
EPY_PLATFORM', 1), ('inline', '__inline')]
extending extension 'sfepy.discrete.fem.extmods.lobatto_bases' defined_macros wi
th [('SFEPY_PLATFORM', 1), ('inline', '__inline')]
extending extension 'sfepy.terms.extmods.terms' defined_macros with [('__SDIR__'
, '\\"sfepy\\\\terms\\\\extmods\\"'), ('SFEPY_PLATFORM', 1), ('inline', '__inlin
e')]

Required and optional packages found:

cython is available in version 0.29
numpy is available in version 1.15.3
scipy is available in version 1.1.0
matplotlib is available in version 2.2.2
pyparsing is available in version 2.2.2
tables is available in version 3.4.4
mayavi (optional) is missing; you may get run-time errors
sympy (optional) is available in version 1.3
igakit (optional) is missing; you may get run-time errors
petsc4py (optional) is missing; you may get run-time errors
mpi4py (optional) is available in version 2.0.0
pymetis (optional) is missing; you may get run-time errors
scikits.umfpack (optional) is missing; you may get run-time errors
pysparse (optional) is missing; you may get run-time errors
```
3. `conda install sfepy` does not change the above behavior.

**Comment by rc** [comment]
All the above seems OK. Try checking your PYTHONPATH, or sys.path and verify, that when running from the sfepy directory the correct scipy gets imported. Otherwise I have no more ideas what to try. The other tests do work, right?

**Comment by awa5114** [comment]
It appears that `base.py` is located in the forked directory of sfepy (D: drive) while `scipy` imports without complaint from the conda environment (C: drive). Also when I try to run the primer using:

`./simple.py its2D_1.py`

I get the same error from `base.py`. I wonder if the fact that I removed sfepy from the original conda environment and forked+cloned to another directory means that it somehow cannot find `scipy`? However I know scipy is there since i can import it from the conda environment in the Anaconda prompt.

**Comment by rc** [comment]
Do you have other scipy installation outside anaconda? Can you import `scipy.sparse` specifically from the conda environment? What happens if you comment out the line 11 in base.py and rerun the tests?

**Comment by rc** [comment]
Things should be fixed now, so closing.
