### ISSUE TITLE
Making MUMPS the default linear solver

### ISSUE THREAD

**Issue by vlukes** [sfepy/sfepy#478]
Pros:
- faster than UMFPACK
- less memory demanding
- different solvers for symmetric and unsymmetric matrices
- parallel factorization, not fully utilized yet
- a build-in Schur complement solver
- conda package

Cons:
- CeCILL-C license (?)
- CSR matrix needs to be converted to COO

The following issues are to be discussed:
- installation: easy installation on Windows and OS X? -> probably YES, because of conda package 
- required dependency?  -> YES
- updating the documentation
- MUMPS license

![umfpack_vs_mumps](https://user-images.githubusercontent.com/1375229/47706595-ecd5bb00-dc29-11e8-84d6-6630a8bc42ea.png)

**Comment by rc** [comment]
Thanks for creating this issue, adding MUMPS and exploring its performance!

I am quite reluctant to make MUMPS a hard dependence - after all, it would be required only to run the examples and related tests, and no other external solver is a required dependency (besides the ones in scipy). Also the license does not seem to be BSD-compatible - I would like to keep sfepy not requiring non-BSD code.

What about adding a "fallback solver" facility, that would just use `ls.scipy_direct` if the specified solver is not available? Other fallback solver could be specified as well, but that should be optional. In this way, all the examples (where appropriate) could be updated to use MUMPS, if available. We can "strongly recommend" installing it, as we do with UMFPACK now.

**Comment by rc** [comment]
OK, so feel free to proceed :)

It would be nice to have a memory time profile using https://github.com/pythonprofilers/memory_profiler (check "Time-based memory usage") for UMFPACK and MUMPS for various problem sizes. Maybe the CSR-COO conversion will be found negligible. Later, this could be a good thing to add as a benchmark, see #477.

**Comment by vlukes** [comment]
See the graph showing the memory usage obtained by a memory profiler.

![umfpack_vs_mumps_mem](https://user-images.githubusercontent.com/1375229/47804119-4c1ff200-dd34-11e8-8c7d-7564eccee687.png)

**Comment by rc** [comment]
Looks good! Later you can try various problem sizes, but this is a good motivation to switch to MUMPS.

**Comment by rc** [comment]
@vlukes can this be closed w.r.t merging of #482? Or are additional updates needed?

**Comment by vlukes** [comment]
Yes, #478 can be closed, #482 solves this issue.

**Comment by rc** [comment]
OK, closing...
