### ISSUE TITLE
sfepy fails to build from source in Debian Unstable

### ISSUE THREAD

**Issue by kkremitzki** [sfepy/sfepy#496]
This issue is covered in more detail here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917675

As a result of this bug, sfepy has been removed from Debian Testing, which would prevent it from being included in the upcoming Debian 10 release.

An abbreviated error message is:
```
sfepy/discrete/common/extmods/common.h:109:59: error: expected expression before ')' token
```

**Comment by rc** [comment]
Thanks for the report!

It looks like the problem is caused by the __SDIR__ preprocessor variable, that should define the directory where a source file resides. I wonder what it expands to in the failed build.

**Comment by kkremitzki** [comment]
All I see in the build log is
`
error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__SDIR__=\"sfepy/discrete/common/extmods\" -DSFEPY_PLATFORM=0 -Dinline=inline -Isfepy/discrete/common/extmods -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c sfepy/discrete/common/extmods/mesh.c -o build/temp.linux-amd64-2.7/sfepy/discrete/common/extmods/mesh.o -MMD -MF build/temp.linux-amd64-2.7/sfepy/discrete/common/extmods/mesh.o.d -g -O2" failed with exit status 1
`

separated for visibility, `-D__SDIR__=\"sfepy/discrete/common/extmods\"`.

**Comment by rc** [comment]
That looks pretty normal. But on my machine all the options are printed within `''`, as in:
```
compiling C sources
C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC

compile options: '-D__SDIR__=\"sfepy/discrete/common/extmods\" -DSFEPY_PLATFORM=0 -Dinline=inline -DDEBUG_FMF -DSFEPY_PLATFORM=0 -Dinline=inline -Isfepy/discrete/common/extmods -I/home/user/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c'
```
The escaped quotes `\"` are there for that reason. I wonder why they are present in your output. Or why the closing escape is interpreted as the part of the `__SDIR__` macro, leading to the error.

**Comment by kkremitzki** [comment]
Are you using gcc8 by any chance?

**Comment by rc** [comment]
No, I have gcc 5.4.0 or 4.8.4.

**Comment by rc** [comment]
I have just merged #502 which should fix this issue. Can you confirm?

**Comment by kkremitzki** [comment]
Yep, that fixed it! Unfortunately the soft freeze just started yesterday so it's too late to make it into Debian 10, but I'll get the package fixed up ASAP.

**Comment by rc** [comment]
OK, thanks!
