### ISSUE TITLE
Installing from source on Windows to run under Python 3.7 reports unexpected Python 2 code

### ISSUE THREAD

**Issue by BoarGules** [sfepy/sfepy#505]
I downloaded `https://github.com/sfepy/sfepy.git` as a zipfile, extracted it and compiled it from source. Close to the end of the installation there appeared this message:

```
Processing sfepy-2019.1-py3.7-win-amd64.egg
creating e:\python37\lib\site-packages\sfepy-2019.1-py3.7-win-amd64.egg
Extracting sfepy-2019.1-py3.7-win-amd64.egg to e:\python37\lib\site-packages
  File "e:\python37\lib\site-packages\sfepy-2019.1-py3.7-win-amd64.egg\sfepy\examples\linear_elasticity\dispersion_analysis.py", line 319
    print key
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(key)?
```

**Comment by rc** [comment]
Thanks for the report - it will be fixed in the master soon (forgot to remove a debug output). It is fixed in https://github.com/rc/sfepy/tree/misc-updates.

**Comment by rc** [comment]
Could you try the current master branch? (The fix is merged.)

**Comment by rc** [comment]
Closing, feel free to reopen if the problem persists.
