### ISSUE TITLE
Support for matplotlib

### ISSUE THREAD

**Issue by mmatera** [sfepy/sfepy#507]
It would be great to have the option of using matplotlib as the backend for the graphics output, since it work both in python 2.7 and 3.4 and has good integration with jupyter.

**Comment by rc** [comment]
Hi, there is some limited support to plot meshes and their entities (edges, faces etc.) using matplotlib. For a full-featured post-processing, especially in 3D, matplotlib would be IMO too slow. IIRC, interactive mayavi 3D plots can be also included in a jupyter notebook.

**Comment by rc** [comment]
The question has been answered, so let's close this issue.
