### ISSUE TITLE
Question about meshing in sfepy

### ISSUE THREAD

**Issue by awa5114** [sfepy/sfepy#508]
Is it possible to pre and post- process a model in sfepy without the use of the 3rd party mesher? Does sfepy have built in meshing classes that can do the work similar to libraries like `fipy`? If not, is there an ambition to come up with such a feature?

**Comment by rc** [comment]
There is no such ambition right now that I am aware of. Only simple meshes can be generated by sfepy - check `script/blockgen.py`, `script/cylindergen.py`.

**Comment by awa5114** [comment]
Would be nice to integrate object-oriented meshing as opposed to jumping from a mesher and text files like they did back in the 70's! :)

**Comment by rc** [comment]
IMHO this is out of scope of sfepy -  you might want to have a look at other packages, such as ngsolve.

**Comment by rc** [comment]
I am closing this issue, but feel free to post more to the thread or reopen.
