### ISSUE TITLE
Running material identification script

### ISSUE THREAD

**Issue by HaominIsMe** [sfepy/sfepy#509]
I tried to run 'examples/homogenization/material_opt.py' after install sfepy. I got this output and error:

` exec(open("examples/homogenization/material_opt.py").read())`
material_opt_micro: left over: ['is_opt', 'mnodes', 'S', 'F', 'verbose', '_filename']
material_opt_macro: reading mesh [user] (function:mesh_hook)...
material_opt_macro: ...done in 0.00 s
material_opt_macro: creating regions...
material_opt_macro:     Omega
material_opt_macro:     Bottom
material_opt_macro:     Top
material_opt_macro: ...done in 0.02 s
material_opt_macro: equation "balance_of_forces":
material_opt_macro: dw_lin_elastic.5.Omega(solid.D, v, u)
         = dw_surface_ltr.5.Top(load.val, v)
material_opt_macro: using solvers:
                ts: no ts
               nls: newton
                ls: ls
material_opt_macro: reading mesh [line2, tri3, quad4, tetra4, hexa8] (/Users/haominliu/sfepy/meshes/3d/matrix_fiber_rand.vtk)...
material_opt_macro: ...done in 0.04 s
material_opt_macro: left over: ['is_opt', 'mesh', 'bbox', 'all_periodic', 'equation_corrs', 'coefs', 'requirements', 'verbose', '_filename']
material_opt_micro: reading mesh [line2, tri3, quad4, tetra4, hexa8] (/Users/haominliu/sfepy/meshes/3d/matrix_fiber_rand.vtk)...
material_opt_micro: ...done in 0.03 s
material_opt_micro: warning: bad element orientation, trying to correct...
material_opt_micro: ...corrected
material_opt_micro: creating regions...
material_opt_micro:     Y
material_opt_micro:     Ym
material_opt_micro:     Near
material_opt_micro:     Far
material_opt_micro:     Bottom
material_opt_micro:     Top
material_opt_micro:     Left
material_opt_micro:     Right
material_opt_micro:     Corners
material_opt_micro:     Yf
material_opt_micro: ...done in 0.05 s
material_opt_micro: using solvers:
                ts: no ts
               nls: newton
                ls: ls
》》》 material optimization START 《《《
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 157, in <module>
  File "<string>", line 153, in main
  File "<string>", line 135, in material_optimize
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/tnc.py", line 275, in fmin_tnc
    res = _minimize_tnc(fun, x0, args, jac, bounds, callback=callback, **opts)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/tnc.py", line 353, in _minimize_tnc
    if len(bounds) != n:
TypeError: object of type 'zip' has no len()

Any ideas to fix it?

**Comment by vlukes** [comment]
Hi,

In Python 3, zip returns a generator object instead of a list as in 
Python 2. The following fix should work:

	xopt = fmin_tnc(feval, x0, approx_grad=True, bounds=list(bnds),
                         xtol=1e-3, callback=istep)

i.e. bounds=bnds -> bounds=list(bnds)

It will send the fix to the main repository in a few minutes.

Regards,
Vladimir
