### ISSUE TITLE
Question about how to save vtk file during each timestep

### ISSUE THREAD

**Issue by HaominIsMe** [sfepy/sfepy#514]
Hi all,

I was trying this example in _examples/large_deformation/compare_elastic_materials.py_
It simulates the compression and tension test. Does anyone know how to dump the vtk file for each timestep? Thank you.

**Comment by vlukes** [comment]
Hi,

set 'save_results=True' at line 150 and set the different output 
filenames for each branch and material as

   problem.setup_output('out_%s_%s' % (branch_function.__name__, key))

Put the line before problem.solve().

Regards
Vladimir

**Comment by HaominIsMe** [comment]
Thanks, @vlukes 
In addition, do you know how to modify `def define()` in order to iterate different mesh files? I am quite new to python. This is the snip of code I changed, how could I include the iterator in `def define()`
```
def define():
    """Define the problem to solve."""
    from sfepy.discrete.fem.meshio import UserMeshIO
    from sfepy.mesh.mesh_generators import gen_block_mesh
    from sfepy.mechanics.matcoefs import stiffness_from_youngpoisson, stiffness_from_lame
    from sfepy.discrete.fem import Mesh

    def mesh_hook(mesh, mode, n):
        """
        load file
        """
        if mode == 'read':
            mesh = Mesh.from_file('/FEM/tetra%d.mesh'%n) # mesh files are saved as tetra0.mesh, tetra1.mesh...
            return mesh

        elif mode == 'write':
            pass

    filename_mesh = UserMeshIO(mesh_hook)
```

Thank you very much.

**Comment by vlukes** [comment]
Hi @HaominIsMe,

In order to iterate different mesh files you can either:
1) run the following python snippet:

        import sys
        sys.path.append('.')

        from sfepy.base.conf import ProblemConf, get_standard_keywords
        from sfepy.base.base import Struct
        from sfepy.applications import PDESolverApp

        for f in ['mesh1.vtk', 'mesh2.vtk']:

            required, other = get_standard_keywords()
            conf = ProblemConf.from_file(YOUR_PROB_DESC_FILE, required, other,
                                        define_args={'filename_mesh': f})

            options = Struct(output_filename_trunk=None)

            app = PDESolverApp(conf, options, 'sfepy [%s]' % f)
            app()

    and change`define()` function in YOUR_PROB_DESC_FILE as follows:

        def define(filename_mesh=None):

or

2) use imperative API, see e.g. `examples/linear_elasticity/linear_elastic_interactive.py`

Regards
Vladimir

**Comment by rc** [comment]
The question has been answered, so let's close this issue.
