### ISSUE TITLE
question about Problem design

### ISSUE THREAD

**Issue by mganglb** [sfepy/sfepy#518]
Hello sfepy-community,
I apologize for spamming a general question in the issue board, but I do not want to bother the main developers with a question from an FEM noob. I had a briefly look at the examples already but I am not sure if I am able to figure that out on my own.

- **Problem:** 

My Problem consists out of three (two) geometries (3D):
**Geometry (I)** is a custom mesh what is moving with a given velocity before impact. After the impact a force acting on the center of gravity of the mesh.
Variables: velocity vector, force vector/function, custom geometry.
**Geometry (II)** is a hyperelastic body. (Cylinder). For this body I have the necessary properties to solve the Neo Hook sold equation. 
Variables: c10, d1, cylinder geometry
**Geometry (III)** is a simple spring with a spring constant. The bottom of this body is fixed.
Variables: spring constantan, (damping constant)

![image](https://user-images.githubusercontent.com/43035491/58417158-36816980-8084-11e9-8a93-637d05276817.png)

- **Goal:**

Stress values of part (II) over time.

- **Questions:** 

**Is that problem solvable with sfepy?**
Could someone point me in the right direction?

**Comment by rc** [comment]
Hi,

the implementation of contacts in sfepy is still a work-in-progress, but maybe a pseudo-contact like in http://sfepy.org/doc-devel/examples/linear_elasticity/elastic_contact_sphere.html might help. Modelling hyperelastic bodies is possible, check http://sfepy.org/doc-devel/examples/large_deformation/index.html. The springs at the bottom might be modeled as in https://github.com/sfepy/sfepy/blob/master/tests/test_elasticity_small_strain.py by the dw_point_lspring term.

r.
