### ISSUE TITLE
postprocess failed

### ISSUE THREAD

**Issue by geoyanzhan3** [sfepy/sfepy#524]
Hi sfepy team, 

I am following the tutorial and running an "Interactive example: Linear Elasticity" on the Jupyter notebook. 

When I run the cell with:

`from sfepy.postprocess.viewer import Viewer`
`view = Viewer('regions.vtk')`
`view()`

I got an error saying: 

> "No module named 'dock_window'.

I have also attached detailed error message. 

The previous cells have run without any errors.

Thank you very much, 
Yan Zhan
[error_messages.txt](https://github.com/sfepy/sfepy/files/3279582/error_messages.txt)

**Comment by rc** [comment]
Hi Yan Zhan,

we do not have experience with running sfepy in the Jupyter notebook, but this seems like a mayavi integration problem - does mayavi work in your notebook by itself?

r.

**Comment by gustxsr** [comment]
Hello!
I also experienced a similar problem with the postprocessor while running the "Interactive example: Linear Elasticity" in an IPython console in Spyder. When I run from:
 `sfepy.postprocess.viewer import Viewer`
I get the following error:
`File "<ipython-input-48-3eb8aedd3e6f>", line 1, in <module>
 from sfepy.postprocess.viewer import Viewer
  File "C:\ProgramData\Anaconda3\lib\site-packages\sfepy\postprocess\viewer.py", line 22, in <module>
    from traits.api \
ModuleNotFoundError: No module named 'traits'` 
Thank you for any help you can provide!
Gustavo Santiago-Reyes

**Comment by gustxsr** [comment]
Solved it! I just had to install mayavi in my Anaconda. I think when I installed sfepy, mayavi didn't download. 
-Gustavo

**Comment by rc** [comment]
Thanks Gustavo, for the follow-up. If you happen to make mayavi running in a Jupyter notebook, chime in, please.

**Comment by gustxsr** [comment]
At least for me, mayavi is running in both IPython and a Jupyter Notebook.

**Comment by rc** [comment]
Thanks! What are your Anaconda and mayavi versions - that might help @geoyanzhan3.

**Comment by gustxsr** [comment]
In anaconda prompt, `conda --version` outputs **conda 4.7.6**, `mayavi2 --version` outputs **Mayavi 4.7.0**, and `anaconda --version` outputs **anaconda Command line client (version 1.7.2)**.
Hope this helps!

**Comment by rc** [comment]
Thanks again!

**Comment by rc** [comment]
The question has been answered, so let's close this issue.

**Comment by ByronGermanB** [comment]
Hello,
I have a similar error, but in this case the module itself is not found.

----> 1 from sfepy.postprocess.viewer import Viewer

ModuleNotFoundError: No module named 'sfepy.postprocess.viewer'
