### ISSUE TITLE
ValueError: ccore error 

### ISSUE THREAD

**Issue by quantumiracle** [sfepy/sfepy#535]
Hi,
I have an error when trying to use linear_elastic.py with my imported mesh. The error is:

sfepy: left over: ['verbose', '__builtins__', 'absolute_import', '__doc__', '__name__', 'data_dir', '__package__', 'stiffness_from_lame', '_filename', '__file__']
sfepy: reading mesh [line2, tri3, quad4, tetra4, hexa8] (/home/quantumiracle/research/Tactile/simulation/SfePy/sfepy/meshes/tactip.vtk)...
sfepy: ...done in 0.86 s
sfepy: warning: mesh with topological dimension 2 lower than space dimension 3
sfepy: - element orientation not checked!
sfepy: creating regions...
sfepy:     SomewhereTop
sfepy:     Right
sfepy:     Omega
sfepy:     Left
sfepy: ...done in 0.04 s
sfepy: equation "balance_of_forces":
sfepy: dw_lin_elastic.i.Omega(solid.D, v, u) = 0
sfepy: using solvers:
                ts: no ts
               nls: newton
                ls: ls
sfepy: solver construction failed with: "OSError('libdmumps.so: cannot open shared object file: No such file or directory',)"
sfepy: 'ls.mumps' not available, trying 'ls.scipy_umfpack'
sfepy: solver construction failed with: "ValueError('UMFPACK not available!',)"
sfepy: 'ls.scipy_umfpack' not available, trying 'ls.scipy_superlu'
sfepy: using 'ls.scipy_superlu' solver
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.01 s
sfepy: matrix shape: (8394, 8394)
sfepy: assembling matrix graph...
sfepy: ...done in 0.01 s
sfepy: matrix structural nonzeros: 165096 (2.34e-03% fill)
sfepy: updating variables...
sfepy: ...done
sfepy: updating materials...
sfepy:     solid
sfepy: ...done in 0.02 s
warp violation -1.902341e-311 at (iel: 1, iqp: 0)!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
sfepy: giving up!
Traceback (most recent call last):
  File "simple.py", line 182, in <module>
    main()
  File "simple.py", line 179, in main
    app()
...
    raise ValueError('ccore error (see above)')
ValueError: ccore error (see above)

Do you know how to solve this?

**Comment by rc** [comment]
Hi,

the problems is related to your mesh: sfepy does not support (with the exception of the shell10x term) meshes with topological dimension lower that the space dimension (see the warning).

r.

**Comment by quantumiracle** [comment]
Hi,
but I follow the tutorial to process the mesh [here](http://sfepy.org/doc-devel/preprocessing.html#gmsh-generating-finite-element-mesh) to generate the 3d mesh. Do you know how to make it same topological dimension as the space dimension?
Thanks.

**Comment by rc** [comment]
Did you do also the last step described there?
```
script/convert_mesh.py screwdriver_handle.msh screwdriver_handle.vtk
```
This is required to strip the surface elements.

**Comment by quantumiracle** [comment]
yes, I have. Still the same problem.

**Comment by rc** [comment]
Could you attach/post somewhere a minimal working example demonstrating the problem?

**Comment by rc** [comment]
Stale issue cleanup.
