### ISSUE TITLE
Interactive (IPython) example of homogenization

### ISSUE THREAD

**Issue by gustxsr** [sfepy/sfepy#536]
Hello sfepy team!
I was wondering if there are any examples of homogenizing a material with a periodic microstructure written similar to the interactive example of Linear Elasticity in section 3.5 of the Sfepy Documentation. I find this a lot easier to understand than the others.
Thank you beforehand!
Gustavo

**Comment by vlukes** [comment]
Hi Gustavo,

there is no interactive homogenization example in Sfepy documentation. 
We use the problem description files to describe various homogenization 
problems. I think that homogenized coefficients and all requirements can 
be defined more clearly using the declarative approach (problem 
description files) than in the case of interactive computation.

Vladimir

**Comment by gustxsr** [comment]
Thank you so much!
