### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by claytonkanderson** [sfepy/sfepy#538]
Unable to install on windows through Anaconda due to missing packages.

![image](https://user-images.githubusercontent.com/30035547/61473479-78c47a00-a954-11e9-8252-a6e034233444.png)

This is with Conda 4.7.5, Python 3.7 on Windows 10.

**Comment by gustxsr** [comment]
Hello!
I was having this exact problem. Furthermore, after trying to install mpi4py and libgcc-ng individually, my anaconda started failing (as in, my Anaconda prompt was erased and the conda command didn't work). The way I managed to fix it (and hopefully I am not forgetting any steps) was by:
1. Uninstalling Anaconda.
2. Installing Anaconda in another directory.
3. In Anaconda Prompt, run `conda install -c conda-forge sfepy` (as in section 2.3 of the Sfepy documentation).
After it was finished, I believe there was a warning that I had to install Microsoft Visual C++ 14.0 before mpi4py can install, but I could still import sfepy and work with it in a Jupyter notebook or IPython.
I still haven't solved the Visual C++ problem (which means I cannot use Description Files), but hopefully, this information helps. 
Before trying anything, I would open `python` in the Anaconda Prompt and verify if `import sfepy` sends any ErrorMessages.
Good luck!
-Gustavo

**Comment by claytonkanderson** [comment]
Hey @gustxsr 

Thanks for the reply.

Unfortunately this is a clean install of Anaconda and the error I'm getting is in response to `conda install -c conda-forge sfepy`

Here is the full output from the command,

![image](https://user-images.githubusercontent.com/30035547/61543031-af5fca80-aa10-11e9-9ffa-c1bcdc08b0ee.png)

**Comment by claytonkanderson** [comment]
Seem to have fixed the problem by using
`conda install -c conda-forge/label/cf201901 sfepy ` from https://anaconda.org/conda-forge/sfepy
and installing mpi4py separately with `conda install -c anaconda mpi4py ` from https://anaconda.org/anaconda/mpi4py

Thanks again @gustxsr for your help.

**Comment by rc** [comment]
Anaconda is a moving target, so if you feel that the installation instructions in the sfepy manual need updating, feel free to do so. Thanks, @gustxsr, for your help!

**Comment by rc** [comment]
FYI: There is a new release (2019.3) available on conda-forge. I am closing this issue, but do not hesitate to report further problems.
