### ISSUE TITLE
Running material identification script part II

### ISSUE THREAD

**Issue by gustxsr** [sfepy/sfepy#539]
Hello team!
I wasn't sure if I should post this problem under the closed issue relating to running material_opt.py so I created a part II. When I run the program I get the following TypeError:

`File "stringsource", line 2, in sfepy.discrete.common.extmods.cmesh.CMesh.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__`

Below is the whole output. Thank you!

![image](https://user-images.githubusercontent.com/46436777/61712272-f6f19980-ad23-11e9-8a78-80010d4ba47d.png)
![image](https://user-images.githubusercontent.com/46436777/61712322-0e308700-ad24-11e9-8183-882301430ae8.png)
![image](https://user-images.githubusercontent.com/46436777/61712385-36b88100-ad24-11e9-8473-b9036a4cf6b4.png)
![image](https://user-images.githubusercontent.com/46436777/61712437-55b71300-ad24-11e9-9af9-453c4131cf98.png)
![image](https://user-images.githubusercontent.com/46436777/61712471-6a93a680-ad24-11e9-87b5-d50723c7c5ad.png)

**Comment by rc** [comment]
This might be related to #494 - try adding `'multiprocessing' : False,` option to `examples/homogenization/homogenization_opt.py` into the options dict on the line 109, for example in this way:
```
    options = {
        'coefs': 'coefs',
        'requirements': 'requirements',
        'volume': { 'variables' : ['u'], 'expression' : 'd_volume.5.Y( u )' },
        'output_dir': 'output',
        'coefs_filename': 'coefs_le',
        'multiprocessing' : False,
    }
```

**Comment by rc** [comment]
Stale issue cleanup, feel free to ask more.
