### ISSUE TITLE
Defining groups in Gmsh 

### ISSUE THREAD

**Issue by gustxsr** [sfepy/sfepy#540]
Greetings!
When I am creating a region for my mesh (like for example in the next line)
`cell = domain.create_region('Cell', 'vertices of group 1', 'facet')`
How can I know which group belongs to what part of my mesh? My mesh consists of a 2D square with a circle in the center. In Gmsh, I defined the circle in the middle to be surface 2, while the part that does not belong to the circle is surface 1. However, I have been inputting different group numbers and none of them seem to be working.
Thank you!

**Comment by rc** [comment]
IIRC this is not trivial - have you looked at http://sfepy.org/doc-devel/preprocessing.html? @vlukes might be able to help.

**Comment by rc** [comment]
It is possible now to import gmsh meshes using meshio (#580), so defining groups should work. Feel free to reopen, if that is not the case.
