### ISSUE TITLE
Creating unit cell for homogenization

### ISSUE THREAD

**Issue by gustxsr** [sfepy/sfepy#541]
Hello!

I apologize for the spam of question and thank you for your time! I was wondering if the shape of each of the element in a model (say of a hollow sphere) has to be identical to that of every element and to the shape of the unit cell created for homogenization. 

Thank you!
Gustavo

**Comment by rc** [comment]
If I understand your question correctly, the shape of the macroscopic domain and its elements are completely unrelated to the shape of the reference unit cell.

**Comment by gustxsr** [comment]
Thank you!!
