### ISSUE TITLE
How to run linear_elastic_mM.py?

### ISSUE THREAD

**Issue by gustxsr** [sfepy/sfepy#542]
Hello!

I was wondering which program I should use to run linear_elastic_mM.py. I have tried simple.py and homogen.py but both of them have errors.

Thank you!
Gustavo

**Comment by rc** [comment]
Hi Gustavo,

python simple.py examples/homogenization/linear_elastic_mM.py should work. What is the error you are getting?

**Comment by gustxsr** [comment]
I am getting `KeyError: 'ls.auto_iterative'`.

This is the whole output:
![image](https://user-images.githubusercontent.com/46436777/62209354-650f0f80-b367-11e9-9246-250b74917463.png)
![image](https://user-images.githubusercontent.com/46436777/62209401-853ece80-b367-11e9-9e58-925689bb4a60.png)
![image](https://user-images.githubusercontent.com/46436777/62209464-a7385100-b367-11e9-9f8f-c5a2c025687a.png)

Thank you!

**Comment by gustxsr** [comment]
I copy-pasted some folders from the version of sfepy that was installed in my computer to sfepy-2019.2 folder and ran the code again and now I am getting a ValueError:
`ValueError: term 'ev_volume_integrate_mat' is not in ['d_of_ns_min_grad', 'd_of_ns_surf_min_d_press', 'd_sd_convect', 'd_sd_diffusion', 'd_sd_div', 'd_sd_div_grad', 'd_sd_lin_elastic', 'd_sd_st_grad_div', 'd_sd_st_pspg_c', 'd_sd_st_pspg_p', 'd_sd_st_supg_c', 'd_sd_surface_integrate', 'd_sd_volume_dot', 'd_sum_vals', 'd_surface', 'd_surface_flux', 'd_surface_moment', 'd_tl_surface_flux', 'd_tl_volume_surface', 'd_volume', 'd_volume_surface', 'dw_adj_convect1', 'dw_adj_convect2', 'dw_adj_div_grad', 'dw_advect_div_free', 'dw_bc_newton', 'dw_biot', 'dw_biot_eth', 'dw_biot_th', 'dw_contact', 'dw_contact_plane', 'dw_contact_sphere', 'dw_convect', 'dw_convect_v_grad_s', 'dw_diffusion', 'dw_diffusion_coupling', 'dw_diffusion_r', 'dw_div', 'dw_div_grad', 'dw_elastic_wave', 'dw_elastic_wave_cauchy', 'dw_electric_source', 'dw_jump', 'dw_laplace', 'dw_lin_convect', 'dw_lin_elastic', 'dw_lin_elastic_eth', 'dw_lin_elastic_iso', 'dw_lin_elastic_th', 'dw_lin_prestress', 'dw_lin_strain_fib', 'dw_non_penetration', 'dw_non_penetration_p', 'dw_nonsym_elastic', 'dw_of_ns_surf_min_d_press_diff', 'dw_piezo_coupling', 'dw_point_load', 'dw_point_lspring', 'dw_s_dot_grad_i_s', 'dw_s_dot_mgrad_s', 'dw_shell10x', 'dw_st_adj1_supg_p', 'dw_st_adj2_supg_p', 'dw_st_adj_supg_c', 'dw_st_grad_div', 'dw_st_pspg_c', 'dw_st_pspg_p', 'dw_st_supg_c', 'dw_st_supg_p', 'dw_stokes', 'dw_stokes_wave', 'dw_stokes_wave_div', 'dw_surface_dot', 'dw_surface_flux', 'dw_surface_integrate', 'dw_surface_ltr', 'dw_surface_ndot', 'dw_tl_bulk_active', 'dw_tl_bulk_penalty', 'dw_tl_bulk_pressure', 'dw_tl_diffusion', 'dw_tl_fib_a', 'dw_tl_he_mooney_rivlin', 'dw_tl_he_neohook', 'dw_tl_membrane', 'dw_tl_surface_traction', 'dw_tl_volume', 'dw_ul_bulk_penalty', 'dw_ul_bulk_pressure', 'dw_ul_compressible', 'dw_ul_he_mooney_rivlin', 'dw_ul_he_neohook', 'dw_ul_volume', 'dw_v_dot_grad_s', 'dw_vm_dot_s', 'dw_volume_dot', 'dw_volume_dot_w_scalar_eth', 'dw_volume_dot_w_scalar_th', 'dw_volume_integrate', 'dw_volume_lvf', 'dw_zero', 'ev_biot_stress', 'ev_cauchy_strain', 'ev_cauchy_strain_s', 'ev_cauchy_stress', 'ev_cauchy_stress_eth', 'ev_cauchy_stress_th', 'ev_def_grad', 'ev_diffusion_velocity', 'ev_div', 'ev_grad', 'ev_integrate_mat', 'ev_piezo_strain', 'ev_piezo_stress', 'ev_surface_div', 'ev_surface_grad', 'ev_surface_integrate', 'ev_volume_integrate']`

**Comment by rc** [comment]
I suggest you try a fresh install of the latest release and do the in-place build to prevent mixing files from different sfepy versions/installations. If that does not help (post any new error message here, please)), you may try to change `'ls.auto_iterative'` to `'ls.scipy_direct'` in `examples/homogenization/linear_homogenization_up.py`.

**Comment by gustxsr** [comment]
Thank you! The first problem got fixed by changing `ls.auto_iterative` to `ls.scipy_direct`. However, now I am getting a KeyError for 'u_00' in linear_homogenization_up.py (line 41). This is the full output:

Traceback (most recent call last):
  File "simple.py", line 182, in <module>
    main()
  File "simple.py", line 179, in main
    app()
  File "/home/dtic/anaconda3/lib/python3.6/site-packages/sfepy/applications/application.py", line 29, in call_basic
    return self.call(**kwargs)
  File "/home/dtic/anaconda3/lib/python3.6/site-packages/sfepy/applications/pde_solver_app.py", line 225, in call
    post_process_hook_final=self.post_process_hook_final)
  File "/home/dtic/anaconda3/lib/python3.6/site-packages/sfepy/discrete/problem.py", line 1383, in solve
    status=status)
  File "/home/dtic/anaconda3/lib/python3.6/site-packages/sfepy/solvers/ts_solvers.py", line 34, in _standard_ts_call
    status=status, **kwargs)
  File "/home/dtic/anaconda3/lib/python3.6/site-packages/sfepy/solvers/ts_solvers.py", line 77, in __call__
    poststep_fun(ts, vec)
  File "/home/dtic/anaconda3/lib/python3.6/site-packages/sfepy/discrete/problem.py", line 1232, in poststep_fun
    ts=ts)
  File "/home/dtic/anaconda3/lib/python3.6/site-packages/sfepy/discrete/problem.py", line 801, in save_state
    out = post_process_hook(out, self, state, extend=extend)
  File "/home/dtic/Downloads/sfepy-2019.2/examples/homogenization/linear_elastic_mM.py", line 38, in post_process
    region, {'strain' : rstrain})
  File "/home/dtic/anaconda3/lib/python3.6/site-packages/sfepy/homogenization/recovery.py", line 520, in recover_micro_hook
    out = recovery_hook(pb, corrs, local_macro)
  File "/home/dtic/Downloads/sfepy-2019.2/examples/homogenization/linear_homogenization_up.py", line 41, in recovery_le
    dim = corrs['corrs_le']['u_00'].shape[1]
KeyError: 'u_00'

**Comment by rc** [comment]
Try removing all `output/corrs_le*` and `output/coefs_le*` files - maybe you have a corrupted file from a previous unsuccessful run?

**Comment by rc** [comment]
Stale issue cleanup, feel free to ask more.
