### ISSUE TITLE
Sfepy Giving up | Ccore error

### ISSUE THREAD

**Issue by gustxsr** [sfepy/sfepy#543]
Hello!
I am working with a partially modified version of the Interactive Example from the Sfepy Documentation in a Jupyter Notebook but when I run `vec = pb.solve(status = status)`, the program outputs `sfepy: giving up` and at the end `ValueError: ccore error (see above)`.  I am using the tetrahedral mesh of a rectangular prism (16x16x1) that has 64 evenly spaced cylinders inside (this is the mesh): 

![image](https://user-images.githubusercontent.com/46436777/62382411-7bf66300-b51b-11e9-8d91-337791bcf1eb.png)

Is there something wrong with my mesh? I could also share the mesh file and jupyter notebook.
Thank you!

This is the whole error message:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-b68e38a571c1> in <module>()
----> 1 vec = pb.solve(status = status)

~/anaconda3/lib/python3.6/site-packages/sfepy/discrete/problem.py in solve(self, state0, status, force_values, var_data, update_bcs, update_materials, save_results, step_hook, post_process_hook, post_process_hook_final, verbose)
   1381                       prestep_fun=prestep_fun,
   1382                       poststep_fun=poststep_fun,
-> 1383                       status=status)
   1384             output('solved in %d steps in %.2f seconds'
   1385                    % (status['n_step'], status['time']), verbose=verbose)

~/anaconda3/lib/python3.6/site-packages/sfepy/solvers/ts_solvers.py in _standard_ts_call(self, vec0, nls, init_fun, prestep_fun, poststep_fun, status, **kwargs)
     32         result = call(self, vec0=vec0, nls=nls, init_fun=init_fun,
     33                       prestep_fun=prestep_fun, poststep_fun=poststep_fun,
---> 34                       status=status, **kwargs)
     35 
     36         ttt = time.clock() - tt

~/anaconda3/lib/python3.6/site-packages/sfepy/solvers/ts_solvers.py in __call__(self, vec0, nls, init_fun, prestep_fun, poststep_fun, status, **kwargs)
     73         prestep_fun(ts, vec0)
     74 
---> 75         vec = nls(vec0)
     76 
     77         poststep_fun(ts, vec)

~/anaconda3/lib/python3.6/site-packages/sfepy/solvers/nls.py in __call__(self, vec_x0, conf, fun, fun_grad, lin_solver, iter_hook, status)
    256 
    257                 try:
--> 258                     vec_r = fun(vec_x)
    259 
    260                 except ValueError:

~/anaconda3/lib/python3.6/site-packages/sfepy/discrete/evaluate.py in eval_residual(self, vec, is_full)
     74             vec = self.make_full_vec(vec)
     75 
---> 76         vec_r = self.problem.equations.eval_residuals(vec)
     77         if self.matrix_hook is not None:
     78             vec_r = self.matrix_hook(vec_r, self.problem, call_mode='residual')

~/anaconda3/lib/python3.6/site-packages/sfepy/discrete/equations.py in eval_residuals(self, state, by_blocks, names)
    699             out = self.create_stripped_state_vector()
    700 
--> 701             self.evaluate(mode='weak', dw_mode='vector', asm_obj=out)
    702 
    703         return out

~/anaconda3/lib/python3.6/site-packages/sfepy/discrete/equations.py in evaluate(self, names, mode, dw_mode, term_mode, asm_obj)
    632             for eq in eqs:
    633                 out = eq.evaluate(mode=mode, dw_mode=dw_mode,
--> 634                                   term_mode=term_mode, asm_obj=asm_obj)
    635                 if isinstance(out, tuple): extras.extend(out[1])
    636 

~/anaconda3/lib/python3.6/site-packages/sfepy/discrete/equations.py in evaluate(self, mode, dw_mode, term_mode, asm_obj)
    851                                                       term_mode=term_mode,
    852                                                       standalone=False,
--> 853                                                       ret_status=True)
    854                     term.assemble_to(asm_obj, val, iels, mode=dw_mode)
    855 

~/anaconda3/lib/python3.6/site-packages/sfepy/terms/terms.py in evaluate(self, mode, diff_var, standalone, ret_status, **kwargs)
   1409             else:
   1410                 _args = tuple(args) + (mode, term_mode, diff_var)
-> 1411                 fargs = self.call_get_fargs(_args, kwargs)
   1412 
   1413                 if varr.dtype == nm.float64:

~/anaconda3/lib/python3.6/site-packages/sfepy/terms/terms.py in call_get_fargs(self, args, kwargs)
   1245     def call_get_fargs(self, args, kwargs):
   1246         try:
-> 1247             fargs = self.get_fargs(*args, **kwargs)
   1248 
   1249         except (RuntimeError, ValueError):

~/anaconda3/lib/python3.6/site-packages/sfepy/terms/terms_elastic.py in get_fargs(self, mat, virtual, state, mode, term_mode, diff_var, **kwargs)
     54     def get_fargs(self, mat, virtual, state,
     55                   mode=None, term_mode=None, diff_var=None, **kwargs):
---> 56         vg, _ = self.get_mapping(state)
     57 
     58         if mode == 'weak':

~/anaconda3/lib/python3.6/site-packages/sfepy/terms/terms.py in get_mapping(self, variable, get_saved, return_key)
   1032                                          self.integral, integration,
   1033                                          get_saved=get_saved,
-> 1034                                          return_key=return_key)
   1035 
   1036         return out

~/anaconda3/lib/python3.6/site-packages/sfepy/discrete/common/fields.py in get_mapping(self, region, integral, integration, get_saved, return_key)
    241 
    242         if out is None:
--> 243             out = self.create_mapping(region, integral, integration)
    244             self.mappings[key] = out
    245 

~/anaconda3/lib/python3.6/site-packages/sfepy/discrete/fem/fields_base.py in create_mapping(self, region, integral, integration, return_mapping)
   1010             vg = mapping.get_mapping(qp.vals, qp.weights, poly_space=ps,
   1011                                      ori=self.ori,
-> 1012                                      transform=self.basis_transform)
   1013 
   1014             out = vg

~/anaconda3/lib/python3.6/site-packages/sfepy/discrete/fem/mappings.py in get_mapping(self, qp_coors, weights, poly_space, ori, transform)
     97         cmap = CMapping(self.n_el, qp_coors.shape[0], self.dim,
     98                         poly_space.n_nod, mode='volume', flag=flag)
---> 99         cmap.describe(self.coors, self.conn, bf_g, ebf_g, weights)
    100 
    101         return cmap

sfepy/discrete/common/extmods/mappings.pyx in sfepy.discrete.common.extmods.mappings.CMapping.describe()

ValueError: ccore error (see above)

**Comment by rc** [comment]
Yes, sharing the mesh and code reproducing the error would be helpful.

**Comment by gustxsr** [comment]
Here I send the Jupyter Note?book and two meshes (one that is all tetrahedral (ends in tet) and the other that is hexahedral (ends in hex)). The filename in the notebook has to be changed to run the program.

________________________________
De: Robert Cimrman <notifications@github.com>
Enviado: viernes, 02 de agosto de 2019 04:55 p.m.
Para: sfepy/sfepy
Cc: Gustavo X Santiago-Reyes; Author
Asunto: Re: [sfepy/sfepy] Sfepy Giving up | Ccore error (#543)


Yes, sharing the mesh and code reproducing the error would be helpful.

-

**Comment by rc** [comment]
@gustxsr have you really attached the files? I cannot see them.

**Comment by rc** [comment]
Stale issue cleanup, feel free to ask more.
