### ISSUE TITLE
problems with examples/homogenization/perfusion_micro.py

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#551]
In current master, running (the python version is not important)
```
python3 ./homogen.py examples/homogenization/perfusion_micro.py
```
runs fails with `'multiprocessing' : False,` option, i.e. always on windows, where multiprocessing is disabled (see #494), and on linux when multiprocessing is switched off.
The error is something like (the variable name can be different):
```
ValueError: argument qM not found! 
```
so the dependency resolution in the serial homogenization engine seems to be broken.

@vlukes Could you have a look at this when you have some time? Thanks!

**Comment by rc** [comment]
With `'multiprocessing' : True,` the example sometimes (rarely) hangs instead of exiting normally.

**Comment by BubuLK** [comment]
FYI: (as already declared some time ago...) I can easily setup Windows 10 with conda Python environment (based on "CIV cloud" with remote RDP access) if someone interested in...
LK

**Comment by rc** [comment]
With Python 2.7, regardless of multiprocessing option, the code seems to hang here:
```
    while remaining.value > 0:
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 1039, in get
    return self._callmethod('get')
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
```
But sometimes it finishes normally(?!)
