### ISSUE TITLE
ls.auto_direct fails without mpi4py

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#561]
The `'ls.auto_direct'` solver fails when mpi4py is not installed, because `MUMPSSolver.__init__() `executes without error - then it fails in `.presolve()` on `MumpsSolver` creation. It should either work without mpi4py or fail already in `.__init__() `.

Can be reproduced by setting `use_mpi = False` in `sfepy/solvers/ls_mumps.py` and running `./run_tests.py tests/test_input_linear_elastic.py --raise`.

@vlukes could you have a look at it? Thanks!

**Comment by vlukes** [comment]
The issue should be fixed by #562. `mpi4py` is now tested in `MUMPSSolver.__init__()`.

**Comment by rc** [comment]
Is mpi4py required also when not solving in parallel?
