### ISSUE TITLE
Getting matrix and rhs vector

### ISSUE THREAD

**Issue by gbikpi** [sfepy/sfepy#565]
Hello,
The class **_sfepy.discrete.Problem_** has got an attribute **_mtx_a_**, which I guess is the matrix **A** in the linear system **Ax = b** resulting from FEM discretization. How, please, could I also get the corresponding rhs vector **b**?
Regards.

**Comment by rc** [comment]
Hi,

the `mtx_a` attribute is indeed used to store the matrix, and contains its data after the equations were evaluated. But instead of using it directly, I recomment evaluating the equations, something like:
```
mtx = problem.mtx_a.copy()
mtx = problem.equations.evaluate(mode='weak', dw_mode='matrix', asm_obj=mtx)
vec = problem.equations.create_stripped_state_vector()
vec = problem.equations.evaluate(mode='weak', dw_mode='vector', asm_obj=vec)
```
You can also evaluate each equation separately.

**Comment by gbikpi** [comment]
Great, many thanks!

**Comment by rc** [comment]
I am closing this issue, but feel free to post more to the thread or reopen.
