### ISSUE TITLE
Getting coordinates of row/cols of the mtx_a matrix 

### ISSUE THREAD

**Issue by leopoldcambier** [sfepy/sfepy#570]
Hello,

I'm very new to sfepy.
I'm running the example in http://sfepy.org/doc-devel/examples/multi_physics/biot.html and getting the matrix out.

```
pb, state = solve_pde('.../.../biot.py')
A = pb.mtx_a
```

I would like, for each row/column in the matrix, to get the associated coordinates in 3D.
(We are evaluating linear solvers, and coordinates are useful for a variety of reasons).

Is there a way to get this ?
I found

```
pb.fields['displacement'].coors
pb.fields['pressure'].coors
```
But there are more coordinates than dof, I suppose because of boundary conditions and such.

Is there a generic way to retrieve coordinates ?

Thanks a lot

**Comment by rc** [comment]
Hi,

yes, the matrices/rhs are by default assembled with the rows/columns corresponding to fixed DOFs removed. If you need the coordinates, you may want to use the following option:
```
options = {
    ...
    'active_only' : False,
    ...
}
```
which makes the matrices full size. I have noticed that this option is not described in the docs, I am fixing that now. Note that the rows/columns corresponding to fixed DOFs are modified.

**Comment by leopoldcambier** [comment]
Hi Robert

Thanks for the help ! That could do the job.

However, to stick as much as possible to the original system: is there a way to get the location of the active dofs within the complete set of dofs ? I tried digging in `pb` but couldn't find anything.

Leopold

**Comment by rc** [comment]
Hi Leopold,

try something like
```
variables = pb.get_variables()
vu = variables['u']
print(vu.eq_map)
print(vu.eq_map.eqi)
```
The `.eqi` attribute contains the indices of the active DOFs in the full vector, so it can be used to index into `pb.fields['displacement'].coors` etc. Also, for multiphysical problems, you may want to have a look at `variables.di` and `variables.adi`, where the info on the complete and active DOFs ordering in the global vector is stored. Does it help?

r.

**Comment by leopoldcambier** [comment]
Thanks Robert, that works :-)
Here is the complete code for posterity
```
from sfepy.applications import solve_pde
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d.art3d import Line3DCollection
from mpl_toolkits.mplot3d import Axes3D
import scipy.sparse as sparse
import numpy as np
import scipy.io

## Load problem and solve PDE
pb, state = solve_pde('biot.py')
A = pb.mtx_a

## Compute coords
N = A.shape[0]
coords_A = np.zeros((3, N))
coords = pb.get_mesh_coors()
variables = pb.get_variables()
adi = variables.adi
for (i,v) in enumerate(adi.var_names):
    start = adi.ptr[i]
    end   = adi.ptr[i+1]
    vup   = variables[v]
    eqi   = vup.eq_map.eqi
    dpn  = vup.eq_map.dpn
    coordsi = eqi // dpn
    coords_A[:,start:end] = coords[coordsi,:].T

## Plot
fig = plt.figure()
ax = fig.gca(projection='3d')
cx = scipy.sparse.coo_matrix(A)
lines = [ (coords_A[:,i], coords_A[:,j]) for i,j in zip(cx.row, cx.col) ]
lc = Line3DCollection(lines, linewidths=0.1)
ax.add_collection(lc)
ax.set_xlim( min(coords_A[0,:]), max(coords_A[0,:]) )
ax.set_ylim( min(coords_A[1,:]), max(coords_A[1,:]) )
ax.set_zlim( min(coords_A[2,:]), max(coords_A[2,:]) )
print("Showing")
plt.show()
```

It shows this, which looks as expected to me

![Screen Shot 2019-11-28 at 13 34 30](https://user-images.githubusercontent.com/10196423/69832593-16259980-11e4-11ea-97f7-97454ffb72f4.png)

I guess one last question: is this the right way to map the vector PDE to its "scalar" dof ?

```
coordsi = eqi // dpn
```

**Comment by rc** [comment]
> Thanks Robert, it seems to work :-)
> 
> I guess one last question: is this the right way to map the vector PDE to its "physical" dof ?
> 
> ```
> coordsi = eqi // dpn
> ```

Yes.

> Here is the complete code for posterity
> 
> ```
> from sfepy.applications import solve_pde
> import matplotlib.pylab as plt
> from mpl_toolkits.mplot3d.art3d import Line3DCollection
> from mpl_toolkits.mplot3d import Axes3D
> import scipy.sparse as sparse
> import numpy as np
> import scipy.io
> 
> ## Load problem and solve PDE
> pb, state = solve_pde('biot.py')
> A = pb.mtx_a
> 
> ## Compute coords
> N = A.shape[0]
> coords_A = np.zeros((3, N))
> coords = pb.get_mesh_coors()
> variables = pb.get_variables()

In case of higher order approximations, you would need to use here the field coordinates (relevant only for the default nodal Lagrangian basis), e.g. `variables['u'].field.coors`, to get the coordinates of the higher order nodes too.

> adi = variables.adi
> for (i,v) in enumerate(adi.var_names):
>     start = adi.ptr[i]
>     end   = adi.ptr[i+1]
>     vup   = variables[v]
>     eqi   = vup.eq_map.eqi
>     dpn  = vup.eq_map.dpn
>     coordsi = eqi // dpn
>     coords_A[:,start:end] = coords[coordsi,:].T

You can use `coords_A[:,adi.indx[v]]` here.
 
I  am interested in seeing your future results of the linear solver evaluations you mentioned - do you plan to make them available?

Cheers,
r.

**Comment by leopoldcambier** [comment]
> In case of higher order approximations, you would need to use here the field coordinates (relevant only for the default nodal Lagrangian basis), e.g. variables['u'].field.coors, to get the coordinates of the higher order nodes too.

Got it thanks. Makes sense. I'll update later if I do that. 

> I am interested in seeing your future results of the linear solver evaluations you mentioned - do you plan to make them available?

Yes it will certainly be public at some point.
I'll remember that when they're ready 👍

**Comment by rc** [comment]
OK, thanks! I am closing this issue, but feel free to post more to the thread or reopen.
