### ISSUE TITLE
Documentation (primer) suggestion for improvement

### ISSUE THREAD

**Issue by flothesof** [sfepy/sfepy#572]
Hi and thank you for your excellent work on sfepy.
I was reading through the primer (http://sfepy.org/doc-devel/solving_pdes_by_fem.html) and got confused when the finite element spaces V and V_0 get introduced. 
V(\Omega) = \{f(x) \in H^1(\Omega)\},
V_0(\Omega) = \{f(x) \in H^1(\Omega); f(x) = 0, x \in \Gamma_D\}.
The definitions make use of the symbol f for defining the functions while in the context of the primer, f is already used for defining the volumic term of the Poisson equation.
This is confusing for me as a beginner. Maybe it could be less confusing by using a different notation when introducing the finite element spaces (like phi, for example)?

Regards,
Florian

**Comment by rc** [comment]
Hi Florian,

thanks for your feedback! I am about to replace f(x) with v(x), would that read better for you?

r.

**Comment by flothesof** [comment]
Yes, this sounds good. Thank you :)

Florian

**Comment by rc** [comment]
OK, I will merge it now an update the web site docs soon.
