### ISSUE TITLE
Questionable .gitignore contents

### ISSUE THREAD

**Issue by zdroid** [sfepy/sfepy#576]
I'm not really involved with the project, but I'm curious what's the meaning behind the following lines in `.gitignore`:
```gitignore
output-tests/*
results/*
work/*
auto/*
dist/
gallery/
meshes/
patches/
issues/
```

and especially `meshes/`, since it is already in the repository.

**Comment by rc** [comment]
It just ignores various stuff (historical accretion) that I have in my main sfepy development directory - no deep meaning. The same for `meshes` - I might occasionally have there untracked files that I do not want to see in `git status`.

**Comment by zdroid** [comment]
Okay then, thanks for clarifying.
