### ISSUE TITLE
Sfepy giving up core error on my mesh (file provided)

### ISSUE THREAD

**Issue by mkondratyev85** [sfepy/sfepy#578]
I'm trying to use `diffusion/poisson_short_syntax` file from the example with my mesh. All I've changed is the `filename_mesh` and `Gamma_Right` region.

```python
filename_mesh = '/tmp/triangular.mesh'

materials = {
    'coef' : ({'val' : 1.0},),
}

regions = {
    'Omega' : 'all', # or 'cells of group 6'
    'Gamma_Left' : ('vertices in (x < 0.00001)', 'facet'),
    'Gamma_Right' : ('vertices in (x > 99.099999)', 'facet'),
}

fields = {
    'temperature' : ('real', 1, 'Omega', 1),
}

variables = {
    't' : ('unknown field', 'temperature', 0),
    's' : ('test field',    'temperature', 't'),
}

ebcs = {
    't1' : ('Gamma_Left', {'t.0' : 2.0}),
    't2' : ('Gamma_Right', {'t.0' : -2.0}),
}

integrals = {
    'i' : 2,
}

equations = {
    'Temperature' : """dw_laplace.i.Omega( coef.val, s, t ) = 0"""
}

solvers = {
    'ls' : ('ls.scipy_direct', {}),
    'newton' : ('nls.newton',
                {'i_max'      : 1,
                 'eps_a'      : 1e-10,
    }),
}

options = {
    'nls' : 'newton',
    'ls' : 'ls',
}
```
But when I try to run the script I get the following error:

```
sfepy: left over: ['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__file__', '__cached__', '__builtins__', 'absolute_import', 'data_dir', 'verbose', '_filename']
sfepy: reading mesh [line2, tri3, quad4, tetra4, hexa8] (/tmp/triangular3.mesh)...
sfepy: ...done in 0.31 s
sfepy: warning: bad element orientation, trying to correct...
sfepy: ...corrected
sfepy: creating regions...
sfepy:     Omega
sfepy:     Gamma_Left
sfepy:     Gamma_Right
sfepy: ...done in 0.42 s
sfepy: equation "Temperature":
sfepy: dw_laplace.i.Omega( coef.val, s, t ) = 0
sfepy: using solvers:
                ts: no ts
               nls: newton
                ls: ls
sfepy: saving regions...
sfepy:   Omega
sfepy:   Gamma_Left
sfepy:   Gamma_Right
sfepy: ...done
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.01 s
sfepy: matrix shape: (30770, 30770)
sfepy: assembling matrix graph...
sfepy: ...done in 0.06 s
sfepy: matrix structural nonzeros: 432034 (4.56e-04% fill)
sfepy: updating variables...
sfepy: ...done
sfepy: updating materials...
sfepy:     coef
sfepy: ...done in 0.06 s
warp violation 0.000000e+00 at (iel: 272, iqp: 0)!
warp violation 0.000000e+00 at (iel: 272, iqp: 1)!
warp violation 0.000000e+00 at (iel: 272, iqp: 2)!
warp violation 0.000000e+00 at (iel: 272, iqp: 3)!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
sfepy: giving up!
Traceback (most recent call last):
  File "simple.py", line 182, in <module>
    main()
  File "simple.py", line 179, in main
    app()
  File "/home/fatune/source/sfepy/sfepy/applications/application.py", line 29, in call_basic
    return self.call(**kwargs)
  File "/home/fatune/source/sfepy/sfepy/applications/pde_solver_app.py", line 226, in call
    post_process_hook_final=self.post_process_hook_final)
  File "/home/fatune/source/sfepy/sfepy/discrete/problem.py", line 1414, in solve
    status=status)
  File "/home/fatune/source/sfepy/sfepy/solvers/ts_solvers.py", line 34, in _standard_ts_call
    status=status, **kwargs)
  File "/home/fatune/source/sfepy/sfepy/solvers/ts_solvers.py", line 73, in __call__
    vec = nls(vec0)
  File "/home/fatune/source/sfepy/sfepy/solvers/nls.py", line 257, in __call__
    vec_r = fun(vec_x)
  File "/home/fatune/source/sfepy/sfepy/discrete/evaluate.py", line 73, in eval_residual
    vec_r = self.problem.equations.eval_residuals(vec)
  File "/home/fatune/source/sfepy/sfepy/discrete/equations.py", line 701, in eval_residuals
    self.evaluate(mode='weak', dw_mode='vector', asm_obj=out)
  File "/home/fatune/source/sfepy/sfepy/discrete/equations.py", line 634, in evaluate
    term_mode=term_mode, asm_obj=asm_obj)
  File "/home/fatune/source/sfepy/sfepy/discrete/equations.py", line 853, in evaluate
    ret_status=True)
  File "/home/fatune/source/sfepy/sfepy/terms/terms.py", line 1456, in evaluate
    fargs = self.call_get_fargs(_args, kwargs)
  File "/home/fatune/source/sfepy/sfepy/terms/terms.py", line 1292, in call_get_fargs
    fargs = self.get_fargs(*args, **kwargs)
  File "/home/fatune/source/sfepy/sfepy/terms/terms_diffusion.py", line 40, in get_fargs
    vg, _ = self.get_mapping(state)
  File "/home/fatune/source/sfepy/sfepy/terms/terms.py", line 1077, in get_mapping
    return_key=return_key)
  File "/home/fatune/source/sfepy/sfepy/discrete/common/fields.py", line 244, in get_mapping
    out = self.create_mapping(region, integral, integration)
  File "/home/fatune/source/sfepy/sfepy/discrete/fem/fields_base.py", line 1013, in create_mapping
    ori=self.ori, transform=transform)
  File "/home/fatune/source/sfepy/sfepy/discrete/fem/mappings.py", line 99, in get_mapping
    cmap.describe(self.coors, self.conn, bf_g, ebf_g, weights)
  File "sfepy/discrete/common/extmods/mappings.pyx", line 104, in sfepy.discrete.common.extmods.mappings.CMapping.describe
    raise ValueError('ccore error (see above)')
ValueError: ccore error (see above)

```

[triangular.zip](https://github.com/sfepy/sfepy/files/4137970/triangular.zip)

With some simple meshes this snipped works, but with this deformed mesh it fails. So it seems like the problem is in the mesh. Could you tell what exactly is wrong with the mesh?

**Comment by rc** [comment]
You can use `script/show_mesh_info.py` to obtain various geometrical and topological information about a mesh. For a single volume mesh, without holes (topologically euqivalent to a ball), you should get something like this:
```
python script/show_mesh_info.py meshes/3d/cylinder.mesh -d
sfepy: reading mesh [line2, tri3, quad4, tetra4, hexa8] (meshes/3d/cylinder.mesh)...
<snip>
sfepy: Euler characteristic: 1
sfepy: number of connected components: 1
sfepy: warning: mesh with topological dimension 2 lower than space dimension 3
sfepy: - element orientation not checked!
sfepy: surface Euler characteristic: 2
sfepy: surface genus: 0.0
sfepy: number of connected surface components: 1
```
- check the numbers of connected components and Euler characteristics for the volume (1 component, 1) and the surface (1 component, 2).

For your mesh, this gives:
```
sfepy: Euler characteristic: 169
sfepy: number of connected components: 1
sfepy: warning: mesh with topological dimension 2 lower than space dimension 3
sfepy: - element orientation not checked!
sfepy: surface Euler characteristic: 257
sfepy: surface genus: -127.5
sfepy: number of connected surface components: 10
```
so the mesh seems to be topologically wrong. How did you generate it? maybe start with a much smaller mesh, so that you could see what is wrong.

**Comment by mkondratyev85** [comment]
Thank you for the answer. I was creating my mesh using pyvista to perform set of iterative simple deformations on a rectangular grid. By using your advice I've found the step that introduce this error. So clearly that was an error in my method of preparation of the mesh.

**Comment by rc** [comment]
OK. BTW. I was not aware of pyvista. If would be useful if you could show us how you prepared the mesh with that package. I am considering reading meshes using meshio (see #460), and pyvista seems like another interesting package.

**Comment by mkondratyev85** [comment]
It is definitely worth looking. https://docs.pyvista.org/. They goal is to implement high-level API for VTK. Pyvista allows you to write very idiomatic, pythonic clean code to generate and work with meshes. It would be nice if it'll be possible to set boundary conditions and material properties for Sfepy in Pyvista. From the code snipped you've sent me via email it looks like it's just a matter of a few functions (if I understand this correctly). As far as I can see, Sfepy is a very flexible tool for FE in python, but the process of prepearing  a mesh (in my case, I work with highly deformed geological structures) is quite tedious. 

There is a page that list some external projects that use pyvista as well https://docs.pyvista.org/external_examples.html. 

I hope you'll find it useful.

**Comment by banesullivan** [comment]
> OK. BTW. I was not aware of pyvista. If would be useful if you could show us how you prepared the mesh with that package. I am considering reading meshes using meshio (see #460), and pyvista seems like another interesting package.

@rc, PyVista supports `meshio` under the hood for file IO with non-VTK formats.

> It would be nice if it'll be possible to set boundary conditions and material properties for Sfepy in Pyvista.

This sounds awesome 🚀, I think PyVista could be a great tool for mesh management, visualization, etc. in this software! And since PyVista already has an interface to `meshio`, it would bring all the file IO that you are looking for, @rc

**Comment by banesullivan** [comment]
From https://github.com/pyvista/pyvista-support/issues/117#issuecomment-581228589:

> Unfortunately right now sfepy reads only 2.0 vtk version.

Does sfepy have its own custom VTK file parser? If so, I'd highly recommend using an external library for VTK file IO. `meshio`, the VTK python bindings, PyVista, `pyvtk`, and `pyevtk` are all readily available for reading the latest VTK file formats and creating accessible data structures for all the points, geometry, and data.

**Comment by rc** [comment]
@banesullivan Yes, it has parsers for various formats, maintained on an as-needed basis. But see #460, I had meshio on my radar for some time. Thanks for chiming in!

**Comment by rc** [comment]
The latest release (2020.1) uses meshio for many formats (see #580) and there is a PR that adds pyvista based post-processing #582, so let us close this.

**Comment by banesullivan** [comment]
Awesome work! I'd love to see examples of the PyVista usage!
