### ISSUE TITLE
Updating sfepy.org pages to a more modern look

### ISSUE THREAD

**Issue by vlukes** [sfepy/sfepy#585]
I suggest to update sfepy.org web to a more modern look, e.g. [1]. What about a new SfePy logo?  If I remember, there were two pretty nice suggestions.

[1] http://sfepy.org/sfepy_examples/example_poropiezo/

**Comment by rc** [comment]
I am OK with the update (if I am not the one to do it ;)). As for the style, I tend to prefer a minimalistic  look (the sidebar in your example seems unnecessarily large). What about something more like the schemes at https://numpy.org or https://ipython.org?

For the reference, the logos were proposed in #303.

**Comment by rc** [comment]
#588 is merged, let's close this.
