### ISSUE TITLE
Question: Is it possible to easily apply unique material properties for each element?

### ISSUE THREAD

**Issue by VladAFlorea** [sfepy/sfepy#597]
I apologize in advance if this is the wrong place to ask or if this is a basic question (I'm new to SfePy). 

I'm looking to apply a unique Young's Modulus to each element in my mesh, however, I'm not sure how to achieve this in SfePy. Basically I want to take an array of Young's moduli, where the index is the element ID, and set the element properties accordingly.

For context, I'm solving 3D linear elastic problems and working on creating a Topology Optimization solver that uses SfePY for FEA.

**Comment by rc** [comment]
It is possible to define material parameters using a function of space and time, so you can, for example, have a different value in each quadrature point. See [1].

Essentially, define a function such as:
```
def get_pars(ts, coors, mode=None,
             equations=None, term=None, problem=None, **kwargs)
  # coors are coordinates of quadrature points in term.region.cells (for volume integral terms).
 ...
```

[1] http://sfepy.org/doc-devel/users_guide.html#functions

PS: You can ask either here, or using the [mailing list](https://mail.python.org/mailman3/lists/sfepy.python.org).

**Comment by VladAFlorea** [comment]
Thanks for your help Robert!

After messing around with it for a bit I was able to get it to work. I have a follow up question more so I understand going forward. The following worked for me:
```python
def get_pars(ts, coors, mode, **kwargs):

    if mode != 'qp': return

    val = nm.empty(coors.shape[0], dtype=nm.float64)
    val.fill(210000)
    val.reshape(coors.shape[0], 1, 1)

    return {'D': stiffness_from_youngpoisson(3, val, 0.3, plane='stress')}
```

Note that I am setting the points to the same value so I can verify the results. However, the following gives me error saying that "val" is called before it is defined even though the code makes it into the if statement:

```python
def get_pars(ts, coors='qp', mode, **kwargs):
    if mode == 'qp':
        val = nm.empty(coors.shape[0], dtype=nm.float64)
        val.fill(210000)
        val.reshape(coors.shape[0], 1, 1)
    return {'D': stiffness_from_youngpoisson(3, val, 0.3, plane='stress')}
```
This might be a simple aspect of Python I'm missing perhaps. Either way, the documentation has examples with both these syntax as well as a couple others. Some added clarification on setting up these functions would be nice. Thanks again!

**Comment by rc** [comment]
You need to put the return statement into the `if` block - it uses `val`.

**Comment by rc** [comment]
The question was answered, closing.

**Comment by lshxx** [comment]
> I apologize in advance if this is the wrong place to ask or if this is a basic question (I'm new to SfePy).
> 
> I'm looking to apply a unique Young's Modulus to each element in my mesh, however, I'm not sure how to achieve this in SfePy. Basically I want to take an array of Young's moduli, where the index is the element ID, and set the element properties accordingly.
> 
> For context, I'm solving 3D linear elastic problems and working on creating a Topology Optimization solver that uses SfePY for FEA.

Hello, I saw your question in the sfepy forum and found that you proposed setting different material parameters in different elements. Could you please give me an example for me to refer to? thank you very much!

**Comment by vlukes** [comment]
Material properties are set by a function e.g. in:

- [diffusion-laplace_1d](https://sfepy.org/doc-devel/examples/diffusion-laplace_1d.html), see function `get_coef()`
- [diffusion-darcy_flow_multicomp](https://sfepy.org/doc-devel/examples/diffusion-darcy_flow_multicomp.html), see function `mat_fun()`
- [linear_elasticity-linear_viscoelastic](https://sfepy.org/doc-devel/examples/linear_elasticity-linear_viscoelastic.html), function `get_th_pars()`
