### ISSUE TITLE
MeshioLibIO.read_data returns only cell data for `gmsh:ref`

### ISSUE THREAD

**Issue by zitkat** [sfepy/sfepy#601]
Hi, during my tinkering with I/O for gmsh  (https://github.com/sfepy/sfepy/pull/593) I encountered following issue: The `write` method of `MeshioLibIO` writes `node_groups` and `mat_id` as point and cell data, both with label `'%s:ref' % self.file_format`. When reading data using `read_data` the vertex data are then overwritten by cell data in `out` dictionary since both have the same labels used as keys.

**Comment by zitkat** [comment]
https://github.com/sfepy/sfepy/pull/603 seems to fix the issue. Note, however, that I'm not using the feature so I did only basic test.

**Comment by rc** [comment]
OK, thanks!
