### ISSUE TITLE
Integer overflow in matrix size check win64

### ISSUE THREAD

**Issue by zitkat** [sfepy/sfepy#610]
So I have been pushing the DG method a bit and got to huge matrices for implict problems and encountered an issue in Equations.create_graph() https://github.com/sfepy/sfepy/blob/02efa4595881910fc781daa8162d44e835c816a0/sfepy/discrete/equations.py#L466-L467
and 
https://github.com/sfepy/sfepy/blob/02efa4595881910fc781daa8162d44e835c816a0/sfepy/discrete/equations.py#L485-L486
When the matrix is large, say 65536 x 65536, which for DG corresponds to 64 x 64 mesh with 3rd order elements 16 DOFs each, which does not seem that excessively large to me, the int32 arithmetic used by numpy.prod overflows. This does not cause problems for smaller or larger (sic) matrices but 65536 x 65536 is exactly zero in 32-bit artithmetic and one gets `'no matrix (zero size)!'` message and subsequently error because the method does not return the matrix. 
Forcing int64 by 
```
nm.prod(shape, dtype=nm.int64)
```
would fix it.

**Comment by zitkat** [comment]
So I have done some further research and this seems to be win64 platform specific thing, where [long int still has only 32 bits](https://docs.microsoft.com/en-us/cpp/c-language/storage-of-basic-types?redirectedfrom=MSDN&view=vs-2019) (sigh). It might still be worth fixing.

**Comment by rc** [comment]
The winXX platforms never stop with surprises :). Thanks for the research!

Yes, it is worth fixing, PR welcome!

I do not really get why larger shapes work - do you mean that larger numbers are promoted to int64 before the operation, and 65536 is the only one that is not?

**Comment by zitkat** [comment]
Larger shapes result in negative values due to owerflow, hence they do not result in `'no matrix (zero size)!'`. They have negative fill, but I managed to miss it until I hit the magic number.

**Comment by rc** [comment]
Lucky catch!
