### ISSUE TITLE
Cylindrical coordinate question

### ISSUE THREAD

**Issue by Gavinlee960312** [sfepy/sfepy#630]
Hello,
I'm trying to solve the following equation in a cylindrical coordinate,
![image](https://user-images.githubusercontent.com/45217113/89339254-b4f77500-d652-11ea-8ddc-a308de127824.png),
Does anyone know how to build the equation in sfepy?

**Comment by rc** [comment]
Hi, sfepy does not have a built-in support for curvilinear coordinates.

**Comment by rc** [comment]
The question was answered, closing.
