### ISSUE TITLE
Application of sfepy in electrostatic field calculation

### ISSUE THREAD

**Issue by way101** [sfepy/sfepy#631]
Hello,
I'm trying to solve a simple electrostatic field problem with sfepy.
Does anyone know that sfepy can be used to calculate electrostatic field?

**Comment by rc** [comment]
Yes, you need to solve the Poisson's equation, check the [examples](http://sfepy.org/doc-devel/examples/diffusion-index.html).

**Comment by way101** [comment]
OK，thank you for your answer. Now I have encountered another  question, if I want to create a circulation region interactively, how can I write my code like the example bellow. I could not find any example in the _SfePy Documentation_. 

`In [8]: gamma1 = domain.create_region('Gamma1',
...: 'vertices in x < %.10f' % (min_x + eps),
...: 'facet')`

**Comment by rc** [comment]
The question was answered, closing.
