### ISSUE TITLE
Default python version causes problem if 2 is default

### ISSUE THREAD

**Issue by rupakbajgain** [sfepy/sfepy#632]
I tried to use sfepy in Ubuntu 20.04.1 LTS.
The updated instructions was whose hint was given in documentation to change python to python3 as
    `sudo apt-get install python3-scipy python3-matplotlib python3-tables python3-pyparsing libsuitesparse-dev python3-setuptools mayavi2 python3-dev ipython3 python3-sympy cython python3-sparse`

After this i tried running the sfepy but it didn't work for some reason it used python v2 since it was default , i mean if i use `python --version` i would get 2.
And running script would cause me problems since it checks for library within 2 which is not installed. I tried alias but it failed, this fixed the installation
<pre>sudo update-alternatives --list python
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
sudo update-alternatives --config python
python --version</pre>

I think the program should use `python3` as default command than `python` which may not require to change default.
Or, something should be changed in documentation.

And, It is working for me now,

**Comment by rc** [comment]
Thanks for mentioning that in 20.04.1 LTS it is possible to change the default python to python3. (Or you can create a python3 virtual environment, e.g. when using conda). The sfepy installation docs need updating now that sfepy is Python3 only.

**Comment by rupakbajgain** [comment]
@rc I will try to do it and create PR. And i think the #!/.../python should be changed to python3 too. Should i change that too?

**Comment by rc** [comment]
Thanks!

I am not sure if replacing `python` with `python3` everywhere in the docs is worth the effort. E.g. with anaconda3, which IMO most windows users use, `python` is python3 and everything works. What I meant was removing/replacing the old installation instructions [here](http://sfepy.org/doc-devel/installation.html#notes-on-installing-sfepy-dependencies-on-various-platforms) - those were not touched for a long time. Also I am not sure about the state of `python-sfepy` debian package.

As for the shebangs (#!/), I would like to have sfepy pip-installable, and use entry-points for the main scripts - that would solve the issue. Your proposal to update those to python3 is a good idea in the meantime, thanks.

**Comment by rupakbajgain** [comment]
@rc i think the problem was the `update-alternatives` was not defined, now i switched to 2 using  `update-alternatives` and the starting using `python3` for script now work.

**Comment by rupakbajgain** [comment]
i have closed issue since it is not related to sfepy.

**Comment by rupakbajgain** [comment]
I am not having that problem anymore maybe some other issue have caused that then.
