### ISSUE TITLE
Is there any way to introduce the elastoplastic constitution relationship?

### ISSUE THREAD

**Issue by fenfam** [sfepy/sfepy#644]
I have searched the document, but only found the Material function could work on it. However, the usually calculating of Material function merely works on predefined material parameters. In elastoplastic and other material consitutions, the deformation variables like stresses and strains are usually related to the stiffness matrix, could the material function access the aforementioned variables during computation?

**Comment by rc** [comment]
Yes, check [this example](http://sfepy.org/doc-devel/examples/linear_elasticity-material_nonlinearity.html).

**Comment by rc** [comment]
The question was answered, closing.
