### ISSUE TITLE
How to directly read all information in .inp file? 

### ISSUE THREAD

**Issue by Yuanzhi0202** [sfepy/sfepy#646]
Hi guys! I am trying to transfer my workflow from Abaqus to Sfepy. In Abaqus all information can be imported though its .inp file.
I can find that mesh information of .inp can be read in Sfepy but is there any way to directly read all and run a simulation based on that?

With kindest regards

**Comment by rc** [comment]
Hi, sfepy uses [meshio](https://github.com/nschloe/meshio) for mesh reading, and obtains only the mesh geometry (vertices, cells, and vertex and cell ids) information.

**Comment by rc** [comment]
The question was answered, closing.
