### ISSUE TITLE
How to define materials for different region in interaction mode?

### ISSUE THREAD

**Issue by Yuanzhi0202** [sfepy/sfepy#647]
Hi guys in documentation there is one way to define materials in different regions as below:
![image](https://user-images.githubusercontent.com/71324174/94636733-5a079480-0308-11eb-8738-7802e30f9bfb.png)
But how to do such thing in interaction mode?  like the format:
D = stiffness_from_youngpoisson(2, options.young, options.poisson)
asphalt = Material('Asphalt', D=D)

**Comment by rc** [comment]
Use simply:
```
mat = Material('mat', values={'D': {'Ym': stiffness_from_youngpoisson_mixed(dim, 7.0e9, 0.4), 'Yc': stiffness_from_youngpoisson_mixed(dim, 70.0e9, 0.2)}})
```

**Comment by Yuanzhi0202** [comment]
Thanks for that! I know this is one way to solve that problem easily, but what if I want to use the format like:
m = Material('m', D=stiffness_from_youngpoisson(dim, young mod, poisson)) ?
Because I have some special task like give the 'm' material thousands of properties for thousands regions

**Comment by rc** [comment]
Then it is better to use a [function](http://sfepy.org/doc-devel/users_guide.html#defining-material-parameters-by-functions) to define the material parameters, the full function signature (= how to access region and its cells) is [here](http://sfepy.org/doc-devel/users_guide.html#id9) (look for `get_pars()`).

Check [this example](http://sfepy.org/doc-devel/examples/diffusion-poisson_parallel_interactive.html).

**Comment by Yuanzhi0202** [comment]
thx for that! After finishing simulation running, due to I have added von-mise evaluation so i will see two figure (one for u and one for von mise), How can I see von_mise figure only in this vtk ?

**Comment by rc** [comment]
What do you use for the visualization? (Anyway, check the visualization tool command line options.)

**Comment by Yuanzhi0202** [comment]
I use view = viwer('filename.vtk') for visulization. The simulation include two variable u and v. After simple simulation I can see distribution of U in VTK. Then I use get_von_mises_stress function on pb.evaluate( 'ev_cauchy_stress...'). Then in vtk file I can see two scalar bar with their coordinate coutour map. 

What I want to do now is only show von-mise stress distribution in VTK because that is better for display. I did not see any example showed such result. How can I do that?

**Comment by rc** [comment]
You can use the `only_names` argument to the `view()` call - it takes a list of data names to display (see the bottom of [this example](http://sfepy.org/doc-devel/examples/linear_elasticity-modal_analysis.html)).

**Comment by Yuanzhi0202** [comment]
Thx! That really works. But now I have one more problem that how can I evaluate reactive force of one surface (I have create it as a region)? Whay I can find in examples is about point force but how can I do it for a surface? also I am runing the simulation in problem discription form.

**Comment by rc** [comment]
Check the force vector calculation in [the primer](http://sfepy.org/doc-devel/primer.html#running-sfepy-in-interactive-mode) - this gives you a reaction in each FE node, which you can select using a region's vertices (assuming the linear approximation and nodal basis). You can add the code into your postprocessing function. Otherwise there is no built-in support for getting the reactions.

**Comment by Yuanzhi0202** [comment]
Thx! I have read this and it help me a lot

**Comment by rc** [comment]
The question was answered, closing.
