### ISSUE TITLE
Execution Time Problem on 3D uniaxial compressive simulation

### ISSUE THREAD

**Issue by CRRMCF** [sfepy/sfepy#649]
Hi guys,

Currently, I am using Sfepy to simulate a 3D geometry model with a uniaxial displacement to find out the von Mises strength and the total execution time for the simulation is about __40 mins_ with 8G RAM_. Besides, 94% of the RAM is occupied when the program is running.
**I am not sure what is causing this execution time to take that long and what I could do to shorten the execution time.**
The geometry model was inputted from an Abaqus input-file with 5514 vertices and 4417 cells.
Also, I have checked the execution time line-by-line and found that the most time consumable step is defined as:
state = pb.solve(status=status)
In this case, I am supposing the solving process used most of the RAM and causing the timing issue.

Some of the problem descriptions have been defined as follow:

integral = Integral('i', order=3)
from sfepy.terms import Term

t1 = Term.new('dw_lin_elastic(m.D, v, u)',
              integral, Omega, m=m, v=v, u=u)

eq = Equation('balance', t1)
eqs = Equations([eq])

from sfepy.discrete.conditions import Conditions, EssentialBC

fix_u = EssentialBC('fix_u', inferior, {'u.all': 0.0})
shift_u = EssentialBC('shift_u',superior, {'u.0': -0.1})

from sfepy.base.base import IndexedStruct
from sfepy.solvers.ls import ScipyDirect
from sfepy.solvers.nls import Newton

ls = ScipyDirect({})
nls_status = IndexedStruct()
nls = Newton({}, lin_solver=ls, status=nls_status)

pb = Problem('elasticity', equations=eqs)
pb.set_bcs(ebcs=Conditions([fix_u, shift_u]))
pb.set_solver(nls)

status = IndexedStruct()
state = pb.solve(status=status)
output(nls_status)

**Comment by rc** [comment]
Hi, can you attach the mesh (+ complete minimal code), so that we can try your example?

**Comment by CRRMCF** [comment]
> Hi, can you attach the mesh (+ complete minimal code), so that we can try your example?

Yes, can I send you the mesh + code by email?

**Comment by rc** [comment]
Yes, you can use the [mailing list](https://mail.python.org/mailman3/lists/sfepy.python.org/). Or attach the files here.

**Comment by rc** [comment]
The question was answered, closing.
