### ISSUE TITLE
Undefined reference to inline function

### ISSUE THREAD

**Issue by stefanor** [sfepy/sfepy#651]
In Debian we've seen [a build failure](https://bugs.debian.org/972372) on 32bit platforms with GCC-10:

```
Extension error:
Could not import extension gen_term_table (exception: /<<PKGBUILDDIR>>/sfepy/discrete/common/extmods/cmesh.cpython-38-arm-linux-gnueabi.so: undefined symbol: _aux_hex)
make[3]: *** [Makefile:35: html] Error 2
```

Can trace that back to `mesh.o`, as one would expect:

```
$ readelf -s ./build/temp.linux-i686-3.8/sfepy/discrete/common/extmods/mesh.o | grep aux
   102: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND _aux_hex
```

Marking the private inline functions as `static inline` fixes the issue. Not sure why it only showed up on this function, maybe because it calls another inline function?

Here's a [good guide on inline behaviour in C99](https://www.greenend.org.uk/rjk/tech/inline.html). I think the best solution here is to be far more explicit with inlining. And replace all `inline` keywords with either `static inline` or `extern inline` as appropriate.

**Comment by rc** [comment]
Thank you for the report and the detailed issue analysis. Based on that, I have proposed a fix in #652. Let me know, if that is enough - I have followed the "simple portable model" from your link.

**Comment by stefanor** [comment]
Yeah, that's exactly the same thing I uploaded in Debian and it has built fine there.

* [my patch](https://salsa.debian.org/science-team/sfepy/-/blob/master/debian/patches/extern-inline.patch)
* [https://buildd.debian.org/status/package.php?p=sfepy](build logs)

I didn't forward that patch as-is, because it felt incomplete, any other inline function that isn't in a header could have the same thing happen to it. Maybe these are the only 3, I didn't audit any other files.

But it's certainly a step in the right direction, :+1:

**Comment by rc** [comment]
Yes, those are the only 3 that are not in a header. Remaining inline functions are all in `sfepy/discrete/common/extmods/mesh.[c,h]` or `sfepy/discrete/iga/extmods/nurbs.[c,h]`. Some are also in `_fmfield.pyx`, but that's Cython turf.

**Comment by rc** [comment]
I would like to resolve this, as it is unlikely that I get a better idea - shall I use your patch instead of #652? :)

**Comment by rc** [comment]
Merging!
