### ISSUE TITLE
Error during using semismooth newton solver

### ISSUE THREAD

**Issue by Yuanzhi0202** [sfepy/sfepy#655]
When I set nonlinear solver as nls.semismooth_newton I met errors as below:

  File "...\sfepy\script\simple.py", line 188, in <module>
    main()
  File "...\sfepy\script\simple.py", line 184, in main
    app()
  File "...\sfepy\applications\application.py", line 29, in call_basic
    return self.call(**kwargs)
  File "...\sfepy\applications\pde_solver_app.py", line 224, in call
    state = problem.solve(
  File "...\sfepy\discrete\problem.py", line 1431, in solve
    vec = tss(state0.get_vec(self.active_only),
  File "...\sfepy\solvers\ts_solvers.py", line 32, in _standard_ts_call
    result = call(self, vec0=vec0, nls=nls, init_fun=init_fun,
  File "...\sfepy\solvers\ts_solvers.py", line 73, in __call__
    vec = nls(vec0)
  File "...\sfepy\solvers\semismooth_newton.py", line 75, in __call__
    fun_smooth = get_default(fun_smooth, self.fun_smooth)
AttributeError: 'SemismoothNewton' object has no attribute 'fun_smooth'

 How to solve this?

**Comment by rc** [comment]
This solver needs some setup, have a look at `tests/test_semismooth_newton.py` and check [the solver docstring](http://sfepy.org/doc-devel/src/sfepy/solvers/semismooth_newton.html?highlight=semismoothnewton#sfepy.solvers.semismooth_newton.SemismoothNewton). Do you really need that?

**Comment by Yuanzhi0202** [comment]
Well actually the reason I want to use semismooth Newton is that the convergence of nls.newton is not good enough even I change iteration number and tolerance.

I want to use other nls solver so I choose this. Actually I have no mathematic understanding about semismooth.
Therefore, is there recommendation about nls solver if convergence of nls newton not good for the case? I want to use petsc as a trial but seems it not support windows.

**Comment by rc** [comment]
What kind of problem is that - can you attach the file?

**Comment by Yuanzhi0202** [comment]
It is a solid composite compresion problem but I use massive meshes and the convegence is not good espeacilly on surface force calculation

**Comment by Yuanzhi0202** [comment]
In other aspests I think would the problem caused by the euqation? I use linear elastic 

equations = {'balance_of_forces':
                 """dw_lin_elastic.i.Omega(m.D,v,u)
     = 0""",
             }

But in my case I have over ten thousands regions with independent material properties. It is an complicated composite 

For the situation now I use 

solvers = {'ls': ('ls.scipy_iterative', {'i_max': 5,
                                         'eps_a': 1e-10,
                                         'eps_r': 1e-10}),
           'nls': ('nls.newton', {
               'i_max': 5,
               'eps_a': 1e-10,
               'eps_r': 1e-10}), }

The terminal log showed the linear solver precision is low so it use nls.newton

Then problem come if I just use regions which have <ten thousands regions (like a lower resolution model) it will convegent to an constant after 5 or more iterations. If I use >ten thousands regions(like a higer resolution model) it will not convegent and the result was wrong when it compared with results in lower resolution case, the tolerance requirement (xxx<eps_r/eps_a) will not change in terminal log when I tried 10 iterations. It looks like the residual after many iterations still not change and connot be smaller than tolerance.

If my assumption of my composite to be linear elastic is right and I insist on using nls.newton how can I avoid the situation I described above for obtianing an satisfactory result?

**Comment by rc** [comment]
Ah, I see, so the problem is not in the nonlinear solver, but in the linear one. The max. number of iterations 'i_max': 5 in the linear solver is too small, try 100 or more. The newton solver iterations just restart the linear solver, so IMO it is worse than having more iterations in the linear solver. But I doubt this will help for the large problem - you will need a good preconditioner that takes into account the material heterogeneities.

I assume the problem is too large for a direct solver (MUMPS)?

**Comment by Yuanzhi0202** [comment]
I have tried set it into:

solvers = {'ls': ('ls.scipy_iterative', {'i_max': 100}),
           'nls': ('nls.newton', {}), }

sfepy: equation "balance_of_forces":
sfepy: dw_lin_elastic.i.Omega(m.D,v,u)
     = 0
sfepy: using solvers:
                ts: no ts
               nls: nls
                ls: ls
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.11 s
sfepy: matrix shape: (939832, 939832)
sfepy: assembling matrix graph...
sfepy: ...done in 33.56 s
sfepy: matrix structural nonzeros: 172019660 (1.95e-04% fill)
sfepy: updating variables...
sfepy: ...done
sfepy: updating materials...
sfepy:     m
sfepy: ...done in 231.35 s
sfepy: nls: iter: 0, residual: 1.156798e+05 (rel: 1.000000e+00)
sfepy:   residual:    0.69 [s]
sfepy:     matrix:   40.06 [s]
sfepy:      solve:   38.40 [s]
sfepy: warning: linear system solution precision is lower
sfepy: then the value set in solver options! (err = 8.023542e+02 < 1.000000e-10)
sfepy: nls: iter: 1, residual: 8.023542e+02 (rel: 6.935994e-03)

Seems there is no ls action ? Any suggestions?

**Comment by rc** [comment]
It seems to go in the right direction - the residual drops from 1e5 to 8e2. What happens when you set i_max to 1000?

**Comment by Yuanzhi0202** [comment]
seems it work!
sfepy: equation "balance_of_forces":
sfepy: dw_lin_elastic.i.Omega(m.D,v,u)
     = 0
sfepy: using solvers:
                ts: no ts
               nls: nls
                ls: ls
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.10 s
sfepy: matrix shape: (939832, 939832)
sfepy: assembling matrix graph...
sfepy: ...done in 28.69 s
sfepy: matrix structural nonzeros: 172019660 (1.95e-04% fill)
sfepy: updating variables...
sfepy: ...done
sfepy: updating materials...
sfepy:     m
sfepy: ...done in 156.89 s
sfepy: nls: iter: 0, residual: 1.156798e+05 (rel: 1.000000e+00)
sfepy:   residual:    0.56 [s]
sfepy:     matrix:   31.35 [s]
sfepy:      solve:  331.82 [s]
sfepy: warning: linear system solution precision is lower
sfepy: then the value set in solver options! (err = 6.732539e-01 < 1.000000e-10)
sfepy: nls: iter: 1, residual: 6.732539e-01 (rel: 5.819980e-06)

I can see both residual and rel become smaller but what is the difference is the rel means  relative residual?

**Comment by Yuanzhi0202** [comment]
I have checked the force results and it is very close to less regions case therefore this method works, thx!

Also I found that the viewer in sfepy cannot see 3d inside content or cut plane. If there any such option for viewer or I need to find other viewing package for 3d content inside view(the vtk file result)?

**Comment by rc** [comment]
Yes, it is the relative residual - as you can see, in the iteration 0, its value is 1. So it does seem to work, but as I said, you would need preconditioning to reduce the number of iterations/computational time required.

**Comment by Yuanzhi0202** [comment]
Thanks, but how to set the precondition, is there any example in sfepy documentation?

**Comment by rc** [comment]
Maybe install and try [PyAMG](https://github.com/pyamg/pyamg), if you cannot use PETSc. You can also setup a preconditioner for the scipy solvers, but it is more complicated (see examples/multi_physics/biot_short_syntax.py).

Ad the visualization - check the postproc.py options, especially
```
  --3d                  3d plot mode
  --scalar-mode mode    mode for plotting scalars with --3d, one of:
                        cut_plane, iso_surface, both [default: iso_surface]
  --vector-mode mode    mode for plotting vectors, one of: arrows, norm,
                        arrows_norm, warp_norm [default: arrows_norm]
```
Or load the file into paraview or mayavi and apply some filters manually.

**Comment by Yuanzhi0202** [comment]
Thx for these information

**Comment by Yuanzhi0202** [comment]
Hi Robert! Now we are working with a fluid simulation with a 3D bone model. By implement the Darcy's Law, we  wish to have the velocity as the final output of the simulation to find out the distribution inside the bone. We have followed the diffusion/darcy_flow_multicomp.py in the manual but the output is not what we need. you please give me more details about that example? If that example actually have no good relationship with what I want to do could you give me a more suitable example for help me build model about fluids insertion velocity field in composites?
