### ISSUE TITLE
Error with python for Windows 32 bit

### ISSUE THREAD

**Issue by RFdyoun** [sfepy/sfepy#657]
My code with SFEPY was completely okay when I used python 3.7 for Windows 64 bit, but I had to switch the python version to python 3.7 for Windows 32 bit due to a compatibility issue. After using the other version of python, however, I start to get errors like below.

File "D:/Cache/tem/GUI_FE/analysis12.py", line 351 in <module>
  call_SFEPY()
File "D:/Cache/tem/GUI_FE/analysis12.py", line 5 in call_SFEPY
  from sfepy.discrete import Problem
File "D:\Cache\tem\GUI_FE\sfepy\discrete\__init__.py", line 9, in <module>
  from .variables import Variables, Variable, FieldVariable, create_adof_conns
File "D:\Cache\tem\GUI_FE\sfepy\discrete\variables.py", line 21, in <module>
  from sfepy.discrete.fem.lcbc_operators import LCBCOperators
File "D:\Cache\tem\GUI_FE\sfepy\discrete\fem\__init__.py", line 11, in <module>
  from .fields_base import Field
File "D:\Cache\tem\GUI_FE\sfepy\discrete\fem\fields_base.py", line 25, in <module>
  from sfepy.discrete.fem.mappings import VolumMapping, SurfaceMapping
File "D:\Cache\tem\GUI_FE\sfepy\discrete\fem\mappings.py", line 8, in <module>
  from sfepy.discrete.common.extmods.mappings import CMapping
ModuleNotFoundError: No module named 'safety.discrete.common.extends.mappings'

Is SFEPY not compatible for Windows 32 bit environment? What would be the best solution for me to apply for my code?

**Comment by rc** [comment]
Did you rebuild the extension modules? (How did you install sfepy?)

**Comment by RFdyoun** [comment]
The general platform is PyCharm, and I basically followed the first instruction on SFEPY homepage like:
1) conda config --add channels conda-forge;
2)conda install sfepy:

I did not rebuild the extension modules, I guess. Can I get any guidance about this?

**Comment by rc** [comment]
I was asking because it seemed that you used a 64-bit conda package of sfepy with a 32-bit python. Did you reinstall the whole anaconda (32 bit version)? The last version of sfepy that had 32-bit conda packages was IIRC 2018.1.

**Comment by RFdyoun** [comment]
No, I didn't install anaconda 32 bit version. What you've guessed is right. I keep using the a version with python 3 on 64-bit Windows without reinstall the whole package. I will reinstall a 32-bit version and try the same and keep you updated on how it goes. Thank you.
