### ISSUE TITLE
Mesh from FreeFEM++ to sfepy

### ISSUE THREAD

**Issue by Silvia-Sciva** [sfepy/sfepy#667]
Hi SfePy community,
I have always used FreeFEM, but now I have to implement the Calderon Problem in python, so I decided to use Sfepy. I tried to use Mesh.from_file where Mesh is imported by sfepy.discrete.fem. I saved my mesh (created with FreeFEM) in a file Th0.mesh, but there is something written in my file that sfepy doesn't know. If I open the file Th0.mesh, there are words, for example "IIdentifier" or "Geometry", that are not known by sfepy. I tried to remove those words and the words they refer to, but the problem moves from the function Mesh.from_file to the function FEDomain (in the following line of the code).
To resume my problem is to use a FreeFEM mesh as sfepy mesh. I write below my FreeFEM file, my mesh and my python file.
Ps: Does anyone know if my problem (div(a*grad(u)) = 0, where a is a function) is already implemented in sfepy? 
Thank you very much.
Silvia 

file: mesh_rettangolo.edp

border lato1(t=0,1){ x=1-t; y=0;label=1;} 
border lato2(t=0,1){ x=0; y=t;label=2;} 
border lato3(t=0,1){ x=t; y=1;label=3;} 
border lato4(t=0,1){ x=1; y=1-t;label=4;}
int n = 30;
mesh Th0 = buildmesh(lato2(-n)+lato3(-n)+lato4(-n)+lato1(-n));
plot(Th0,wait=1);
savemesh(Th0,"/home/silvias/Desktop/Th0.mesh");

file: calderon_problem.py

import numpy as nm
from sfepy.discrete.fem import Mesh, FEDomain, Field

mesh = Mesh.from_file('/home/silvias/Desktop/Th0.mesh')
domain = FEDomain('domain', mesh)

file: Th0.mesh (It is not complete: see when there are ".........")

MeshVersionFormatted 1

Dimension
2

Identifier
";2, Date: 21/01/22 15:17 30s"

Geometry
"/home/silvias/Desktop/Th0.mesh.gmsh"

Vertices
1133
1 0 1
0.966666666667 0 1
1 0.0333333333333 4
.......

Edges
120
2 1 1
4 2 1
.......

SubDomainFromMesh
1
3 1 1 0

SubDomainFromGeom
1
2 1 1 0

VertexOnGeometricVertex
120
 1 1
 2 2
 3 3
 4 4
 7 5
 .......

VertexOnGeometricEdge
0

EdgeOnGeometricEdge
120
1 1
2 2
3 3
4 4
........

End

**Comment by Silvia-Sciva** [comment]
Solved

**Comment by rc** [comment]
Hi, thanks for the report. How did you solve the issue? [Meshio](https://github.com/nschloe/meshio) is used under the hood to read meshes, so maybe it needs an update...

**Comment by Silvia-Sciva** [comment]
The problem is that on my file Th0.mesh there were more things written than
necessary. I saw that sfepy requires only the dimension of the space of the
domain, the coordinates of the vertices and the triangles, but FreeFem
saves also other characteristics of the mesh. So I remove the unnecessary
characteristics from my Th0.mesh file.
Thanks for your interest
Silvia

Il giorno ven 22 gen 2021 alle ore 18:06 Robert Cimrman <
notifications@github.com> ha scritto:

**Comment by rc** [comment]
OK, thanks! Let us close this issue then, but feel free to reopen it/ask more.

One more thing: I do not know what other formats are supported by FreeFEM++ - maybe some other might work without the manual editing?

**Comment by Silvia-Sciva** [comment]
I have tried formats as ".ols" and ".stl", but sfepy doesn't know those
formats, so I decided to modify my mesh manually

Il giorno ven 22 gen 2021 alle ore 19:28 Robert Cimrman <
notifications@github.com> ha scritto:

**Comment by rc** [comment]
OK, thanks!
