### ISSUE TITLE
Two Material Modal Analysis

### ISSUE THREAD

**Issue by lbeardslee1963** [sfepy/sfepy#674]
Hi sfepy,

I am trying to conduct modal analysis on a two material build up. I have modified the modal analysis example to fit my needs and have it working well for a single material. At the moment I am importing a file from Gmsh and using that as the model, ultimately I would like to define two regions in Gmsh and assign a different material property to each. I have looked through several examples and have found where to define the different materials, but I have not figured out how to define the different regions of the mesh so that I can assign the materials to them. Once I can figure this out the next question is how do I include the two materials in a single mass and stiffness matrix. Any help would be much appreciated!

**Comment by rc** [comment]
Hi Luke,

there is a [tutorial](http://sfepy.org/doc/preprocessing.html) (section Multipart models) written by @vlukes that shows how to define subdomains using freecad/openscad and gmsh. This [manual section](http://sfepy.org/doc/users_guide.html#materials) shows how to easily define material parameters that are constant per subdomain.

**Comment by lbeardslee1963** [comment]
Okay, I have read through the tutorials and understand how to define the two regions/subdomains, but how do I add those regions to my mesh so that I can define a material property for each? I have pasted what I think is the key piece of code below, I am assuming I need to create two regions, one for group 1, and group 2, then define two materials one for each region. Then how do I add these to the two terms defining the mass and stiffness matrix? 

omega = domain.create_region('Omega', 'all')

    field = Field.from_args('fu', np.float64, 'vector', omega,
                            approx_order=order)

    u = FieldVariable('u', 'unknown', field)
    v = FieldVariable('v', 'test', field, primary_var_name='u')

    mtx_d = stiffness_from_youngpoisson(dim, young, poisson)
    m = Material('m', D=mtx_d, rho=density)
    integral = Integral('i', order=2*order)

    t1 = Term.new('dw_lin_elastic(m.D, v, u)', integral, omega, m=m, v=v, u=u)
    t2 = Term.new('dw_volume_dot(m.rho, v, u)', integral, omega, m=m, v=v, u=u)
    eq1 = Equation('stiffness', t1)
    eq2 = Equation('mass', t2)
    lhs_eqs = Equations([eq1, eq2])

**Comment by rc** [comment]
Let's say you define two regions Omega1, Omega2. Then try something like:
```
mat = Material('m', values={'Omega1' : {'rho' : 1, 'D' : ...}, 'Omega2' : {'rho' : 2, 'D', ...}})
```

**Comment by rc** [comment]
It seems to me that you mix the declarative and imperative ways of region definitions. In the imperative style that you use, you can simply define 
```
t11 = Term.new('dw_lin_elastic(m.D, v, u)', integral, omega1, m=m, v=v, u=u)
t12 = Term.new('dw_lin_elastic(m.D, v, u)', integral, omega2, m=m, v=v, u=u)
eq1 = Equation('stiffness', t11 + t12)
```
etc. Or IMO(*) you can use the whole domain region omega in the terms (as you do), while defining the material parameters using omega1, omega2.

(*) If it does not work, let us know.

**Comment by lbeardslee1963** [comment]
Okay, so I started by trying to use your suggestions which seems like a much cleaner approach to the problem. I set it up like this:
`dim = 3
mtx_d = stiffness_from_youngpoisson(dim, 68e9, .36)
mtx_d1 = stiffness_from_youngpoisson(dim, 75e9, .3)
m = Material('m', values={'omega1': {'rho': rho, 'D': mtx_d}, 'omega2': {'rho': 6000, 'D': mtx_d1}})`

**Comment by rc** [comment]
Sorry, I gave you wrong advice: the material definition should be:
```
m = Material('m', values={'rho': {'omega1': 2700, 'omega2': 6000}, 'D': {'omega1': mtx_d, 'omega2': mtx_d1}})
```
-> a "transposition" of what I wrote.

As for the zeros, what are your boundary conditions?

**Comment by lbeardslee1963** [comment]
Ah ha, that works great. I still get 12 zeros, I am using free boundary conditions, so I would expect there to be 6. I think that maybe its the way I have defined the mesh. I defined two regions in Gmsh, but I think its treating them as two free bodies and not creating a common boundary between them. Would this be possible?

**Comment by rc** [comment]
Yes, that might be the case. You can use `script/show_mesh_info.py -d <your mesh file>` to see the number of mesh components and/or connect the components (provided their vertices coincide) using `script/convert_mesh.py -m <mesh-in> <mesh-out>`.

**Comment by lbeardslee1963** [comment]
Hi, sorry for taking so long to get back. This solved my issues! I just had to use the convert mesh. Thank you for all your help.

**Comment by rc** [comment]
Thanks for letting us know! Closing...
