### ISSUE TITLE
Maximum Approx_order 

### ISSUE THREAD

**Issue by ThomasShairifi** [sfepy/sfepy#723]
Hi,
I would like to know the maximum approx_order than we can set for our field. In the manual it is said that 2 is the maximum. No high order is available for FE interpolation ? 
Thank you

fields = {
<name> : (<data_type>, <shape>, <region_name>, <approx_order>)
}

**Comment by rc** [comment]
Can you point to the docs, where this is mentioned? The information is obsolete, the orders are mostly limited by the available memory - the orders higher than 3 are very memory-hungry, see [1].

[1] https://doi.org/10.1016/j.advengsoft.2021.103033 (preprint: https://arxiv.org/abs/2107.04121)

**Comment by ThomasShairifi** [comment]
Thank you for your answer, 
I was asked to compare high order and refinement. I would like to try order 3 or 4 or higher.

it is written page 37 : 

**Fields**
Fields correspond to FE spaces:
fields = {<name> : (<data_type>, <shape>, <region_name>, <approx_order>)}
where
• <data_type> is a numpy type (float64 or complex128) or ‘real’ or ‘complex’
• <shape> is the number of DOFs per node: 1 or (1,) or ‘scalar’, space dimension (2, or (2,) or 3 or (3,)) or
‘vector’; it can be other positive integer than just 1, 2, or 3
• <region_name> is the name of region where the field is defined
• <approx_order> is the FE approximation order, e.g. 0, 1, 2, ‘1B’ (1 with bubble)

Example: scalar P1 elements in 2D on a region Omega:
fields = {'temperature' : ('real', 1, 'Omega', 1),}
The following approximation orders can be used:
• simplex elements: 1, 2, ‘1B’, ‘2B’
• tensor product elements: 0, 1, ‘1B’
Optional bubble function enrichment is marked by ‘B’.

**Comment by rc** [comment]
Orders 3, 4 or even 5 should be OK, depending on your mesh size (the approximate memory requirements can be seen in the article linked above).

Thanks for pointing to the docs. The text does not forbid orders greater than 2 but neither it tells anything about allowed orders -> it should be updated.

**Comment by rc** [comment]
Closing answered questions with no further reaction...
