### ISSUE TITLE
Question: How to create Problem Domain/Mesh and Regions from mesh data in numpy arrays?

### ISSUE THREAD

**Issue by burnpanck** [sfepy/sfepy#731]
I have custom code which generates a thetrahedral mesh for my problem, consisting of a small number of distinct materials, and includes both essential and natural boundary condition. The material parameters applicable for each cell are specified as one out of a small number of parameter sets corresponding to the material type.
 1. Instantiate a `Mesh` from vertex coordinates and cell-vertex association. I presume that this can be achieved using `Mesh.from_data(name, coors, ngroups, conns, mat_ids, descs)`, however, I'm not clear how exactly the arguments need to be prepared.
 2. Assign the material parameters to the corresponding cells. One can probably achieve that by creating a separate named region for each material, and then assign the material parameters to each named region. How would I create a named region defined by a set of cells (i.e. their index in the spec array)? Potentially something like `Region.from_cells(cells, domain, ...)` - but what exactly is the `cells` parameter?

For the discussion's sake, let's assume the following numpy arrays exist:
```
vertices = ... # float array of shape (Nvert,3); the coordinates of the vertices
cells = ... # int array of shape (Ncell,4) in the range [0..Nvert); the indices of the vertices forming all cells of the domain
cell_material = ... # int array of shape (Ncell,) in the range [0,Nmat); which of the Nmat materials each cell contains
material_D = ... # float array of shape (Nmat,); the material parameter of each material
facets = ... # int array of shape (Nfac,3) in the range [0..Nvert); the indices of the vertices forming all cell facets of the domain
nbc_idx = ... # int array of shape (Nnbc,) in the range [0..Nfac); the indices of the subset of facets forming natural boundary conditions
nbc_flux = ... # float array of shape (Nnbc,); the normal fluxes across the facets forming natural boundary conditions
ebc_idx = ... # int array of shape (Nebc,) in the range [0..Nvert); the indices of the subset of vertices forming essential boundary conditions
ebc_values = ... # float array of shape (Nebc,); the solution values at the vertices forming essential boundary conditions
```

These parameters should be enough to describe the 1st-order FEM discretisiation of the problem .
Given those parameters, how can I construct suitable calls to `Mesh.from_data(...)` and `Region.from_cells(...)` to get a SfePy-compatible first-order description ?

This would allow me to do custom geometry optimisation through a fully programmatic way of generating the problem specification including the geometry/meshes.

_Alternative: Instead of multiple named regions each assigned a constant material `D`, it might be easier to create a single material with a `D` which is a piecewise constant function of space specified for each cell, e.g. using the numpy expression `material_D[cell_material]`, a `(Ncell,)`-shaped float array._

**Comment by lshxx** [comment]
> 再次感谢，我相信我现在拥有我需要的所有信息。

Hello, I saw your question in the sfepy forum and found that you proposed setting different material parameters in different elements. Could you please give me an example for me to refer to? thank you very much!
