### ISSUE TITLE
What python versions are expected to be supported exactly?

### ISSUE THREAD

**Issue by burnpanck** [sfepy/sfepy#736]
The documentation states `sfepy` should work with "python 3.x". However, the CI only tests python 3.7. The source-code is still full of uses of `six`, from times when python 2 was still a thing. In order to let contributors help advance SfePy, it's important to know modernisation schedule the maintainers would like to target. For example, at my company, we have a policy where we do not intentionally refactor old code just because older versions have stopped being supported, but do that kind of refactoring when we touch a piece of code for other reasons. This allows us to choose a modernisation schedule where we do not have to hold back just because the sudden availability of a cool feature would require us to refactor everything. However, it means that when touching code, you may not necessarily tell from the presence of previous code what the current preferred style of writing is.

In my specific case, I was trying to improve the documentation of the `Materials` class, found a small inconsistency, and was heading to improve that. Things that I would do along the way depending on the minimum supported version would be:
 - use [f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings) to format messages (python 3.6)
 - add [type annotations](https://docs.python.org/3/library/typing.html) as a form of documentation (python 3.5)

**Comment by rc** [comment]
Closing old issues with no further reaction...
