### ISSUE TITLE
unable to convert 2d mesh made with gmsh

### ISSUE THREAD

**Issue by flothesof** [sfepy/sfepy#743]
Hi,

I am trying to model a 2D problem using GMSH. The mesh is bounded by a rectangle and in the shape of a car.
![image](https://user-images.githubusercontent.com/2360669/141091333-2e4a7b18-4f29-490a-be8a-caf596342424.png)
To use it within my 2D model, I first convert it following the instructions in the documentation.
```python ..\sfepy\script\convert_mesh.py --2d citroen.msh citroen.h5```
However, the conversion script fails with an error:
```python_traceback
sfepy: reading mesh (citroen.msh)...
Traceback (most recent call last):
  File "..\sfepy\script\convert_mesh.py", line 237, in <module>
    main()
  File "..\sfepy\script\convert_mesh.py", line 162, in main
    mesh = Mesh.from_file(filename_in)
  File "c:\users\fl232714\documents\python workspace\scripts\2020_sfepy\sfepy\sfepy
\discrete\fem\mesh.py", line 220, in from_file
    mesh = io.read(mesh, omit_facets=omit_facets)
  File "c:\users\fl232714\documents\python workspace\scripts\2020_sfepy\sfepy\sfepy
\discrete\fem\meshio.py", line 393, in read
    cgdata0[m.cell_sets[k][ic]] = cgrps[ik]
IndexError: index 30 is out of bounds for axis 0 with size 1
```
I’ve attached a debugger to the file and tried to understand why this happens.
```python
            for ic, c in enumerate(m.cells): #iterate over cells
                cgdata0 = nm.zeros((len(c.data),), dtype=nm.int32)
                for ik, k in enumerate(keys):
                    cgdata0[m.cell_sets[k][ic]] = cgrps[ik] # this fails since the index is not valid for cgdata0
                cgdata.append(cgdata0)
```
It turns out that `m.cell_sets[k][ic]` is a 2d numpy array in certain cases which leads to this bug:
```
m.cell_sets[k][ic]    
Out[2]: array([30, -5], dtype=int32)
```
Do you have any ideas why this is so and what I can do to prevent that? I’m guessing that I somehow have wrongly defined things in my script, but what?

Cheers,
Florian
Attached: .geo and .msh in archive
[car.zip](https://github.com/sfepy/sfepy/files/7511731/car.zip)

**Comment by flothesof** [comment]
An even simpler example that throws the same type of error is that of a square in a square:
![image](https://user-images.githubusercontent.com/2360669/141099958-0051fb0f-d1c7-4f19-886d-e2246cce0cf2.png)
```
Point(1) = {-1, -1, 0, 1.0};
Point(2) = {1, -1, 0, 1.0};
Point(3) = {1, 1, 0, 1.0};
Point(4) = {-1, 1, 0, 1.0};
Point(5) = {-0.5, 0.5, 0, 1.0};
Point(6) = {-0.5, -0.5, 0, 1.0};
Point(7) = {0.5, -0.5, 0, 1.0};
Point(8) = {0.5, 0.5, 0, 1.0};

Line(5) = {1, 2};
Line(6) = {2, 3};
Line(7) = {3, 4};
Line(8) = {4, 1};


Line(1) = {6, 7};
Line(2) = {7, 8};
Line(3) = {8, 5};
Line(4) = {5, 6};

Line Loop(1) = {8, 5, 6, 7};
Line Loop(50) = {4, 1, 2, 3};

Plane Surface(1) = {1, 50};
```

I’m a bit confused because a script that DOESN’T make an error is based on a file that you gave on the GMSH example page but that is conceptually the same (https://sfepy.org/doc-devel/preprocessing.html):
![image](https://user-images.githubusercontent.com/2360669/141100368-43846375-3dfc-4fe2-bb73-e6ece335199d.png)

```
a = 0.5;
r = 0.3;
out = 0.03;
in = 0.03;
Point(1) = {-a,-a,0, out};
Point(2) = {-a,a,0, out};
Point(3) = {a, a,0, out};
Point(4) = {a,-a,0, out};
Point(5) = {0, 0, 0, in};
Point(6) = {r, 0, 0, in};
Point(7) = {0, r, 0, in};
Point(8) = {-r, 0, 0, in};
Point(9) = {0, -r, 0, in};
Line(1) = {1,4};
Line(2) = {4,3};
Line(3) = {3,2};
Line(4) = {2,1};


Circle(5) = {6,5,7};
Circle(6) = {7,5,8};
Circle(7) = {8,5,9};
Circle(8) = {9,5,6};
Line Loop(5) = {2,3,4,1};
Line Loop(50) = {5,6,7,8};

Plane Surface(1) = {5, 50};
```

**Comment by vlukes** [comment]
Hi Florian,

the problem is in the msh4.1 format. If you use msh22

	gmsh -2 citroen.geo -o citroen.msh -format msh22

then it works.

Regards
Vladimir

**Comment by vlukes** [comment]
Hi again,

the `msh4` format also works well, but you must add `Physical Surface(1) = {1};` to your geo file.

Regards
Vladimir

**Comment by flothesof** [comment]
Hello Vladimir,

thank you very much for your answer.
This solves my problem.
@rc Is there any interest that I contribute my example to the gallery? (solve for scalar potential with incompressibility constraint)

Cheers,
Florian

**Comment by rc** [comment]
Yes, @flothesof, that would be great! It would be nice to have an example with a mesh different from the mostly boring ones we have currently.

In case you decide to contribute it: The first paragraph in an example's docstring is the text displayed in the gallery captions, so do not make it too long :) Then the docstring describes the problem solved, the equations and usage examples, in case there are options, see e.g. [this example](https://sfepy.org/doc-devel/examples/navier_stokes-stokes_slip_bc.html#navier-stokes-stokes-slip-bc). Yours might include also the meshing information.
