### ISSUE TITLE
"linear system solution precision is lower than the value set in solver options!" - how to avoid?

### ISSUE THREAD

**Issue by burnpanck** [sfepy/sfepy#745]
I have a linear multi-material problem (simple heat-transfer) with a non-uniformly sized tetragonal mesh of the order of 4e5 to 4e6 cells and 5e4 to 7e5 vertices (depending on the meshing parameters). I solve the problem using `Newton(dict(is_linear=True), lin_solver=ls)` and am now looking to select and tune the underlying linear solver `ls`. All solvers I tried (`ScipyDirect`, `ScipyIterative`, `PETScKrylovSolver` and `PyAMGSolver`) end up with the aforementioned warning:
```
Linear system solution precision is lower than the value set in solver options!
```
The residuals vary between no improvement at all to about 5e-2 of the initial residuals. Depending on the solver, the result is furthermore anywhere between obviously wrong and ok at first sight. The underlying problem has a C2 symmetry that is not enforced during meshing or solving, and even with the better solvers that symmetry is significantly violated in the result.

The computation time for that problem is still acceptable, so I'd be willing to trade mode computation for a more accurate result. However, lowering the tolerance doesn't help, because the all the solvers seem to stop for another reason that isn't clear to me. Could it be roundoff error due to an ill-conditioned problem (there is almost three orders of magnitude difference in the thermal conductivity across the domain)? How do I select a suitable pre-conditioner? How do I find out why the solvers are stopping in the first place despite not converging on the requested tolerance?

**Comment by rc** [comment]
Having the residual so large even for direct solvers indicates some problem with the matrix - it might be singular due to insufficiently fixed rigid body modes? The three orders of magnitude difference in the thermal conductivity is IMO not enough to warrant such behavior - try a test run with a homogeneous conductivity value.

**Comment by burnpanck** [comment]
Thanks, that might have been it. I had forgotten to turn on mesh-optimisation, so there must have been slivers in the mesh.

**Comment by rc** [comment]
Closing as answered.
