### ISSUE TITLE
`gen_mesh_from_geom` does not work

### ISSUE THREAD

**Issue by WhymustIhaveaname** [sfepy/sfepy#771]
Now I am trying to generate my own mesh. I use the following code to get a simple 2d square.
![image](https://user-images.githubusercontent.com/38423345/150524887-2f580a80-6ec4-4be2-9728-cfd75a5e2860.png)

Then I fed this geometry object to `gen_mesh_from_geom(geo)`
```
mesh_generators.gen_mesh_from_geom(sample,verbose=True)
```
And got the following error
```
/usr/lib/python3/dist-packages/pexpect/pty_spawn.py in _spawn(self, command, args, preexec_fn, dimensions)
    273         command_with_path = which(self.command, env=self.env)
    274         if command_with_path is None:
--> 275             raise ExceptionPexpect('The command was not found or was not ' +
    276                     'executable: %s.' % self.command)
    277         self.command = command_with_path
ExceptionPexpect: The command was not found or was not executable: triangle.
```

Maybe I misunderstand what is a `geom`. But I cannot find any example all over the internet. I also read the source code. SfePy tries to call a command `triangle -ACpV` in the terminal which I never installed.

**Comment by rc** [comment]
The code tries to call an external tool triangle: https://www.cs.cmu.edu/~quake/triangle.html, https://github.com/PhilipLudington/Triangle - you need to have that installed. Note that `mesh_generators.gen_mesh_from_geom()` was not touched a long time, it might be better for you to use gmsh which is being actively developed. See also https://sfepy.org/doc-devel/preprocessing.html.

**Comment by rc** [comment]
FYI: https://github.com/nschloe/pygmsh

**Comment by WhymustIhaveaname** [comment]
Thanks! I tried `pygmsh` that day. But it can only do triangle meshes, while I want to try quadrilateral elements that day. I guess gmsh has a quadrilateral function but pygmsh does not adapt. So maybe I will need to use gmsh directly in a terminal eventually. However, these did not bother me because I exported a mesh from Blender and finished my work ([here](https://github.com/WhymustIhaveaname/FEMdemo/blob/main/Part2.ipynb)). Thank you for your attention!

**Comment by WhymustIhaveaname** [comment]
I succeeded to use gmsh! It is __surprisingly easy to install__. Just `sudo dnf install gmsh` (or `apt` on Ubuntu) and it is done! The GUI is a bit counterintuitive but its command line parameters are easy to use. So I draw the geometry using GUI and mesh using the command line.
```
$ gmsh stick.geo -3 -format vtk -clmax 0.04 -o stick_clmax.04.vtk
Info    : Running 'gmsh stick.geo -3 -format vtk -clmax 0.04 -o stick_clmax.04.vtk' [Gmsh 4.6.0, 1 node, max. 1 thread]
...
Info    : Done optimizing mesh (Wall 0.00223017s, CPU 0.002226s)
Info    : 1155 nodes 4499 elements
Info    : Writing 'stick_clmax.04.vtk'...
Info    : Done writing 'stick_clmax.04.vtk'
Info    : Stopped on Sun Jan 30 12:46:28 2022 (From start: Wall 0.0817471s, CPU 0.129114s)
```
where the `stick.geo` is
```
$ cat stick.geo
// Gmsh project created on Sun Jan 30 11:36:10 2022
//+
SetFactory("OpenCASCADE");
Circle(1) = {0, 0, 0, 0.1, 0, 2*Pi};
//+
Curve Loop(1) = {1};
//+
Surface(1) = {1};
//+
Extrude {0, 0, 1} {
  Surface{1}; Curve{1}; 
}
```
![image](https://user-images.githubusercontent.com/38423345/151687007-8b88e3fb-0b67-4eba-b1b7-08a66a47cff7.png)

**Comment by WhymustIhaveaname** [comment]
No, gmsh will give very close points. And its docs are nothing! Please keep away from gmsh! It is a waste of time!
