### ISSUE TITLE
Simplification of term table?

### ISSUE THREAD

**Issue by vlukes** [sfepy/sfepy#773]
It seems to me that the term table is too complicated.

I think it is unnecessary to have separated integrals for `virtual, state` and `parametr_1, parametr_2` in the table.
If we write that `v`, `s`, ...  "_are test or parameter function_" description of many terms can be simplified without losing information.

**Example** - `dw_div_grad` term: there could be just two integrals in the definition,  with and without material parameter, and 

  `opt_material`,  `virtual/parameter_1`, `state/parameter_2`

in the column for arguments.

**Comment by rc** [comment]
True, most new terms  (e.g. multilinear ones) allow different kinds of variables, so the distinction is no longer necessary.
