### ISSUE TITLE
Get displacement of a node in a certain location?

### ISSUE THREAD

**Issue by lucascbarbosa** [sfepy/sfepy#778]
I'm trying to get the displacement vector of a node in a certain coordinate(top of the geometry in the y direction). Is there a way to get its index the u matrix? Like with another matrix that has the coordinates of all nodes?

**Comment by rc** [comment]
Check `field.get_dofs_in_region()` in `post_process()` [here](https://sfepy.org/doc-devel/examples/linear_elasticity-nodal_lcbcs.html).

**Comment by rc** [comment]
Closing answered questions with no further reaction...
