### ISSUE TITLE
Multilinear terms - cached values

### ISSUE THREAD

**Issue by vlukes** [sfepy/sfepy#782]
The [attached](https://github.com/sfepy/sfepy/files/8117696/test_multilinear.zip) script shows the problem in multilinear terms.

There is the following equation:

`dw_diffusion.i.Omega(solid.K, q, p)  = de_sd_diffusion.i.Omega(solid.K, q, p, V)`

which has the sensitivity term `de_sd_diffusion` on the right hand side. The design velocity field `V` is changing in the defined parametric hook, but there is no change in the calculated value `p`!

**Comment by rc** [comment]
Can you try adding `self.einfos = {}` prior to calling `self.make_function()` in the `de_sd_diffusion` term? I will fix it properly, but I am curious whether this would help.

**Comment by vlukes** [comment]
Yes, I'm currently using the suggested fix `self.einfos = {}` in `self.make_function()`  and it works.
