### ISSUE TITLE
cannot set full DOF vector with LCBCs!

### ISSUE THREAD

**Issue by Amirrgrbn** [sfepy/sfepy#785]
Hello,
Im using sfepy to solve a simple FEM problem. The conditions og the problem are like; 

fix_u_x = EssentialBC('fix_u_x', right, {'u.0':0.0})
fix_u_y = EssentialBC('fix_u_y', bottom, {'u.1':0.0})

bc_fun = Function('bc_fun' , bc_fun, extra_args={'tr' : max_y})

bc_time = Function('bc_time' , lambda ts : False if ts.step == 0 else True)
bc_top = EssentialBC('bc_top', top, {'u.1' : constrain_disp}, times = bc_time)
#bc_left = EssentialBC('bc_left', left, {'u.0' : bc_fun})
bc_left = LinearCombinationBC(name = 'bc_left', regions = [left, None], dofs = {'u.0' : None}, 
        dof_map_fun = None, kind = 'rigid', arguments = ()) 

So the right and bottom are fixed, and on top there is a delay on applying the boundary and displacement in u.0 on left boundary is uniform (if im correct the rigid in LCBCs should confirm it). 
Having a delay on applying EBCs requires to set active_only to True ( if im right?);

pb = Problem('elasticity_real', equations=eqs, functions=functions, active_only=False)

the solvers are;

ls = ScipyDirect({})
nls_status = IndexedStruct()
nls = Newton({} , lin_solver=ls, status=nls_status, i_max = 1, eps_a= 1e-10, ls_red = 1e-8)
tss = Solver.any_from_conf(
    Struct(**{
        'kind' : 'ts.simple',
        't0' : 0,
        'n_step' : ts_step,
        'verbose' : 1,
        'quasistatic' : True}), nls=nls, context=pb)

pb.set_solver(tss)
status = IndexedStruct()
state = pb.solve(status=status)

and the equations are like:
t1 = Term.new('dw_lin_elastic(m.D, v, u)', integral0, omega, m=m, v=v, u=u)
t2 = Term.new('dw_biot(m.alpha, v, T)', integral1, omega, m=m, v=v, T=T)
t4 = Term.new('dw_surface_ltr(f.val, v)', integral0, top, f=f, v=v)

eq = Equation('balance_of_forces', t1+t2-t4)
eqs = Equations([eq])

Having ti solved I get the following error; 
sfepy: reading mesh (facet_mesh.mesh)...
sfepy:   number of vertices: 9840
sfepy:   number of cells:
sfepy:     2_4: 9589
sfepy: ...done in 0.06 s
sfepy: warning: bad element orientation, trying to correct...
sfepy: ...corrected
sfepy: saving regions as groups...
sfepy:   Omega
sfepy:   Omega_bpp
sfepy:   Omega_gdl
sfepy:   Omega_mem
sfepy:   left
sfepy:   right
sfepy:   top
sfepy:   bottom
sfepy:   left_bottom
sfepy: ...done
sfepy: updating variables...
sfepy:             Max Temperature is 20.0000000000
sfepy:   data of T set by get_temperature_load()
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.01 s
sfepy: lcbc: bc_left
sfepy: dofs: total 77714, free 77488, constrained 226, new 3
sfepy:  -> active 77491
sfepy: matrix shape: (77714, 77714)
sfepy: assembling matrix graph...
sfepy: ...done in 0.06 s
sfepy: matrix structural nonzeros: 2462788 (4.08e-02% fill)
sfepy: ====== time 0.000000e+00 (step  1 of 30) =====
sfepy: updating variables...
sfepy:             Max Temperature is 20.0000000000
sfepy:   data of T set by get_temperature_load()
sfepy: ...done
sfepy: lcbc: bc_left
sfepy: dofs: total 77714, free 77488, constrained 226, new 3
sfepy:  -> active 77491

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_13648\611744814.py in <module>
    133 status = IndexedStruct()
    134 
--> 135 state = pb.solve(status=status)
    136 
    137 

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\problem.py in solve(self, state0, status, force_values, var_data, update_bcs, update_materials, save_results, step_hook, post_process_hook, post_process_hook_final, verbose)
   1434                       prestep_fun=prestep_fun,
   1435                       poststep_fun=poststep_fun,
-> 1436                       status=status)
   1437             output('solved in %d steps in %.2f seconds'
   1438                    % (status['n_step'], status['time']), verbose=verbose)

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\solvers\ts_solvers.py in _standard_ts_call(self, vec0, nls, init_fun, prestep_fun, poststep_fun, status, **kwargs)
     32         result = call(self, vec0=vec0, nls=nls, init_fun=init_fun,
     33                       prestep_fun=prestep_fun, poststep_fun=poststep_fun,
---> 34                       status=status, **kwargs)
     35 
     36         elapsed = timer.stop()

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\solvers\ts_solvers.py in __call__(self, vec0, nls, init_fun, prestep_fun, poststep_fun, status, **kwargs)
    140         self.output_step_info(ts)
    141         if ts.step == 0:
--> 142             prestep_fun(ts, vec0)
    143 
    144             vec = self.solve_step0(nls, vec0)

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\problem.py in prestep_fun(ts, vec)
   1255                 self.time_update(ts)
   1256                 state = state0.copy()
-> 1257                 state.set_vec(vec, self.active_only)
   1258                 state.apply_ebc()
   1259 

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\state.py in set_vec(self, vec, active_only)
    244 
    245         else:
--> 246             self.set_full(vec)
    247 
    248     def create_output_dict(self, fill_value=None, var_info=None,

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\state.py in set_full(self, vec, var_name, force)
    172         if var_name is None:
    173             if self.variables.has_lcbc and not force:
--> 174                 raise ValueError('cannot set full DOF vector with LCBCs!')
    175 
    176             self.vec = vec

ValueError: cannot set full DOF vector with LCBCs!

is there any possibility that someone give me some hints on how to solve the issue? 
the second problem is that having lcbcs cause in singularity, and still have no idea on how to solve it.
Thanks

**Comment by rc** [comment]
> So the right and bottom are fixed, and on top there is a delay on applying the boundary and displacement in u.0 on left boundary is uniform (if im correct the rigid in LCBCs should confirm it).
> Having a delay on applying EBCs requires to set active_only to True ( if im right?);

You meant setting `'active_only' : False`, right? Anyway it seems that this combination (active_only = False and LCBCs) is not currently possible. Is it not possible to use the initial condition for the `bc_top` at t=0?

You need to fix the rigid body motions to avoid the singular matrix. The LCBCs only are not enough.

(How do you set T? Is there another equation?)

**Comment by Amirrgrbn** [comment]
Exactly setting active_only to false, 
For the boundary top i want to have constant displacement but the value has to be the ts.step =0 value. So not sure if it works with initial condition ( or maybe i dont know how to).
The T is simply supplied by function using time steps. 
There seems to be a way handling this by assigning the Force to True in; 
173 if self.variables.has_lcbc and not force:
Is it possible?

**Comment by Amirrgrbn** [comment]
By top constrain the displacement is the value after considering Force and replace it with displacement after time zero.

**Comment by rc** [comment]
I can imagine two possible solutions:

1. Split it into two problems: first solve the initial step to get the displacement, then solve the time-dependent problem with the already known boundary conditions with `'active_only' : True`.

2. Define custom `prestep_fun()` and `poststep_fun()` functions (see `Problem.get_tss_functions()`), where you pass `force=True` to ` variables.set_state()` (*), see [this example](https://sfepy.org/doc-devel/examples/diffusion-time_poisson_interactive.html) that demonstrates how to set those custom functions.

The option 1 seems easier to me.

(*) The state handling was updated in the git version, see #764.

**Comment by Amirrgrbn** [comment]
Thanks, I would try both to see the results,
just a question would it be possible to replace the rigid boundary with such a function? 

def bc_fun(ts,coors, mode=None, tr = 0, **kwarg):
    
    val = np.empty(coors.shape[0], dtype=np.float64)
    uvar = eqs.variables['u']
    
    val[coors[:,1] == tr] = uvar.evaluate_at(coors[coors[:,1] == tr])[:,0]
    val[coors[:,1] != tr] = np.ones_like(coors.shape[0]-1)*val[coors[:,1] == tr]
    
    return val
and then:
bc_left = EssentialBC('bc_left', left, {'u.0' : bc_fun})

**Comment by rc** [comment]
Yes, use something like `fbc_fun = Function('u_fun', bc_fun, extra_args={'tr': tr})` to pass additional arguments ([example](https://sfepy.org/doc-devel/examples/linear_elasticity-linear_elastic_interactive.html)).

**Comment by Amirrgrbn** [comment]
Just, would it be right considering such a function? Is it quite same as considering rigid?

**Comment by Amirrgrbn** [comment]
Im tryinh to solve usingt  the prestep_fun but dont know exactly how to define the prestep fun;

tss = Solver.any_from_conf(
    Struct(**{
        'kind' : 'ts.simple',
        't0' : 0,
        'n_step' : ts_step,
        'verbose' : 1,
        'quasistatic' : True}), nls=nls, context=pb)
        

variables = pb.get_initial_state()
init_fun , _prestep_fun, poststep_fun = pb.get_tss_functions(variables)

pb.set_solver(tss)
status = IndexedStruct()

def prestep_fun(ts,vec):
    _prestep_fun(ts,vec)
    variables.set_full(vec, force=True)
    
pb.time_update(tss.ts)
variables.apply_ebc()

tss_status = IndexedStruct()
tss(variables.get_vec(pb.active_only),prestep_fun=prestep_fun,status=tss_status)

**Comment by Amirrgrbn** [comment]
Can you help me on how to fix the rigid boundary, to at the same time doesnt have the assertion error?

**Comment by rc** [comment]
Can you attach your complete example (a small mesh included), so that I could test it?

**Comment by Amirrgrbn** [comment]
Here is the simpler case, with easy geom. If it works for this it will do in complete one, Sorry but for now I dont have access to full example.
[sfepy_doc.zip](https://github.com/sfepy/sfepy/files/8191611/sfepy_doc.zip)

**Comment by Amirrgrbn** [comment]
Please finde the full version of code, used the git vesrion of sfepy

[facet_mesh.zip](https://github.com/sfepy/sfepy/files/8196207/facet_mesh.zip)

**Comment by Amirrgrbn** [comment]
updated

**Comment by Amirrgrbn** [comment]
I think I have partially handeled the probelm therewith rigid boundary, now tghe new problem is that solving with ls, it solves for all time steps but the residual is too larg (put i_max=0), 

sfepy: reading mesh (facet_mesh.mesh)...
sfepy:   number of vertices: 5580
sfepy:   number of cells:
sfepy:     2_4: 5394
sfepy: ...done in 0.03 s
sfepy: warning: bad element orientation, trying to correct...
sfepy: ...corrected
sfepy: saving regions as groups...
sfepy:   Omega
sfepy:   Omega_bpp
sfepy:   Omega_gdl
sfepy:   Omega_mem
sfepy:   left
sfepy:   right
sfepy:   top
sfepy:   bottom
sfepy:   single_top
sfepy: ...done
sfepy: updating variables...
sfepy:             Max Temperature is 20.0000000000
sfepy:   data of T set by get_temperature_load()
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.00 s
sfepy: lcbc: bc_left
sfepy: dofs: total 43894, free 43718, constrained 176, new 3
sfepy:  -> active 43721
sfepy: matrix shape: (43894, 43894)
sfepy: assembling matrix graph...
sfepy: ...done in 0.04 s
sfepy: matrix structural nonzeros: 1386788 (7.20e-02% fill)
sfepy: ====== time 0.000000e+00 (step 1 of 5) =====
sfepy: updating variables...
sfepy:             Max Temperature is 20.0000000000
sfepy:   data of T set by get_temperature_load()
sfepy: ...done
sfepy: lcbc: bc_left
sfepy: dofs: total 43894, free 43718, constrained 176, new 3
sfepy:  -> active 43721
sfepy: updating materials...
sfepy:     m
sfepy:     f
sfepy:             Pressure is -1000000.0000000000
sfepy: ...done in 0.02 s
sfepy: nls: iter: 0, residual: 2.397618e+02 (rel: 1.000000e+00)
sfepy: ====== time 2.500000e-01 (step 2 of 5) =====
sfepy: updating variables...
sfepy:             Max Temperature is 22.2758620690
sfepy:   data of T set by get_temperature_load()
sfepy: ...done
sfepy: lcbc: bc_left
sfepy: dofs: total 43894, free 43718, constrained 176, new 3
sfepy:  -> active 43721
sfepy: updating materials...
sfepy:     m
sfepy:     f
sfepy:             Pressure is -1000000.0000000000
sfepy: ...done in 0.00 s
sfepy: nls: iter: 0, residual: 2.397618e+02 (rel: 1.000000e+00)
sfepy: ====== time 5.000000e-01 (step 3 of 5) =====
sfepy: updating variables...
sfepy:             Max Temperature is 24.5517241379
sfepy:   data of T set by get_temperature_load()
sfepy: ...done
sfepy: lcbc: bc_left
sfepy: dofs: total 43894, free 43718, constrained 176, new 3
sfepy:  -> active 43721
sfepy: updating materials...
sfepy:     m
sfepy:     f
sfepy:             Pressure is -1000000.0000000000
sfepy: ...done in 0.00 s
sfepy: nls: iter: 0, residual: 2.397618e+02 (rel: 1.000000e+00)
sfepy: ====== time 7.500000e-01 (step 4 of 5) =====
sfepy: updating variables...
sfepy:             Max Temperature is 26.8275862069
sfepy:   data of T set by get_temperature_load()
sfepy: ...done
sfepy: lcbc: bc_left
sfepy: dofs: total 43894, free 43718, constrained 176, new 3
sfepy:  -> active 43721
sfepy: updating materials...
sfepy:     m
sfepy:     f
sfepy:             Pressure is -1000000.0000000000
sfepy: ...done in 0.00 s
sfepy: nls: iter: 0, residual: 2.397618e+02 (rel: 1.000000e+00)
sfepy: ====== time 1.000000e+00 (step 5 of 5) =====
sfepy: updating variables...
sfepy:             Max Temperature is 29.1034482759
sfepy:   data of T set by get_temperature_load()
sfepy: ...done
sfepy: lcbc: bc_left
sfepy: dofs: total 43894, free 43718, constrained 176, new 3
sfepy:  -> active 43721
sfepy: updating materials...
sfepy:     m
sfepy:     f
sfepy:             Pressure is -1000000.0000000000
sfepy: ...done in 0.00 s
sfepy: nls: iter: 0, residual: 2.397618e+02 (rel: 1.000000e+00)


but when it change i_max to a value except 0, it gives assertion error. 

sfepy: reading mesh (facet_mesh.mesh)...
sfepy:   number of vertices: 5580
sfepy:   number of cells:
sfepy:     2_4: 5394
sfepy: ...done in 0.04 s
sfepy: warning: bad element orientation, trying to correct...
sfepy: ...corrected
sfepy: saving regions as groups...
sfepy:   Omega
sfepy:   Omega_bpp
sfepy:   Omega_gdl
sfepy:   Omega_mem
sfepy:   left
sfepy:   right
sfepy:   top
sfepy:   bottom
sfepy:   single_top
sfepy: ...done
sfepy: updating variables...
sfepy:             Max Temperature is 20.0000000000
sfepy:   data of T set by get_temperature_load()
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.00 s
sfepy: lcbc: bc_left
sfepy: dofs: total 43894, free 43718, constrained 176, new 3
sfepy:  -> active 43721
sfepy: matrix shape: (43894, 43894)
sfepy: assembling matrix graph...
sfepy: ...done in 0.04 s
sfepy: matrix structural nonzeros: 1386788 (7.20e-02% fill)
sfepy: ====== time 0.000000e+00 (step 1 of 5) =====
sfepy: updating variables...
sfepy:             Max Temperature is 20.0000000000
sfepy:   data of T set by get_temperature_load()
sfepy: ...done
sfepy: lcbc: bc_left
sfepy: dofs: total 43894, free 43718, constrained 176, new 3
sfepy:  -> active 43721
sfepy: updating materials...
sfepy:     f
sfepy:             Pressure is -1000000.0000000000
sfepy:     m
sfepy: ...done in 0.02 s
sfepy: nls: iter: 0, residual: 2.397618e+02 (rel: 1.000000e+00)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_19828\1920340429.py in <module>
    150 vec = tss(variables.get_state(pb.active_only,force=True),init_fun=init_fun,
    151           prestep_fun=prestep_fun,
--> 152           poststep_fun=poststep_fun, status=tss_status)
    153 
    154 variables.set_state(vec, pb.active_only, force=True)

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\solvers\ts_solvers.py in _standard_ts_call(self, vec0, nls, init_fun, prestep_fun, poststep_fun, status, **kwargs)
     32         result = call(self, vec0=vec0, nls=nls, init_fun=init_fun,
     33                       prestep_fun=prestep_fun, poststep_fun=poststep_fun,
---> 34                       status=status, **kwargs)
     35 
     36         elapsed = timer.stop()

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\solvers\ts_solvers.py in __call__(self, vec0, nls, init_fun, prestep_fun, poststep_fun, status, **kwargs)
    142             prestep_fun(ts, vec0)
    143 
--> 144             vec = self.solve_step0(nls, vec0)
    145 
    146             poststep_fun(ts, vec)

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\solvers\ts_solvers.py in solve_step0(self, nls, vec0)
    110     def solve_step0(self, nls, vec0):
    111         if self.conf.quasistatic:
--> 112             vec = nls(vec0)
    113 
    114         else:

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\solvers\nls.py in __call__(self, vec_x0, conf, fun, fun_grad, lin_solver, iter_hook, status)
    352             vec_dx = lin_solver(vec_r, x0=vec_x,
    353                                 eps_a=eps_a, eps_r=eps_r, mtx=mtx_a,
--> 354                                 status=ls_status)
    355             ls_n_iter += ls_status['n_iter']
    356             time_stats['solve'] = timer.stop()

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\solvers\ls.py in _standard_call(self, rhs, x0, conf, eps_a, eps_r, i_max, mtx, status, context, **kwargs)
     76         context = get_default(context, self.context)
     77 
---> 78         assert_(mtx.shape[0] == mtx.shape[1] == rhs.shape[0])
     79         if x0 is not None:
     80             assert_(x0.shape[0] == rhs.shape[0])

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\base\base.py in assert_(condition, msg)
    221 def assert_(condition, msg='assertion failed!'):
    222     if not condition:
--> 223         raise ValueError(msg)
    224 
    225 ##

ValueError: assertion failed!

**Comment by Amirrgrbn** [comment]
here is the code and mesh; 

[Uploading facet_mesh.zip…]()

**Comment by rc** [comment]
I will try to look at it tonight or tomorrow.

**Comment by Amirrgrbn** [comment]
thanks alot

**Comment by rc** [comment]
I had set `{'is_linear': False}` in the Newton solver to overcome the `ValueError` above, but then came to another, more fundamental problem.

I think I can finally see the problem. LCBCs are incompatible with `active_only = False`, because with LCBCs, one must apply them prior to solving the linear system, and so the vectors/matrices are in fact "reduced" (in size). I do not see an easy way of reconciling those two concepts. 

There are IMO two ways forward:
- The splitting into two problems, proposed already above.
- Not using LCBCs, but enforcing the rigid boundary in a weak sense by some penalty term - something like [this](https://sfepy.org/doc-devel/examples/multi_physics-biot_npbc.html) (LCBCs) vs [that](https://sfepy.org/doc-devel/examples/multi_physics-biot_npbc_lagrange.html) (Lagrange multipliers).

**Comment by Amirrgrbn** [comment]
Ok, appreciate your effort on this, i may try another way then

**Comment by rc** [comment]
Not sure, something like elasticity, to penalize non-zero strain?

**Comment by Amirrgrbn** [comment]
I will try but then would it be possible to do it inly in u.0 direction?

**Comment by Amirgrbn** [comment]
Hello, again, 
Well it seems that dividing into two problems would be straight forward way to handle my situation, but the problem is that I still have the error of singularity using the rigid boundary. I would appreciate if you can let me know How to fix it? 
[facet_mesh.zip](https://github.com/sfepy/sfepy/files/8247024/facet_mesh.zip)

**Comment by rc** [comment]
The rigid LCBCs work cannot work for 'u.0' only (I missed this detail). With 'u.all' it works, right?

**Comment by Amirrgrbn** [comment]
Yes, applying on u.0 gives a singularity error. ( or residual is nan).
