### ISSUE TITLE
material_opt script error

### ISSUE THREAD

**Issue by BarelyPotato** [sfepy/sfepy#794]
Hello,
When running the "material identification" script, i get the following error 
"state = out[-1][1].get_state_parts()
AttributeError: 'State' object has no attribute 'get_state_parts'"

**Comment by rc** [comment]
Hi,

Either consult the latest release docs (https://sfepy.org/doc/mat_optim.html) or, better, get the git version of sfepy (the default docs on the website are the development docs). See #764 for background.

**Comment by BarelyPotato** [comment]
I got sfepy using the conda forge command. Now i'm trying to reset conda and run sfepy without installation from sources after installing the relevant packages and the c extension modules. It's taking a while since i'm facing compatibility issues with different python versions. I will report back when it's done.

**Comment by BarelyPotato** [comment]
The problem is solved. 

However, at the end of the script run ("material optimization FINISHED <<<" is printed) the figure interface freezes, then when I force close it, an array of the optimized parameters is printed followed by an error due to force closing the figure. I will try in a different machine and a different OS and see if the same happens.

Thank you @rc.

**Comment by rc** [comment]
Closing answered issues with no further reaction...
