### ISSUE TITLE
modify the final stiffness matrix

### ISSUE THREAD

**Issue by Antoniobari** [sfepy/sfepy#796]
Hello, 
Im trying to use sfepy for some elastic problems, but i wonder if it is also possible to access the final stiffness matrix and modify it before solving it, or modify the mapping algorithm. I have seen some examples with prestep_fun and want to know if it is possible to use such function for it, 
appreciate in advance for any help

**Comment by Amirrgrbn** [comment]
Thanks, it solved my issue. 
one more question, defining material by function is it also possible to also define the region? im tryinh to use the following but geting error;

def get_material(ts, coors, young_modulus = [], poisson_ratio = [], alpha = [], region= None,**kwargs):

    eye_array = np.array([[1],[1],[0]])
    out = {'D' : {'Omega_bottom' : stiffness_from_youngpoisson(dim=2, young=young_modulus[0] , poisson=poisson_ratio[0], plane='stress'),
                    'Omega_top' : stiffness_from_youngpoisson(dim=2, young=young_modulus[1], poisson=poisson_ratio[1], plane='stress')},
            'alpha' : {'Omega_bottom' : (young_modulus[0]/(1-poisson_ratio[0])*eye_array*alpha[0]),
                       'Omega_top' : (young_modulus[1]/(1-poisson_ratio[1])*eye_array*alpha[1])},},
            's' : {'Omega_bottom' : (young_modulus[0]/(1-poisson_ratio[0])*eye_array),
                    'Omega_top' : (young_modulus[1]/(1-poisson_ratio[1])*eye_array)}}}
    return out 

and get the error; 

AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_13900\3327039428.py in <module>
    118 status = IndexedStruct()
    119 store = Function('store',store)
--> 120 state = pb.solve(status=status, save_results=False, step_hook=store)
    121 
    122 print('Nonlinear solver status:\n', tss_status)

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\problem.py in solve(self, state0, status, force_values, var_data, update_bcs, update_materials, save_results, step_hook, post_process_hook, post_process_hook_final, verbose)
   1419 
   1420             if self.is_linear():
-> 1421                 mtx = prepare_matrix(self, variables) # Updates materials.
   1422                 self.try_presolve(mtx)
   1423 

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\problem.py in prepare_matrix(problem, state)
     78     Pre-assemble tangent system matrix.
     79     """
---> 80     problem.update_materials()
     81 
     82     ev = problem.get_evaluator()

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\problem.py in update_materials(self, ts, mode, verbose)
    595             self.update_time_stepper(ts)
    596             self.equations.time_update_materials(self.ts, mode=mode,
--> 597                                                  problem=self, verbose=verbose)
    598 
    599 

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\equations.py in time_update_materials(self, ts, mode, problem, verbose)
    340         """
    341         self.materials.time_update(ts, self, mode=mode, problem=problem,
--> 342                                    verbose=verbose)
    343 
    344     def setup_initial_conditions(self, ics, functions=None):

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\materials.py in time_update(self, ts, equations, mode, problem, verbose)
     56         for mat in self:
     57             if verbose: output(' ', mat.name)
---> 58             mat.time_update(ts, equations, mode=mode, problem=problem)
     59         if verbose: output('...done in %.2f s' % timer.stop())
     60 

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\materials.py in time_update(self, ts, equations, mode, problem)
    305 
    306         for key, term in self.iter_terms(equations):
--> 307             self.update_data(key, ts, equations, term, problem=problem)
    308 
    309         self.update_special_data(ts, equations, problem=problem)

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\materials.py in update_data(self, key, ts, equations, term, problem)
    224                              **self.extra_args)
    225 
--> 226         self.set_data(key, qps, data)
    227 
    228     def update_special_data(self, ts, equations, problem=None):

~\miniconda3\envs\fuelcell\lib\site-packages\sfepy\discrete\materials.py in set_data(self, key, qps, data)
    187         if data is not None:
    188             for dkey, val in six.iteritems(data):
--> 189                 if val.ndim != 3:
    190                     raise ValueError('material parameter array must have'
    191                                      " three dimensions! ('%s' has %d)"

AttributeError: 'dict' object has no attribute 'ndim'

**Comment by Amirrgrbn** [comment]
for a single region i get the following error, 


def get_mat(ts,coors,**kwargs):
    return {'D' : stiffness_from_youngpoisson(dim=2, young=1e6 ,
                                            poisson= 0.25, plane='stress')}

get_mat = Function('get_mat',get_mat) 
m = Material('m', function = get_mat)


ValueError: material parameter array must have three dimensions! ('D' has 2)

**Comment by Amirgrbn** [comment]
Sorry for asking so many things, but is there any posssiblity to consider elastoplastic and strai-hardening behavior with sfepy?

**Comment by rc** [comment]
> Thanks, it solved my issue. one more question, defining material by function is it also possible to also define the region? im tryinh to use the following but geting error;

No, you should not mix that - the material function should return a dict of material parameters. But you can decide what to put in that dict based on `term.region`, see the [complete material function signature](https://sfepy.org/doc-devel/users_guide.html#functions) (search "full signature").

**Comment by rc** [comment]
> Sorry for asking so many things, but is there any posssiblity to consider elastoplastic and strai-hardening behavior with sfepy?

Those models are not implemented. It might be possible to add them, but you would be on your own - I have no knowledge of plasticity.

**Comment by Amirrgrbn** [comment]
Thanks, I just solved the issue refering to example, homogenization_opt and it is ok now. 
For the plasticity, I should then try to finout the possible way to implement it.
Thanks

**Comment by Amirrgrbn** [comment]
Hello, 
I will try to add additional contribtion of the plasticity to the equations ( it might produce some errors but for the moment seems to be fine), the idea is to compute at each step the value and add it to equations for the next step. 
since for 3D problem it would be like 
![image](https://user-images.githubusercontent.com/65605644/162926128-44d61667-1ea3-4f6f-b5d8-7d003bbf8e4e.png)
, normally for Therml effect i was using biot, but this shpa would not be compatible with that equation, Would you please let me know if there is any equation (in terms) that can handle it for me? 

thanks

**Comment by vlukes** [comment]
Would be `dw_lin_prestress` [1] right for you?

[1] https://sfepy.org/doc-devel/src/sfepy/terms/terms_elastic.html#sfepy.terms.terms_elastic.LinearPrestressTerm

**Comment by Amirrgrbn** [comment]
yes, actually i did use it;  but the idea doesnt seem correct for the plasticity.
thanks for it.

**Comment by rc** [comment]
Closing answered questions with no further reaction...
