### ISSUE TITLE
How to define a Sub-Domain from point coordinates? 

### ISSUE THREAD

**Issue by nicolasDucou** [sfepy/sfepy#799]
Hello, I would like to know if it is possible and how should I proceed to create a subdomain (for applying BCs or load) from points coordinates?

Thanks in advance for your answer. 

Nicolas Ducoulombier

**Comment by vlukes** [comment]
Hi Nicolas,

A subdomain from coordinates can be selected by a user defined function. See examples [1], [2] or User’s Guide/Regions.

Example (from User’s Guide):

```
import numpy as nm

def get_ball(coors, domain=None):
    x, y, z = coors[:, 0], coors[:, 1], coors[:, 2]

    r = nm.sqrt(x**2 + y**2 + z**2)
    flag = nm.where((r < 0.1))[0]

    return flag

functions = {
    'get_ball' : (get_ball,),
}

regions = {
    'Omega_B' : 'vertices by get_ball',
}
```

Regards
Vladimir

[1] https://sfepy.org/doc-devel/examples/diffusion-poisson_parametric_study.html
[2] https://sfepy.org/doc-devel/examples/diffusion-poisson_functions.html

**Comment by vlukes** [comment]
Dear Nicolas,

the function in the example above allows you for more general rules than simple inequalities. The mesh coordinates are in the input argument `coors`, so if you can compare them to another point sets. The output of the function is a list of vertices belonging to the domain. Nothing more general is available.

Regards
Vladimir

**Comment by rc** [comment]
Closing answered questions with no further reaction...
