### ISSUE TITLE
Does sfepy support multiple dependent variables ?

### ISSUE THREAD

**Issue by lisixi** [sfepy/sfepy#810]
![未命名](https://user-images.githubusercontent.com/43193161/164472684-9e13093b-ca55-4693-87dd-0daf38d24396.jpg)
I have a system of PDEs for 2D problem, which is coupled. This system has two dependent variables, u_0 and u_-1. And I have given the weak form of this system, as is shown in the attached figure. In this figure, a, b, c, d, M_0, M_-1, are known, and v_0 and v_-1 are the corresponding test functions. This system only has the first boundary condition.
So, is it possible to solve this PDEs by sfepy?

**Comment by vlukes** [comment]
Hi @lisixi,

if u0 and u1 are the scalar unknowns, the coupled equations  can be coded in SfePy as

```
dw_dot.i.Omega(coefs.a, v0, u0) + dw_dot.i.Omega(coefs.b, v0, u1) + dw_diffusion_coupling.i.Omega(coef.M0, v0, u0) - dw_dot.i.dOmega(coef.M0n, v0, u0) = 0
```
and

```
dw_dot.i.Omega(coefs.c, v1, u0) + dw_dot.i.Omega(coefs.d, v1, u1) + dw_diffusion_coupling.i.Omega(coef.M1, v1, u1) - dw_dot.i.dOmega(coef.M1n, v1, u1) = 0
```

where `coef.M0n` and `coef.M1n` are projections of `M0` and `M1` into the normal direction.
 
See term overview [1] and the examples.

[1] https://sfepy.org/doc-devel/terms_overview.html

**Comment by rc** [comment]
Closing answered questions with no further reaction...
