### ISSUE TITLE
Set multiple forces

### ISSUE THREAD

**Issue by lshxx** [sfepy/sfepy#819]
How should I set different forces on different nodes? For example, at the same time, the force of the X direction at the position of the node 1 is 2N, and the force of the Y direction is 3N. The force of the X direction of the node 2 is 1N, and the force of the Y direction is 4N.

**Comment by rc** [comment]
See [this](https://sfepy.org/doc-devel/users_guide.html#defining-material-parameters-by-functions). If you really want nodal forces, have a look at the `dw_point_load` term.

**Comment by lshxx** [comment]
> See [this](https://sfepy.org/doc-devel/users_guide.html#defining-material-parameters-by-functions). If you really want nodal forces, have a look at the `dw_point_load` term.

I saw this example, but I'm a beginner. So I don't understand the example, can you give me a clearer example that describes it?

**Comment by vlukes** [comment]
Take a look at the [primer](https://sfepy.org/doc-devel/primer.html) and  this example: [linear_elasticity/its2D_1.py](https://sfepy.org/doc-devel/examples/linear_elasticity-its2D_1.html).

**Comment by lshxx** [comment]
> Take a look at the [primer](https://sfepy.org/doc-devel/primer.html) and this example: [linear_elasticity/its2D_1.py](https://sfepy.org/doc-devel/examples/linear_elasticity-its2D_1.html).

I want to set different forces on nodes 4 and 5, but it seems my code can't do it. Could you please help me find out why?
[question.zip](https://github.com/sfepy/sfepy/files/8704759/question.zip)

**Comment by lshxx** [comment]
> See [this](https://sfepy.org/doc-devel/users_guide.html#defining-material-parameters-by-functions). If you really want nodal forces, have a look at the `dw_point_load` term.
from __future__ import absolute_import
import numpy as nm

from sfepy.base.base import IndexedStruct
from sfepy.discrete import (FieldVariable, Material, Integral, Functions,Function,
                            Equation, Equations, Problem)
from sfepy.discrete.fem import Mesh, FEDomain, Field
from sfepy.terms import Term
from sfepy.discrete.conditions import Conditions, EssentialBC
from sfepy.mechanics.matcoefs import stiffness_from_youngpoisson
#from sfepy.discrete.fem.utils import refine_mesh
from sfepy.solvers.auto_fallback import AutoDirect
#from sfepy.solvers.ls import ScipyDirect, ScipySuperLU, ScipyUmfpack,MUMPSSolver
from sfepy.solvers.nls import Newton
from sfepy import data_dir
from sfepy.postprocess import plot_dofs
from sfepy.postprocess.plot_dofs import _get_axes

import matplotlib.pyplot as plt






mesh = Mesh.from_file('D:/sfepy_mesh/meshes/2d/mesh12.msh')
domain = FEDomain('domain', mesh)
conn = domain.get_conn()

coors = domain.get_mesh_coors()

young =1.0 # Young's modulus [MPa]
poisson =0.3   # Poisson's ratio


domain = FEDomain('domain', mesh)
omega = domain.create_region('Omega','all')

left = domain.create_region('Left','vertices in (x < 1)', 'facet')

top = domain.create_region('Top','vertex 4,5', 'vertex')


field = Field.from_args('fu', nm.float64, 'vector', omega,
                                       approx_order = 1)

u = FieldVariable('u', 'unknown', field)
v = FieldVariable('v', 'test', field, primary_var_name='u')





def get_load(ts, coors, mode, **kwargs):
    

    if mode == 'qp':
        x = coors[:, 0]

        val = 2

        val.shape = (coors.shape[0], 1, 1)
        return {'f' : val} 
    


asphalt = Material('Asphalt',D = stiffness_from_youngpoisson(2, young, poisson,plane = 'stress'))

load = Material('Load', function=Function('get_load', get_load))


integral = Integral('i', order=2)
integral0 = Integral('i', order=0)

t1 = Term.new('dw_lin_elastic(Asphalt.D, v, u)',
              integral, omega, Asphalt=asphalt, v=v, u=u)


t2 = Term.new('dw_point_load(Load.val, v)',
              integral0, top, Load=load, v=v)

eq = Equation('balance', t1 - t2)

eqs = Equations([eq])


ysym = EssentialBC('YSym', left, {'u.0' : 0.0})

ls = AutoDirect({})

nls_status = IndexedStruct()
nls = Newton({}, lin_solver=ls, status=nls_status)

pb = Problem('elasticity', equations=eqs)

pb.set_bcs(ebcs=Conditions([ysym]))

pb.set_solver(nls)


statee = pb.solve()

out = statee.create_output_dict()

pb.save_state('csits2D_interactive.vtk', statee)
[mesh.zip](https://github.com/sfepy/sfepy/files/8707982/mesh.zip)

**Comment by rc** [comment]
Closing answered questions with no further reaction...
