### ISSUE TITLE
Visualize the material property before the main simulation?

### ISSUE THREAD

**Issue by yug-NUST** [sfepy/sfepy#827]
I was trying to define the material property as a function of space coordinates. Before running the simulation, I just want to make sure that the material property is set correctly. Is there a way to visualize the material property after creating the material instance with the following code?
```
def th_cond(ts, coors, mode=None, **kwargs):
    x, y = coors[:, 0], coors[:, 1]
    val = ( x * y) *  2 * nm.pi
    val.shape = (coors.shape[0], 1, 1)
    return {'kap' : val}
thcond = Function('thcond', th_cond)
m = Material('kappa', function=thcond)
```
When using a function to define material properties, it seems there's no parameter to attach the material property to a certain region.  
So I defined a new term as follows:

`t1 = Term.new('ev_integrate_mat(m.kap, pa)', integral, omega_total, m=m, pa=1)`

Now a region 'omega_total' is defined. Then, I called:

`t1.evaluate()`

The following error pops up
AttributeError: 'IntegrateMatTerm' object has no attribute 'names' 
I misused it apparently, but I cannot find any other way to evaluate the term.

So I tried a simpler example by setting material parameters in different regions directly:

`m = Material('m',  values={'kappa': {'omega1': 1, 'omega2': 2}})`

I still cannot find any method for the instance m to get the material property at different meshing points. 

I've already searched different examples and FAQs. I understand that postprocessing tricks should do the job. However, with defined regions and material properties, one should be able to visualize the material property at this stage without solving the whole problem.

**Comment by rc** [comment]
The function should look like this:
```
def th_cond(ts, coors, mode='None', **kwargs):
    if mode == 'qp':
        x, y = coors[:, 0], coors[:, 1]
        val = (x * y) * 2 * nm.pi
        val.shape = (coors.shape[0], 1, 1)
        return {'kap' : val}
```
Then your code works. Also, maybe you want the last line to be:
```
mat = pb.evaluate('ev_integrate_mat.2.omegat(m.kap, pa)', m=m, mode='el_avg')
```

**Comment by yug-NUST** [comment]
> The function should look like this:
> 
> ```
> def th_cond(ts, coors, mode='None', **kwargs):
>     if mode == 'qp':
>         x, y = coors[:, 0], coors[:, 1]
>         val = (x * y) * 2 * nm.pi
>         val.shape = (coors.shape[0], 1, 1)
>         return {'kap' : val}
> ```
> 
> Then your code works. Also, maybe you want the last line to be:
> 
> ```
> mat = pb.evaluate('ev_integrate_mat.2.omegat(m.kap, pa)', m=m, mode='el_avg')
> ```

Thank you very much. It works now. Can you explain why the following line is necessary?
`if mode == 'qp':`
It seems the function 'th_cond' inherits the 'mode' information from somewhere.

**Comment by rc** [comment]
See [this](https://sfepy.org/doc-devel/users_guide.html#defining-material-parameters-by-functions) - the function is called several times in different modes, and the coordinates argument is not always set.

**Comment by rc** [comment]
Closing answered questions with no further reaction...
