### ISSUE TITLE
Setup "matrix_hook" through interactive way

### ISSUE THREAD

**Issue by ywan459** [sfepy/sfepy#882]
Hi there, 

1. Just wondering about how to setup the "matrix_hook" through the imperative API. I have read the post #796 , but I have not seen any codes regarding to the imperative API. 

2. API docs said "matrix_hook" updates every iteration (see: [ check setup_hook function](https://sfepy.org/doc/src/sfepy/discrete/problem.html#sfepy.discrete.problem.Problem.setup_hooks) I would like to know whether the facilities are available for artificially updating of stiffness matrix just before solving the problem. 

Here is my toy problem code, basically it follows the linear_elasticity.py 

`
from argparse import ArgumentParser
import numpy as nm

import sys
sys.path.append('.')

from sfepy.base.base import IndexedStruct
from sfepy.discrete import (FieldVariable, Material, Integral, Function,
                            Equation, Equations, Problem)
from sfepy.discrete.fem import Mesh, FEDomain, Field
from sfepy.terms import Term
from sfepy.discrete.conditions import Conditions, EssentialBC
from sfepy.solvers.ls import ScipyDirect
from sfepy.solvers.nls import Newton
from sfepy.mechanics.matcoefs import stiffness_from_lame
from sfepy.mechanics.matcoefs import stiffness_from_youngpoisson
from sfepy.mesh.mesh_generators import gen_block_mesh

def modify_matrix(mtx, problem, call_mode):
    mtx = mtx*2
    return mtx

def main():
    from sfepy import data_dir

    parser = ArgumentParser()
    parser.add_argument('--version', action='version', version='%(prog)s')
    options = parser.parse_args()
    
    mesh = gen_block_mesh([0.0098, 0.0011, 0.1], [5, 3, 17],
                          [0, 0, 0.05], name='specimen',
                          verbose=False)
    
    domain = FEDomain('domain', mesh)

    min_x, max_x = domain.get_mesh_bounding_box()[:,0]
    eps = 1e-8 * (max_x - min_x)
    omega = domain.create_region('Omega', 'all')
    
    gammaBtm = domain.create_region('Btm',
                                  'vertices in (z < 0.001)', 'facet')
    gammaTop = domain.create_region('Top',
                                  'vertices in (z > 0.099)', 'facet')

    field = Field.from_args('fu', nm.float64, 'vector', omega,
                            approx_order=2)

    u = FieldVariable('u', 'unknown', field)
    v = FieldVariable('v', 'test', field, primary_var_name='u')

    m = Material('m', D=stiffness_from_youngpoisson(3, 150.0e9, 0.3))
    
    S = 1.083500e-05    # specimen cross-section
    F = 5.0e3*10           # force
    f = Material('f', val=F/S)

    integral = Integral('i', order=5)

    t1 = Term.new('dw_lin_elastic(m.D, v, u)',
                  integral, omega, m=m, v=v, u=u)
    t2 = Term.new('dw_surface_ltr(f.val, v)', integral, gammaTop, f=f, v=v)
    
    eq = Equation('balance', t1 - t2)
    eqs = Equations([eq])

    fix_u = EssentialBC('fix_u', gammaBtm, {'u.all' : 0.0})

    ls = ScipyDirect({})
    
    nls_status = IndexedStruct()
    nls = Newton({}, lin_solver=ls, status=nls_status)
    
    pb = Problem('elasticity', equations=eqs)
    #pb.save_regions_as_groups('regions')

    pb.set_bcs(ebcs=Conditions([fix_u]))
    pb.set_solver(nls)
    
    # Try to setup the matrix_hook here. 
    # pb.setup_hooks(options={
    #    "matrix_hook" : modify_matrix})
    
    # evaluate the stiffness matrix
    # variables = pb.get_initial_state()
    # pb.time_update()
    # pb.update_materials()
    # variables.apply_ebc()
    # r = pb.equations.eval_residuals(variables())
    # K = pb.equations.eval_tangent_matrices(variables(), pb.mtx_a)

    status = IndexedStruct()
    variables = pb.solve(status=status)

    print('Nonlinear solver status:\n', nls_status)
    print('Stationary solver status:\n', status)

    pb.save_state('linear_elasticity.vtk', variables)
    
if __name__ == '__main__':
    main()

`

**Comment by rc** [comment]
Hi @ywan459,

The following two lines should do - put those just below `pb.set_solver(nls)`:
```python
    ev = pb.get_evaluator(reuse=True)
    ev.matrix_hook = modify_matrix
```

**Comment by rc** [comment]
Closing answered questions with no further reaction...
