### ISSUE TITLE
Phonon - phase velocity vs. other CLI options

### ISSUE THREAD

**Issue by heczis** [sfepy/sfepy#884]
Hi,
I wanted to run the phononic simulation with all the options enabled (plot, dispersion, phase velocity) and I guess that this piece of code makes it crash:
https://github.com/sfepy/sfepy/blob/64467347475f9ade8d2aa78d191578f44216ce45/sfepy/homogenization/band_gaps_app.py#L368-L371
Should I change the working of `AcousticBandGapsApp` or rather make the relevant command-line parameters of `simple.py` exclusive to each other? (In other words: Does it make sense to run a phononic simulation with `--phonon-phase-velocity` plus any other option?)

**Comment by rc** [comment]
Whatever is easier :) (the exclusive options?)
