### ISSUE TITLE
Some general questions from a beginner

### ISSUE THREAD

**Issue by peppe988** [sfepy/sfepy#886]
Dear all, I am new to FEM analysis and I would like to ask for your help, I am really sorry if these questions are too basic or if this is the wrong section but I am new to GitHub too. So here are my questions:

1) I don't understand how to create an equation which is not a simple sum of the terms in the "term table".  
For example, if we call phi, phi2 our unknown variables and I want to solve the Laplace equation with dw_laplace(s, f(phi,phi2),*) where f(phi,phi2)=phi*phi2/(sqrt(1+phi**2) (it is just an example to ask how to do operations with the variables on sfepy, I don't even know if the equation makes sense). How do I do that?

2) always related to the previous question, after solving the solutions for example in 3D, how do I process the variables for calculating other equations?

2) is it possible to create a domain which is just 2 different 3d rectangular boxes connected to each other, without using any CAD software?

Thank you and sorry for these questions!

**Comment by rc** [comment]
Hi @peppe988,

> Dear all, I am new to FEM analysis and I would like to ask for your help, I am really sorry if these questions are too basic or if this is the wrong section but I am new to GitHub too. So here are my questions:
> 
>     1. I don't understand how to create an equation which is not a simple sum of the terms in the "term table".
>        For example, if we call phi, phi2 our unknown variables and I want to solve the Laplace equation with dw_laplace(s, f(phi,phi2),_) where f(phi,phi2)=phi_phi2/(sqrt(1+phi**2) (it is just an example to ask how to do operations with the variables on sfepy, I don't even know if the equation makes sense). How do I do that?

This is not possible in sfepy - the equations have to be simple sums of terms. Maybe try a package  that supports full symbolic evaluation, such as FEniCS? (In SfePy, you would need to add a new nonlinear term, which is not trivial.)

>     2. always related to the previous question, after solving the solutions for example in 3D, how do I process the variables for calculating other equations?

Check [the Primer](https://sfepy.org/doc-devel/primer.html).

>     3. is it possible to create a domain which is just 2 different 3d rectangular boxes connected to each other, without using any CAD software?

If the two meshes match at the connection, then yes, you can use simple add them (`mesh = mesh1 + mesh2`), see also [gen_extended_block_mesh() source](https://sfepy.org/doc-devel/_modules/sfepy/mesh/mesh_generators.html#gen_extended_block_mesh).
