### ISSUE TITLE
CI disabled (AppVeyor build is broken)

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#893]
The AppVeyor build is broken due to a too long path error (cf. https://github.com/cython/cython/issues/4202), so I will disable it until a solution is found.

**Comment by flothesof** [comment]
Maybe it is time to use Github CI? This is what many packages are now using... Apparently it allows CI under Windows, Mac and Linux at the same time.

**Comment by rc** [comment]
Yes, and numpy or scipy setups could serve as an inspiration. However I do not feel like setting up all the github action machinery by myself at the moment.

**Comment by flothesof** [comment]
You’ll find a PR regarding this topic here: #910

**Comment by flothesof** [comment]
I’m happy to see the CI seems to work since you merged the PR :)

**Comment by rc** [comment]
Yes, I forgot to close this. Thanks!
