### ISSUE TITLE
ev_surface_flux gives wrong values in some surfaces

### ISSUE THREAD

**Issue by peppe988** [sfepy/sfepy#899]
Dear Sfepy community, I am having some problems calculating the flux of a given quantity through a surface. When I calculate the flux on the left or the right of the block I get the right result, while if I calculate that on the centre it gives me the wrong value, as you can see in the image the calculation on the left boundary is equal to the predicted one, on the central one not:

![Current](https://user-images.githubusercontent.com/116461547/203340024-14048491-842b-4365-a4f0-733a76009bed.png)

I think it is a problem with how the surface is defined in the centre because I have tried to calculate the terms that enter in "ev_surface_flux" separately and they are right both in the centre and the extremes.

In order to give you more context, the equation I am simulating is (solving for \phi):
![image](https://user-images.githubusercontent.com/116461547/203345524-b060b93f-4d83-4782-a971-a614a3c63c5e.png)

and the quantity I want to calculate is:
![image](https://user-images.githubusercontent.com/116461547/203343048-d5af4bcf-ade8-4374-a9d0-1a13fd9e7331.png)
for the geometry I am using this quantity doesn't depend on y,z direction, so there wasn't the need to calculate the flux, however, since I will move to more complex geometries, I have defined it in a general way.

 Here is the part of the code I am talking about and I have also attached the whole code:
```

def post_process(out, problem, variables, extend=False):

    global kk
    global control
    kk=kk+1
    Current=0.
    if(kk==n_step):
        for n in range(N_freq):
            Current=Current + problem.evaluate('ev_surface_flux.i.Gamma_Left(Current_density.val_%s,phi_%s)'%(n,n),mode='eval',
             verbose=True)
            control=control +1

 
        with open("Current_phase_t=%s_tc_R=0.txt"%T, "a") as f:

            Current=-Current.imag

            f.write('%f %f'%(Current,delta1) + '\n')

    return out

def Current_density(ts, coors, problem, equations=None, mode=None, **kwargs):

    if mode == 'qp':
        phi_values=[]
        phi_values_d=[]
        global val_current
        global control
        global c
        if (control == 0):
            for n in range(N_freq):
                phi_values.append(problem.evaluate('ev_integrate.i.Omega(phi_%s)'%n, mode='qp', verbose=True))


                val_current.append(np.exp(0.57721)*T/Tc*1./(w(n)**2+abs(phi_values[n])**2)
                *(np.conjugate(phi_values[n])))

                cc=val_current[n].shape[0] * val_current[n].shape[1]
                val_current[n].shape = (cc,1,1)

                val_current[n]=np.tile(val_current[n],(dim,dim))

                for k in range(cc):
                    for i in range(dim):
                        for j in range(dim):
                            if (i!=j):
                                val_current[n][k][i][j]=0

            for n in range(N_freq):
                c['val_%s'%n]= val_current[n]



  regions = {
      'Omega' : 'all',
      'Gamma_Left' : ('vertices in (x == -5)', 'facet'),
      'Gamma_Right' : ('vertices in (x == 5)', 'facet'),
      'Omega_1' : ('vertices in (x > -0.0001) & (x < 3) ',),
      'Gamma_Current': ('vertices in (x ==0)' , 'facet','Omega_1'),
  }


```
[Usadel_equation.zip](https://github.com/sfepy/sfepy/files/10068500/Usadel_equation.zip)

**Comment by peppe988** [comment]
HI robert, thank you for your questions, I will try to respond to each of them, but before this, I just want to tell you that the code is working infact I have compared the parameters \phi(w_n) with their analytical value and they coincide almost perfectly. The only problem I am having is that the current calculated with the term "ev_surface_flux" is completely wrong at the center. I have tried to calculate it with another code by probing my file.vtk and getting the various \phi(w_n), and I get the right result in the whole geometry (the current stays constant all over the mesh except minor corrections).

1) Yes the problem is that n in the definition of the delta coefficient runs over all the frequencies and the phi_n parameters. So for every w_n I have different phi_n and hence different equations (due to g(w_n)). Moreover, decreasing the temperature will require more and more frequencies, the theory behind this system is a disaster :-( ! 
2) yes
3) I will try that, I still need to study the package more in depth to learn how to do that, are there some instructions on the user's guide?
4) If I just leave True is a problem?
5) unfortunately I need a lot of frequencies.
6) Thank you.
7) I am trying to simulate how the current in a weak link (a type of josephson junction we want to use to create qubits, photon detectors etc..) depends on different parameters. So that before I nanofabricate it I know what materials, geometries etc.. to use.

**Comment by peppe988** [comment]
I do not exclude that the problem is in the way I have defined the Current's density in my code.

**Comment by rc** [comment]
> HI robert, thank you for your questions, I will try to respond to each of them, but before this, I just want to tell you that the code is working infact I have compared the parameters \phi(w_n) with their analytical value and they coincide almost perfectly. The only problem I am having is that the current calculated with the term "ev_surface_flux" is completely wrong at the center. I have tried to calculate it with another code by probing my file.vtk and getting the various \phi(w_n), and I get the right result in the whole geometry (the current stays constant all over the mesh except minor corrections).

So it seems the problem is really in the flux calculation. I wonder if, although physically nonsense, you could debug that with n_freq=1, just to get the (wrong) current constant?
 
>     1. Yes the problem is that n in the definition of the delta coefficient runs over all the frequencies and the phi_n parameters. So for every w_n I have different phi_n and hence different equations (due to g(w_n)). Moreover, decreasing the temperature will require more and more frequencies, the theory behind this system is a disaster :-( !
> 
>     2. yes
> 
>     3. I will try that, I still need to study the package more in depth to learn how to do that, are there some instructions on the user's guide?

Look at some examples with "interactive" in name, or examples that can be run standalone (e.g. sfepy/examples/linear_elasticity/dispersion_analysis.py, or sfepy/examples/multi_physics/thermal_electric.py - there are many.). I can help you with that.

>     4. If I just leave True is a problem?

No problem. Just that you see lots of output about term evaluation and the relevant output about the linear system convergence scrolls away :)


>     5. unfortunately I need a lot of frequencies.
> 
>     6. Thank you.
> 
>     7. I am trying to simulate how the current in a weak link (a type of josephson junction we want to use to create qubits, photon detectors etc..) depends on different parameters. So that before I nanofabricate it I know what materials, geometries etc.. to use.

Magic!

**Comment by peppe988** [comment]
ok I have tried the debugging procedure. This is how phi varies in my geometry ( as you can see I have also plotted the analytical values and they coincide, that it is because when you suppose L=0, Delta doesn't matter so you get the right phi even with just one frequency)
![probed_phi](https://user-images.githubusercontent.com/116461547/204608257-7ba233df-4c75-4b29-b386-198021801b30.png)

then I have calculated the current as:
I=I+1/(w(n)**2+phi_real(x)**2+phi_imag(x)**2)*(phi_real(x)*phi_imag_dev(x))

I=I*T/Tc/(np.pi/2)*np.exp(0.57721)*2

where phi_imag_dev is the derivative of phi_imag (imaginary part of phi if it was not clear from the context) and I get the right value of the current along the domain (almost constant):
![Current_x_dependence](https://user-images.githubusercontent.com/116461547/204606889-8e1437d4-6d7d-47e7-ae67-0ca1cb7efbf9.png)
However the current calculated with the ev_surface term is 0.38286791 on the left and 0.27533487 on the center (always renormalized with I=I*T/Tc/(np.pi/2)*np.exp(0.57721)*2). So I think the problem can be caused by these 2 possibilities:
1) I have wrongly defined the surface at the center 
1) I have wrongly defined the current density wrongly

Thank you for your help! I will have a look at the examples you told me about.

**Comment by rc** [comment]
I have tried to put some debug output to `post_process()`:
```
            Current=Current + problem.evaluate('ev_surface_flux.i.Gamma_Left(Current_density.val_%s,phi_%s)'%(n,n),mode='eval',verbose=verbose)
            aa = problem.evaluate('ev_surface_flux.i.Gamma_Left(Current_density.val_%s,phi_%s)'%(n,n),mode='eval',verbose=verbose)
            bb = problem.evaluate('ev_surface_flux.i.Gamma_Right(Current_density.val_%s,phi_%s)'%(n,n),mode='eval',verbose=verbose)
            cc = problem.evaluate('ev_surface_flux.i.Gamma_Current(Current_density.val_%s,phi_%s)'%(n,n),mode='eval',verbose=verbose)
            print(aa, bb, cc)
```
because apparently some global state changes between calls to material update functions.
I do not know how to debug the code without first untangling it - the global variables are evil :)

**Comment by peppe988** [comment]
I am really sorry, you are right. I will try to explain what my evil mind thought when creating them.
Basically:
1) "kk" is a global variable I have created so that I calculate the current only at the very last step because at that point I am  sure the solution converged.
2) "control" is there so that the function "Current_density" doesn't have to evaluate again all the phi_n and calculate the term np.exp(0.57721)*T/Tc*1./(w(n)**2+abs(phi_values[n])**2)*(np.conjugate(phi_values[n])) which is stored in the global variable "c".
3) "val_current" defined as a global is horrific. I have modified the code 100 times and I guess I have kept it from an old debugging experiment.

Again sorry, you were super helpful, I don't want to bother you further.

**Comment by rc** [comment]
Ad 1. you can access the time-stepping info via `problem.ts` - just check `step`. In the material functions you have `ts` directly.

No problem, feel free to ask!

**Comment by peppe988** [comment]
@rc thank you, I have solved the problem. 
I got rid of all the global variables and instead of using
`problem.evaluate('ev_integrate.i.Omega(phi_%s)'%n, mode='qp', verbose=True)`
I have used 
`vt = problem.get_variables()['phi_%s'%n];`
`vt.evaluate_at(coors,mode='val')`
and for some reason I get the right flux

**Comment by rc** [comment]
OK, glad to hear that you solved the issue.

On the other hand, I am curious why the two ways give different results. As long as the variables contain the same data, and coors correspond to the coordinates of the quadrature points (in the physical domain), the results should be the same. See 
`test_invariance_qp()` in `sfepy/tests//test_mesh_interp.py`. Check
```
pytest sfepy/tests//test_mesh_interp.py -k invariance_qp -vs
```

**Comment by peppe988** [comment]
That's what I got


=============================== warnings summary ===============================
tests/test_mesh_interp.py::test_invariance_qp
tests/test_mesh_interp.py::test_invariance_qp
  /Users/giuseppecolletta/opt/anaconda3/lib/python3.9/site-packages/tables/__init__.py:24: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
    from .utilsextension import (

tests/test_mesh_interp.py::test_invariance_qp
  /Users/giuseppecolletta/opt/anaconda3/lib/python3.9/site-packages/tables/req_versions.py:20: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    min_numpy_version = LooseVersion('1.9.3')

tests/test_mesh_interp.py::test_invariance_qp
  /Users/giuseppecolletta/opt/anaconda3/lib/python3.9/site-packages/tables/req_versions.py:21: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    min_numexpr_version = LooseVersion('2.6.2')

tests/test_mesh_interp.py::test_invariance_qp
  /Users/giuseppecolletta/opt/anaconda3/lib/python3.9/site-packages/tables/req_versions.py:22: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    min_hdf5_version = LooseVersion('1.8.4')

tests/test_mesh_interp.py::test_invariance_qp
  /Users/giuseppecolletta/opt/anaconda3/lib/python3.9/site-packages/tables/req_versions.py:23: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    min_blosc_version = LooseVersion("1.4.1")

tests/test_mesh_interp.py::test_invariance_qp
  /Users/giuseppecolletta/opt/anaconda3/lib/python3.9/site-packages/tables/req_versions.py:24: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    min_blosc_bitshuffle_version = LooseVersion("1.8.0")

tests/test_mesh_interp.py::test_invariance_qp
  /Users/giuseppecolletta/opt/anaconda3/lib/python3.9/site-packages/tables/filters.py:27: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    blosc_version = LooseVersion(tables.which_lib_version("blosc")[1])

tests/test_mesh_interp.py::test_invariance_qp
  /Users/giuseppecolletta/opt/anaconda3/lib/python3.9/site-packages/tables/tests/common.py:36: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    hdf5_version = LooseVersion(tables.hdf5_version)

tests/test_mesh_interp.py::test_invariance_qp
  /Users/giuseppecolletta/opt/anaconda3/lib/python3.9/site-packages/tables/tests/common.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    blosc_version = LooseVersion(tables.which_lib_version("blosc")[1])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================= 1 passed, 5 deselected, 10 warnings in 2.10s ================

**Comment by peppe988** [comment]
In all the other functions `problem.evaluate(...)` works fine, maybe is something related to `np.tile()` in Current density that creates problems?

**Comment by rc** [comment]
So the test passes (the distutils-related warnings can be ignored). If you want, attach your current script so that I can run it and have a look. In the script I have there is no `np.tile()` call that should influence the `problem.evaluate(...)` calls.

**Comment by peppe988** [comment]
Sure! you can run it as it is, I have just used one frequence . As for np.tile() you are right I was thinking of an old version of my code
[Usadel_equation.zip](https://github.com/sfepy/sfepy/files/10261177/Usadel_equation.zip)

**Comment by rc** [comment]
I see. You are using the material parameter `Current_density.val_%s` in `post_process()`, where you integrate over `Gamma_Current` region. So the `coors` passed into `Current_density()` are the physical quadrature point coordinates in the `Gamma_Current` region, but in the `problem.evaluate(...)` call you get the values from the whole domain `Omega`. If you fix the integration domain, you get the same results (after a reshape):
```
In [5]: phi_val2 = problem.evaluate('ev_integrate.i.Gamma_Current(phi_%s)'%n, mode='qp', verbose=True)
In [6]: phi_val2.shape = phi_val.shape
In [7]: np.linalg.norm(phi_val - phi_val2)
Out[7]: 6.280369834735101e-16
```

**Comment by peppe988** [comment]
Oh that was it. Thank you for all the help!
