### ISSUE TITLE
Unit for density in Material object

### ISSUE THREAD

**Issue by lucascbarbosa** [sfepy/sfepy#901]
Hello, I'd like to know what is the unit for density in Material object. I have a material with  density of 700 kg/m³, so I define rho as 700?

**Comment by rc** [comment]
The units are up to you but they need to be consistent. So I recommend using the basic SI units, just like you wrote, i.e.
- length: m
- mass: kg
- stiffness / stress: Pa
- density: kg / m^3

**Comment by rc** [comment]
Closing answered questions with no further reaction...
