### ISSUE TITLE
reduce verbosity of some parts of the sfepy loop

### ISSUE THREAD

**Issue by flothesof** [sfepy/sfepy#903]
Hi,
I’m trying to make a sfepy standalone app in the transient case described in #898.
Sfepy is by default very verbose. I would like sfepy to only print timestep information.
Is that possible? 
I’ve managed to reduce verbosity to zero using the following:
```
from sfepy.base.base import output

output.set_output(quiet=True)
``` 
Is it possible to extend this and to select the kind of information that is printed?

Thanks,
Cheers
Florian

**Comment by flothesof** [comment]
Actually, I found a workaround. Since I use a step hook function, I added the output specifically at that stage.

```python
def step_hook(pb, ts, variables):
    """This hook is called at each time-step of the solver."""
    output.set_output(quiet=False)
    output(f"time step: {ts.step + 1}/{ts.n_step}")
    output.set_output(quiet=True)
```

**Comment by rc** [comment]
FWIW: You correctly found the quiet setting. There is not much else, only some function (e.g. Problem.evaluate()) have `verbose` argument that can be used for a finer control.
