### ISSUE TITLE
test on splinebox.py fails

### ISSUE THREAD

**Issue by pnavidi** [sfepy/sfepy#932]
the method used to minimize has an option with keyword "xtol" which should be replaced by "xatol"
            ts[ii] = minimize(lambda x: ptdist(x, ic, self), x0,
                              method='nelder-mead',
                              options={'xatol': 1e-5, 'disp': False}).x

**Comment by rc** [comment]
Thanks for the report! Try upgrading sfepy - it is fixed from the 2022.3 release.

**Comment by pnavidi** [comment]
thx
