### ISSUE TITLE
Setting material properties with values of previous simulation

### ISSUE THREAD

**Issue by NoelGK** [sfepy/sfepy#933]
Hi,

I am trying to develop a model of pollutant propagation that takes into account wind speed and direction. For this purpose, I first create a simulation of Navier-Stokes equations to obtain the wind vector map and then I am trying to import the obtained values into a script that solves time independent convection-diffusion equation.

$$
0 = \nabla (D \nabla c) - \nabla \cdot (\mathbf{v} c) + R
$$

where $\mathbf{v}$ are the wind values obtained before.

My problem comes when trying to map the coordinates given by sfepy with the values of the obtained .vtk file.

```
import numpy as np
import meshio as ms

filename_mesh = '../path-to-problem-mesh'

''' In this part I load the values of wind obtained in the previous simulation. "wind_points" are the points of the mesh (the same in both files) and "u" the actual values. '''

wind_file = './path-to-previous-simulation-output'
mesh = ms.read(wind_file)
wind_points = mesh.points
u = mesh.point_data['u']

.
.
.
""" Bunch of configuration parameters for sfepy """
.
.
.

materials = {
    'u': 'get_wind',
}

def get_wind(ts, coors, mode=None, **kwargs):
    x, y = coors[:, 0], coors[:, 1]
    z = np.zeros(x.shape)
    qp = np.stack([x, y, z], axis=1)
    condition = np.all(np.isclose(wind_points, qp), axis=1)
    return {'wind': u[np.where(condition)]}

functions = {
    'get_wind': (get_wind, ),
}
```

When I try to run the simulation, I get the following error in `get_wind`

> ValueError: operands could not be broadcast together with shapes (6068,3) (21831,3) 

I do not fully understand the implementation of finite elements, thus I thoguht that the parameter `coors` corresponded to the center of the cells in the mesh. Now, since the length of `coors` is way bigger than the number of points in the mesh, I suspect I was wrong.

Is sfepy providing the coordinates of the **vertices** of each cell, instead of the centers?

How can I achieve my purpose of importing the results of another simulation into the script as a function?

Thank you.

**Comment by rc** [comment]
Hi @NoelGK,

`coors` in the material function correspond to the quadrature points inside each cell.

As for the contents of your Navier-Stokes results file, it depends - the primary (unknown) variables are stored in the mesh vertices, while derived quantities (e.g. stresses, fluxes) are usually averaged per each cell. Note also that for approximation orders > 1, the extra degrees of freedom are not saved by default.

For your use, I would not go via a VTK file. Try saving the velocities directly into a file (e.g. using `np.save()`). Then in your second simulation you could define an auxiliary variable as `parameter field` (see [sfepy/examples/navier_stokes/stokes_slip_bc.py](sfepy/examples/navier_stokes/stokes_slip_bc.py)), which could be evaluated in the quadrature points in your function.

**Comment by NoelGK** [comment]
Hi @rc,

First of all, thank you for your quick response. I am trying to implement it as you sugested, and I have a quick doubt that maybe you could answer. Again, I am sorry if this is really basic FE stuff.

When I save the .npy, the result is an array, lets call it `wind`, of shape (7277, 6, 2, 1). On the other hand, the shape of `coors` array is (21831, 2). Since 21831 = 7277 * (6 / 2), I know that this is related somehow. My question is how the `coors` array is structurally related to the values of `wind`.

Thank you very much for your help.

**Comment by rc** [comment]
How have you got the `wind` array in your NS simulation? This shape indicates that it is in quadrature points. It is a 2D simulation, right? Do you use the same approximation orders/quadratures of the velocity in the two simulations?

**Comment by NoelGK** [comment]
Okey I think it is solved. The problem was the approximation orders, that were different from one simulation to another (I didn't know that the quadrature points gere generated based on that). 

The only thing I'm missing is a term like

$$
\nabla(\mathbf{v} c)
$$

but where $\mathbf{v}$ has a nonzero divergence (since the only similar thing I have seen in the docs is the `dw_advect_div_free` term, which has a vanishing divergence for the velocity.

**Comment by NoelGK** [comment]
My NS equations are incompressible, so in theory that ends the problem. Thank you very much for your help!!!

**Comment by rc** [comment]
FWIW you can verify the incompressibility by evaluating div(v)... It is enforced only in the integral (weak) sense of FEM.
