### ISSUE TITLE
move modal_analysis script to gallery?

### ISSUE THREAD

**Issue by flothesof** [sfepy/sfepy#942]
Hi,
I really like the modal analysis script that is in the linear elasticity folder (sfepy\examples\linear_elasticity\modal_analysis.py).
I think it’s an example that should have it’s spot in the gallery.
I contributed something to pyvista that was similar to what the script does (https://docs.pyvista.org/examples/99-advanced/warp-by-vector-eigenmodes.html#sphx-glr-examples-99-advanced-warp-by-vector-eigenmodes-py).

What would it take to make the script generating a gallery entry? I would be willing to contribute this.

Cheers,
Florian

**Comment by rc** [comment]
Currently the gen_gallery.py script does not support the interactive examples. But it should be fixable - for each such example there could be defined a command with options to run and another command (or just a file name) to make the image. It is on my todo list for a long time... (nice pyvista example btw.)

**Comment by rc** [comment]
Done.
