### ISSUE TITLE
error whit boundaries between overlapping volumes

### ISSUE THREAD

**Issue by peppe988** [sfepy/sfepy#948]
Dear sfepy community, 
I am having a problem whit 3-dimensional domains of different materials. I have seen in some examples that the way to deal with boundary conditions within part of the domain is to do something like in [https://sfepy.org/doc-devel/examples/acoustics-acoustics3d.html](url):
regions = {
    'Omega' : 'all',
    'Omega_1' : 'cells of group 1',
    'Omega_2' : 'cells of group 2',
    'Gamma_12' : ('r.Omega_1 *v r.Omega_2', 'facet'),
    'Gamma_12_1' : ('copy r.Gamma_12', 'facet', 'Omega_1'),
    'Gamma_12_2' : ('copy r.Gamma_12', 'facet', 'Omega_2'),
    'Gamma_in' : ('vertices in (z < 0.001)', 'facet'),
    'Gamma_out' : ('vertices in (z > 0.157)', 'facet'),
}

I was trying to do the same with my model which is this:
[Sfepy-issue.zip](https://github.com/sfepy/sfepy/files/10804463/Sfepy-issue.zip)

But using the same notation "cells of group 1": I get "the region has no entities!" error, while if I use "vertices of group 1" notation I get just the internal vertices of the volume and not the vertices on the boundary surfaces and so I cannot define the boundary between internal volumes as in " 'Gamma_12' : ('r.Omega_1 *v r.Omega_2', 'facet')," since in this way the 2 internal volumes do not overlap.

I have tried defining it manually since they are just boxes using this:
regions = {
    'Omega' : 'all',
    'Omega_bridge_1' : ('vertices in (x > -4.25) & (x<4.25)& (z<4.5) & (y<2.25) & (y>-2.25) ',),
    'Omega_bridge' : ('vertices in (x >= -6.25) & (x<=6.25)& (z<=4.5) & (y<=2.25) & (y>=-2.25) ',),
    'Omega_left_1' : ('vertices in (x > -62.26) & (x<=-2.25) ',),
    'Omega_right_1' : ('vertices in (x >= 2.25) & (x<62.26) ',),
    'Omega_right':('r.Omega_right_1 -v r.Omega_bridge_1',),
    'Omega_left':('r.Omega_left_1 -v r.Omega_bridge_1'),
    'Gamma_Left' : ('vertices in (x == -62.25)', 'facet'),
    'Gamma_Right' : ('vertices in (x == 62.25)', 'facet'),
    'Gamma_left_bridge_1' : ('r.Omega_left *v r.Omega_bridge','facet'),
    'Gamma_right_bridge_1' : ('r.Omega_right *v r.Omega_bridge','facet'),
    'Gamma_left_bridge' : ('copy r.Gamma_left_bridge_1', 'facet', 'Omega_left'),
    'Gamma_right_bridge' : ('copy r.Gamma_right_bridge_1', 'facet', 'Omega_right'),
    'Gamma_bridge_left' : ('copy r.Gamma_left_bridge_1', 'facet', 'Omega_bridge'),
    'Gamma_bridge_right' : ('copy r.Gamma_right_bridge_1', 'facet', 'Omega_bridge'),
    'Omega_1' : ('vertices in (x > -0.5) & (x<2) ',),
    'Gamma_Current': ('vertices in (x > -0.5) & (x<0.1)' ,'facet','Omega_1'),
}

And even if on paraview the boundaries and volumes are correct I get this error when I run the code: 
"shape mismatch: indexing arrays could not be broadcast together with shapes (28,3) (44,3) "
So it seems like some vertices are counted 2 times (at least I think so). From another issue I have seen that the best way to create a mesh is to follow these guidelines: [http://sfepy.org/doc-devel/preprocessing.html#multipart-models](url), but I don't understand why if I create my mesh directly on gmsh It does not work.

**Comment by rc** [comment]
The number in `'cells of group 1'` refers to the cell group number in your mesh. It seems that those number are 55-59 in your case, see the screenshot (`sfepy-view Sfepy-example.mesh --camera-position="-18.9528,-115.387,-186.587,0,0,15,0.279793,-0.844325,0.45698" -o mesh.png --off-screen`).

![mesh](https://user-images.githubusercontent.com/44282/220654062-7b7a2736-e7ea-49c2-817a-398e0e9ff8a5.png)

But why you error is not `ValueError: cell group 1 does not exist`? Maybe attach a minimal example than can be run.

**Comment by peppe988** [comment]
sure!
[sfepy_issue_2.zip](https://github.com/sfepy/sfepy/files/10805549/sfepy_issue_2.zip)
 this is the error I am getting is this: "shape mismatch: indexing arrays could not be broadcast together with shapes (575,3) (392,3) "

The code is just an example it does not make physical sense!

**Comment by peppe988** [comment]
I accidentally removed the post process_hook to check the regions: here is the correct version:
[sfepy_isuue_3.zip](https://github.com/sfepy/sfepy/files/10805716/sfepy_isuue_3.zip)
If you remove the jump terms you can see that the regions are correct

**Comment by rc** [comment]
- If you run
```
sfepy-run sfepy-example.py --save-regions --solve-not
```
and have a look at e.g. `Gamma_left_bridge_1` you will notice faces in the interface that do not belong there. This is because the intersection is based on vertices (`*v`). You need to use `*f` (faces) of `*s` (facets) intersection. However that is not all.
- There was a bug in the `copy` keyword - it did not preserve the region kind, so the extra faces appeared again. This is now fixed in the git version (#950).
- Finally, although with the above changes the code runs, it seems that the Omega_left and Omega_right are not well connected to the bridge - again check the saved region meshes, or run
```
sfepy-view work/people/peppe988/i948/Sfepy-example.mesh --opacity=0.3 -e
```
The inner surfaces visible there are IMO disconnected. Is that possible?

**Comment by peppe988** [comment]
Actually, with (`*v`) it seems that I am obtaining the proper boundaries while with ('*s') some surfaces are missing. However, if there are connection problems I think I can play with the meshes option on gmsh, it is not a problem. 
Thanks for solving the bug I think it will work now.
 Can I ask you how to install this latest version?

**Comment by peppe988** [comment]
I have checked better the surfaces obtained with (`*v`) and as you said there are strange spikes inside:
<img width="1007" alt="Schermata 2023-02-23 alle 00 05 49" src="https://user-images.githubusercontent.com/116461547/220792157-79d7670d-bdb3-4e1f-a8b8-6a459e3e4c07.png">

But if I use `*s` or `*f` even if the spikes problem is solved some surfaces are completely cancelled:
<img width="1007" alt="Schermata 2023-02-23 alle 00 05 17" src="https://user-images.githubusercontent.com/116461547/220792407-fd74b42e-0848-4abd-b1a3-ad35f7cfbb2e.png">

**Comment by rc** [comment]
On 2/23/23 01:08, peppe988 wrote:
> I have checked better the surfaces obtained with (`*v`) and as you said there are strange spikes inside:
> <img width="1007" alt="Schermata 2023-02-23 alle 00 05 49" src="https://user-images.githubusercontent.com/116461547/220792157-79d7670d-bdb3-4e1f-a8b8-6a459e3e4c07.png">

Yes, that is because the region is given by the vertices, and those surplus 
faces actually have their vertices in the non-convex region.

> But if I use `*s` or `*f` even if the spikes problem is solved some surfaces are completely cancelled:
> <img width="1007" alt="Schermata 2023-02-23 alle 00 05 17" src="https://user-images.githubusercontent.com/116461547/220792407-fd74b42e-0848-4abd-b1a3-ad35f7cfbb2e.png">
> 

That is why I think that the meshes are not connected - exactly where the faces 
are missing.

**Comment by rc** [comment]
> If there are connection problems I think I can play with the meshes option on gmsh, it is not a problem. Thanks for solving the bug I think it will work now. Can I ask you how to install this latest version, so that I can test my code?

If you do not want to clone the repository using git, try
```
pip install https://github.com/sfepy/sfepy/archive/refs/heads/master.zip
```

**Comment by peppe988** [comment]
ok, thanks maybe there is a problem with the meshing algorithm when connecting the transfinite mesh of the bridge and Omega_left/right because if you just look at the vertices generated with `*v` saving the region as a vtk file they are correct, but some of them are internally connected with these surplus faces. I will try to create a better CAD model instead of just adding lines and points :-).

Sorry for deleting the previous comment I was generating the images before installing the new version and I thought it would have been solved with the update. Is there a way to restore it?

Thank you for the help!

**Comment by rc** [comment]
I do not know how to un-delete the comment. I can try forwarding the e-mail version here?

**Comment by peppe988** [comment]
don't worry, it was just in case other people find this conversation, but it is already clear enough since you quoted it in the previous messages

**Comment by peppe988** [comment]
I get this error: `ERROR: Could not build wheels for sfepy, which is required to install pyproject.toml-based projects` 
when using this command: `pip install https://github.com/sfepy/sfepy/archive/refs/heads/master.zip`

I am using anaconda if this helpful

**Comment by rc** [comment]
I think this means some dependency version mismatch. Maybe try downloading `https://github.com/sfepy/sfepy/archive/refs/heads/master.zip`, unpack it and follow [this](http://sfepy.org/doc-devel/installation.html#compilation-of-c-extension-modules).

**Comment by peppe988** [comment]
Ok solved the problem, I had to install it in an environment with python 3.7 and mine was 3.9. I have also changed the mesh and the boundary surfaces are all correct now. Thanks, I will close the issue!
