### ISSUE TITLE
more than 1400 Warning at libTest

### ISSUE THREAD

**Issue by Thomas-GT40** [sfepy/sfepy#986]
I'm under the water, please help me.
i followed all the tutorials, i even reset my pc, and always the same.

1. I install gcc with mingw64
2. I install visual studio code (CbuildTools)
3. I install python (3.11)
4. pip install numpy
5. pip install cython
6. pip install sfepy
7. pip install pytest

and then i do the test and obtain this :

================================================== warnings summary ===================================================
tests/test_cmesh.py: 1 warning
tests/test_declarative_examples.py: 990 warnings
tests/test_dg_field.py: 11 warnings
tests/test_dg_terms_calls.py: 2 warnings
tests/test_ed_solvers.py: 3 warnings
tests/test_eigenvalue_solvers.py: 1 warning
tests/test_elasticity_small_strain.py: 9 warnings
tests/test_functions.py: 2 warnings
tests/test_high_level.py: 2 warnings
tests/test_homogenization_perfusion.py: 4 warnings
tests/test_hyperelastic_tlul.py: 381 warnings
tests/test_laplace_unit_disk.py: 2 warnings
tests/test_laplace_unit_square.py: 10 warnings
tests/test_lcbcs.py: 5 warnings
tests/test_linear_solvers.py: 1 warning
tests/test_mesh_interp.py: 4 warnings
tests/test_mesh_smoothing.py: 2 warnings
tests/test_msm_laplace.py: 1 warning
tests/test_msm_symbolic.py: 1 warning
tests/test_poly_spaces.py: 1840 warnings
tests/test_projections.py: 3 warnings
tests/test_refine_hanging.py: 84 warnings
tests/test_term_call_modes.py: 2892 warnings
tests/test_term_consistency.py: 4 warnings
tests/test_term_sensitivity.py: 87 warnings
tests/test_volume.py: 5 warnings
  C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\linalg\utils.py:71: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(nm.__version__) >= '1.8':

tests/test_cmesh.py: 1 warning
tests/test_declarative_examples.py: 991 warnings
tests/test_dg_field.py: 11 warnings
tests/test_dg_terms_calls.py: 2 warnings
tests/test_ed_solvers.py: 3 warnings
tests/test_eigenvalue_solvers.py: 1 warning
tests/test_elasticity_small_strain.py: 9 warnings
tests/test_functions.py: 2 warnings
tests/test_high_level.py: 2 warnings
tests/test_homogenization_perfusion.py: 4 warnings
tests/test_hyperelastic_tlul.py: 381 warnings
tests/test_laplace_unit_disk.py: 2 warnings
tests/test_laplace_unit_square.py: 10 warnings
tests/test_lcbcs.py: 5 warnings
tests/test_linear_solvers.py: 1 warning
tests/test_mesh_interp.py: 4 warnings
tests/test_mesh_smoothing.py: 2 warnings
tests/test_msm_laplace.py: 1 warning
tests/test_msm_symbolic.py: 1 warning
tests/test_poly_spaces.py: 1840 warnings
tests/test_projections.py: 3 warnings
tests/test_refine_hanging.py: 84 warnings
tests/test_term_call_modes.py: 2892 warnings
tests/test_term_consistency.py: 4 warnings
tests/test_term_sensitivity.py: 87 warnings
tests/test_volume.py: 5 warnings
  C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    other = LooseVersion(other)

tests/test_conditions.py: 4 warnings
tests/test_declarative_examples.py: 1068 warnings
tests/test_domain.py: 20 warnings
tests/test_ed_solvers.py: 64 warnings
tests/test_elasticity_small_strain.py: 6 warnings
tests/test_functions.py: 4 warnings
tests/test_high_level.py: 2 warnings
tests/test_homogenization_perfusion.py: 28 warnings
tests/test_hyperelastic_tlul.py: 66 warnings
tests/test_laplace_unit_square.py: 6 warnings
tests/test_lcbcs.py: 14 warnings
tests/test_linear_solvers.py: 10 warnings
tests/test_linearization.py: 72 warnings
tests/test_mesh_generators.py: 10 warnings
tests/test_mesh_interp.py: 100 warnings
tests/test_mesh_smoothing.py: 2 warnings
tests/test_meshio.py: 34 warnings
tests/test_msm_laplace.py: 6 warnings
tests/test_msm_symbolic.py: 12 warnings
tests/test_projections.py: 4 warnings
tests/test_refine_hanging.py: 28 warnings
  C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\discrete\fem\meshio.py:460: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(meshiolib.__version__) >= LooseVersion('4.0.3') and\

tests/test_declarative_examples.py: 4 warnings
tests/test_homogenization_perfusion.py: 14 warnings
  C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\discrete\fem\mesh.py:239: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint32 will fail in the future.
  For the old behavior, usually:
      np.array(value).astype(dtype)`
  will give the desired result (the cast overflows).
    cmesh = cmesh_in.create_new(region.cells, region.tdim,

tests/test_declarative_examples.py: 10 warnings
tests/test_ed_solvers.py: 4 warnings
  C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function MUMPSSolver.__del__ at 0x0000025BD7F06840>

  Traceback (most recent call last):
    File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\solvers\ls.py", line 864, in __del__
      self.clear()
    File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\solvers\ls.py", line 832, in clear      if self.mumps_ls is not None:
         ^^^^^^^^^^^^^
  AttributeError: 'MUMPSSolver' object has no attribute 'mumps_ls'

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_declarative_examples.py::test_examples[acoustics/vibro_acoustic3d.py]
  C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\discrete\fem\mesh.py:246: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint32 will fail in the future.
  For the old behavior, usually:
      np.array(value).astype(dtype)`
  will give the desired result (the cast overflows).
    cmesh = cmesh_in.create_new(region.facets, region.tdim - 1,

tests/test_declarative_examples.py::test_examples[linear_elasticity/linear_elastic_up.py]
  C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function MUMPSSolver.__del__ at 0x0000025BD7F06840>

  Traceback (most recent call last):
    File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\solvers\ls.py", line 864, in __del__
      self.clear()
    File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\solvers\ls.py", line 832, in clear      if self.mumps_ls is not None:
         ^^^^^^^^^^^^^
  AttributeError: 'SchurMumps' object has no attribute 'mumps_ls'

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_declarative_examples.py::test_examples[multi_physics/biot_short_syntax.py]
  C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\solvers\ls.py:359: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(sp.__version__) >= '1.4.0':

tests/test_linear_solvers.py::test_solvers
  C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function MUMPSSolver.__del__ at 0x0000025BD7F06840>

  Traceback (most recent call last):
    File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\solvers\ls.py", line 418, in __init__
      import pyamg
  ModuleNotFoundError: No module named 'pyamg'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\tests\test_linear_solvers.py", line 201, in test_solvers
      problem.init_solvers(status=status,
    File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\discrete\problem.py", line 1147, in init_solvers
      ls = Solver.any_from_conf(ls_conf, context=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\solvers\__init__.py", line 30, in any_from_conf
      return solver_table[conf.kind](conf, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\solvers\ls.py", line 421, in __init__
      raise ImportError(msg)
  ImportError: cannot import pyamg!

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\solvers\ls.py", line 864, in __del__
      self.clear()
    File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\solvers\ls.py", line 832, in clear      if self.mumps_ls is not None:
         ^^^^^^^^^^^^^
  AttributeError: 'MUMPSSolver' object has no attribute 'mumps_ls'

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================================== 208 passed, 14291 warnings in 457.63s (0:07:37) ===================================

**Comment by rc** [comment]
Those warnings seem to originate mostly from missing optional packages. The tests pass, so you can ignore the warnings.

The `AttributeError: 'MUMPSSolver' object has no attribute 'mumps_ls'` will be fixed soon, thanks for the report!

**Comment by Thomas-GT40** [comment]
thanks a lot for your quick response, but after that, i have problems with basics commande, like : 
mesh = Mesh.from_file('poutre.msh') (where poutre.msh is a tetrahedral mesh of a beam from gmsh)

i obtain this :   

--------------------------------------------------------------------------------------------------------------------------------------------
File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\discrete\fem\mesh.py", line 219, in from_file
    mesh = io.read(mesh, omit_facets=omit_facets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\40\AppData\Local\Programs\Python\Python311\Lib\site-packages\sfepy\discrete\fem\meshio.py", line 421, in read
    cgdata0[m.cell_sets[k][ic]] = cgrps[ik]
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^
IndexError: index 8 is out of bounds for axis 0 with size 1
 -------------------------------------------------------------------------------------------------------------------------------------------

It's even weirder when beside that, the command mesh = meshio.read("poutre.mesh") work perfectly fine.
Thanks again for your answer.

**Comment by rc** [comment]
This is a meshio issue. SfePy forces its version to be 4.4.6 (this needs to be updated...), so maybe it is already fixed upstream. In any case, try using another format that works for the moment.

**Comment by Thomas-GT40** [comment]
It looks like to work better.
I take a mesh example from the SfePy github.
I compared both files, and turned out that gmsh export the mesh in the same format, but without exactly the same syntax.
To continues my work, I think I will code a converter tool between gmsh or tetgen to the right mesh files format expected for sfepy. If you want, I'll keep you in touch.
Thanks again for your work and your responses.

**Comment by Thomas-GT40** [comment]
The error that i sent to you was the msh format, but there is also a probleme the mesh format of gmsh.
At the beginning of the file from gmsh (mesh) it begins exactly like the mesh from your GitHub (block.mesh), but there are some differences, like edges definition. I think i will just cut the useless part of the file. 
(PS: I used the app gmsh from the website, not gmsh in python, maybe it make a difference).

**Comment by rc** [comment]
FWIW: The `-3` option in 3D or `-2` in 2D should ensure that the mesh contains only the cells, not lower dimensional entities.

**Comment by rc** [comment]
The `-3` is a gmsh option, you can generate the mesh from the command line using:
```
gmsh -3 -format mesh -o result.mesh geometry.geo
```
where the `.geo` file is the geometry saved by gmsh.

**Comment by Thomas-GT40** [comment]
yep, for the -3, and about the sfepy-view ? 
I'm trying using directly the script resview.py but i'm not familiar with the code, and i didn't found any solution for the moment.
If you have the solution, it should be great :). 
Thanks

**Comment by rc** [comment]
Can you run sfepy-view without arguments? What is your OS?

**Comment by Thomas-GT40** [comment]
No, it don't work with "sfepy-view linear_elasticity.vtk", again "Invalide Syntaxe". 
I'm on Windows.

**Comment by Thomas-GT40** [comment]
I'm using Pycharm, with the standard python environement. My final objective is to make an exe with all the dependencies in the same folder. I would like to make it clean to use it many time easily. It's why i'm not using anaconda.
Right now, the code "linear_elastic_interactive.py" look like to work (i don't have any error or warning).
But yes, still the probleme with sfepy-view, and the macro commande "sfepy-run" don't work either.

**Comment by rc** [comment]
OK. How did you install sfepy - with pip? Or from git sources?

Anyway, it should be possible to run the non-interactive examples using `python <path-to-sfepy>/scripts/simple.py` instead of `sfepy-run` and analogously `python <path-to-sfepy>/scripts/resview.py` instead of sfepy-view. Based on the terminal you use, you may need to use `python.exe` or `python3.exe` instead of `python`.

**Comment by Thomas-GT40** [comment]
I installed sfepy with pip. 
I still got invalid syntaxe for "python .../scripts/resview.py" even if i use python.exe or python3.exe instead.

When I execute the entire code without visualisation i obtain this :

sfepy:   number of vertices: 258
sfepy:   number of cells:
sfepy:     2_3: 454
sfepy: ...done in 0.01 s
sfepy: saving regions as groups...
sfepy:   Omega
sfepy:   Gamma1
sfepy:   Gamma2
sfepy: ...done
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.00 s
sfepy: matrix shape: (1815, 1815)
sfepy: assembling matrix graph...
sfepy: ...done in 0.00 s
sfepy: matrix structural nonzeros: 39145 (1.19e+00% fill)
sfepy: updating variables...
sfepy: ...done
sfepy: updating materials...
sfepy:     m
sfepy:     f
sfepy: ...done in 0.00 s
sfepy: nls: iter: 0, residual: 1.343114e+01 (rel: 1.000000e+00)
sfepy:   residual:    0.02 [s]
sfepy:     matrix:    0.00 [s]
sfepy:      solve:    0.01 [s]
sfepy: nls: iter: 1, residual: 2.650482e-14 (rel: 1.973386e-15)
sfepy: solved in 1 steps in 0.04 seconds
Nonlinear solver status:
 IndexedStruct
  condition:
    0
  err:
    2.650481656793139e-14
  err0:
    13.431138597204926
  ls_n_iter:
    -1
  n_iter:
    1
  time_stats:
    dict with keys: ['residual', 'matrix', 'solve']
Stationary solver status:
 IndexedStruct
  n_step:
    1
  time:
    0.0431111999996574

Process finished with exit code 0

So it's look like to work well beside the sfepy-view probleme.

**Comment by rc** [comment]
OK. Can you post the entire log of your sfepy-view invocation, including what/where you write and everything it prints?

**Comment by Thomas-GT40** [comment]
I use exactly the "Interactive Example: Linear Elasticity" found on sfepy.org.  and I put "! sfepy-view regions.vtk -2 --grid-vector1 "[2, 0, 0]"" at the the same place that the exemple. I tried with and without the "!" but nothing (invalide syntaxe).

**Comment by Thomas-GT40** [comment]
Yeii it work !
Sadly, not with sfepy built-in visualisation, but I read pyvista doc and I found how to visualize the result.
For the moment i succeed to visualize the displacement. :)
Now i'm trying to understand how to calculate the stress in this sample exemple and visualize them.
Thanks again for your rapid answers and your help.

**Comment by rc** [comment]
> pb.save_state('linear_elasticity.vtk', variables)
> 
> sfepy-view linear_elasticity.vtk

I see what is wrong. `sfepy-view` is a command that should be run in a terminal or in ipython (prefixed with '!'), not within the code.

If you want to visualize the results from Python, use either pyvista directly (like you did), or you can use the `pv_plot()` function from `sfepy.postprocess.resview`.
