### ISSUE TITLE
Implementing new non-linear terms and solve equations with nls.Newton

### ISSUE THREAD

**Issue by peppe988** [sfepy/sfepy#998]
Dear Sfepy, first of all, thank you, I have had a lot of fun running simulations and coding with your software in the last 6 months. Now, I'm eager to explore some more advanced features and I was wondering if there's a way for me to create my own non-linear terms. If that's possible, I'd greatly appreciate it if you could point me in the direction of any tutorials or resources that can help me do it properly. Thanks in advance!

**Comment by rc** [comment]
The description [here](http://sfepy.org/doc-devel/developer_guide.html#how-to-implement-a-new-term) is reasonably up-to-date, with the exception that nowadays we try to avoid C/Cython and implement also the evaluation function using NumPy. 

What kind of terms do you have in mind? There is a bunch of support code/classes that you could use in case of hyper-elasticity/large deformations in solid mechanics.

`register_term()` from `sfepy.terms` can be used to add a user term.

**Comment by peppe988** [comment]
Hi, thanks for the quick reply. I was trying to implement terms that in the strong form look like this (p is the state) :
\grad(f(p)\grad p) + g(p)=0 . where g and f are \frac{1}{\sqrt{1+p^2}} or \frac{1}{1+p^2}. I also have boundary conditions in which \grad(p)\cdot n=h(p). 

I am seeing now that the term dw_ns_dot_grad_s [NonlinearScalarDotGradTerm](http://sfepy.org/doc-devel/src/sfepy/terms/terms_dg.html#sfepy.terms.terms_dg.NonlinearScalarDotGradTerm) is similar to what I am looking for, so I guess I can modify it for my needs. Of course, if a term that does what I am looking for already exists no problem, if not, I have 1 question:
-will it just be a matter of modifying "out_qp = dot_sequences(bf_t, val_grad_qp, 'ATB')" by changing the dot_sequences or I am oversimplifying the problem?

**Comment by rc** [comment]
Yes, that's it. Instead of `dot_sequences()`,  which nowadays is just a helper around `@`, you might want to use `numpy.einsum()`.

**Comment by peppe988** [comment]
Ok, I had tried to implement the new term, but I was getting a mismatch error, so I decided to run an example code with the term [NonlinearScalarDotGradTerm](http://sfepy.org/doc-devel/src/sfepy/terms/terms_dg.html#sfepy.terms.terms_dg.NonlinearScalarDotGradTerm), following the example http://sfepy.org/doc-devel/examples/dg-burgers_2D.html#dg-burgers-2d. However, I get this error:
here is the example code:
[Sfepy_issue.zip](https://github.com/sfepy/sfepy/files/11691250/Sfepy_issue.zip)

```
Traceback (most recent call last):
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/bin/sfepy-run", line 8, in <module>
    sys.exit(main())
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/scripts/simple.py", line 330, in main
    app()
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/applications/application.py", line 29, in call_basic
    return self.call(**kwargs)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/applications/pde_solver_app.py", line 232, in call
    post_process_hook_final=self.post_process_hook_final)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/problem.py", line 1469, in solve
    status=status)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/solvers/ts_solvers.py", line 36, in _standard_ts_call
    status=status, **kwargs)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/solvers/ts_solvers.py", line 75, in __call__
    vec = nls(vec0)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/solvers/nls.py", line 260, in __call__
    vec_r = fun(vec_x)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/evaluate.py", line 78, in eval_residual
    vec_r = self.problem.equations.eval_residuals(vec)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/equations.py", line 675, in eval_residuals
    self.evaluate(mode='weak', dw_mode='vector', asm_obj=out)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/equations.py", line 608, in evaluate
    term_mode=term_mode, asm_obj=asm_obj)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/equations.py", line 833, in evaluate
    ret_status=True)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/terms/terms.py", line 1487, in evaluate
    fargs = self.call_get_fargs(_args, kwargs)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/terms/terms.py", line 1312, in call_get_fargs
    fargs = self.get_fargs(*args, **kwargs)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/terms/terms_dg.py", line 742, in get_fargs
    out_qp = dot_sequences(vg2.bfg, val_qp, 'ATB')
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/linalg/utils.py", line 457, in dot_sequences
    out = mtx @ vec
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

```
It is probably my fault since I do not understand why the functions in the tutorial I have linked use p[...,None] and then "p[-1]" in the equation. If you could explain this to me, It will be really helpful!

**Comment by rc** [comment]
To use `dw_ns_dot_grad_s`, the function f(p) must return a vector - see the [example](http://sfepy.org/doc-devel/examples/dg-burgers_2D.html#dg-burgers-2d).

Maybe send your original term and the error?

**Comment by peppe988** [comment]
Yes, sorry, the original error was the same as this one because I was just copy-pasting the source code of dw_ns_dot_grad_s. As you said, the mistake was not making f(p) a vector. So I have changed that, and now it works.

I am now trying to understand the right way to sum over the indices of the base functions, material functions, and so on. So I have printed the shape of all these elements by running this code:
[Sfepy_issue.zip](https://github.com/sfepy/sfepy/files/11723282/Sfepy_issue.zip)

```
vu in g_nl function is (1414, 6, 1, 2)
p in g_nl function is (1414, 6, 1, 1)
vg2.bfg in dw_nl_grad_grad is (1414, 6, 2, 6)
vg2.bf in dw_nl_grad_grad is (1, 6, 1, 6)
valqp in dw_nl_grad_grad is (1414, 6, 2, 1)
outqp in dw_nl_grad_grad is (1414, 6, 6, 1)
outqp*vg1.bf in dw_nl_grad_grad is (1414, 6, 6, 6)
out (1414, 1, 6, 1)
```
A few questions:
1) the shape of the variable is (1414, 6, 1, 1), where 1414 are the number of cells, 6 are the qp? and 1,1 represent a scalar?. But vg2.bf has (1, 6, 1, 6) where the first 1 is because they are the same at every cell, but I don't understand what the last 6 stands for, is it the number of base functions?

2) whatever the term I am trying to create, should it always have this shape (n Cells, n qp?, n bf, 1 for scalar)? 

3) If I understand correctly, We use p[-1] in "dw_nl_grad_grad.i.Omega( g_nl, g_nl_d, phi[-1] ,s )" because in this way diff_var is set to None?

4) As you can see I have removed all the elipsis in g_nl(p) and consequently in the class NonlinearTerm (which again is just the already exisisting [NonlinearScalarDotGradTerm](http://sfepy.org/doc-devel/src/sfepy/terms/terms_dg.html#sfepy.terms.terms_dg.NonlinearScalarDotGradTerm), I am just playing with it at the moment) and it seems to work just fine and looks simpler in my head. Were there a reason to be like that? 

5) why does the term [NonlinearScalarDotGradTerm](http://sfepy.org/doc-devel/src/sfepy/terms/terms_dg.html#sfepy.terms.terms_dg.NonlinearScalarDotGradTerm) requires the derivative of the function if it is not used anywhere? (at least I don't see it)

**Comment by rc** [comment]
> Yes, sorry, the original error was the same as this one because I was just copy-pasting the source code of dw_ns_dot_grad_s. As you said, the mistake was not making f(p) a vector. So I have changed that, and now it works.

OK
 
> I am now trying to understand the right way to sum over the indices of the base functions, material functions, and so on. So I have printed the shape of all these elements by running this code: [Sfepy_issue.zip](https://github.com/sfepy/sfepy/files/11723282/Sfepy_issue.zip)
> 
> ```
> vu in g_nl function is (1414, 6, 1, 2)
> p in g_nl function is (1414, 6, 1, 1)
> vg2.bfg in dw_nl_grad_grad is (1414, 6, 2, 6)
> vg2.bf in dw_nl_grad_grad is (1, 6, 1, 6)
> valqp in dw_nl_grad_grad is (1414, 6, 2, 1)
> outqp in dw_nl_grad_grad is (1414, 6, 6, 1)
> outqp*vg1.bf in dw_nl_grad_grad is (1414, 6, 6, 6)
> out (1414, 1, 6, 1)
> ```
> 
> A few questions:
> 
>     1. the shape of the variable is (1414, 6, 1, 1), where 1414 is the number of cells, 6 is the qp? and 1,1 represent a scalar?. But vg2.bf has (1, 6, 1, 6) where the first 1 is because they are the same at every cell, but I don't understand what the last 6 stands for, is it the number of base functions?

Yes, because your approximation order is 2. Were it 1, the last shape value would be 3 (the triangle vertices).

>     2. whatever the term I am trying to create, should it always have this shape (n Cells, n qp?, n bf, 1 for scalar)?

Yes. For a variable with n_c components, the resulting shape would be (n_cell, n_qp, n_c * n_bf, 1) in the residual mode.
 
>     3. If I understand correctly, We use p[-1] in "dw_nl_grad_grad.i.Omega( g_nl, g_nl_d, phi[-1] ,s )" because in this way diff_var is set to None?

The DG example uses an explicit time-stepping, that is why there is phi[-1]. In your case, you might need to implement the matrix mode properly. It was omitted in the dw_ns_dot_grad_s due to time constraints of my student finishing his master thesis :)

>     4. As you can see I have removed all the ellipsis in g_nl(p) and consequently in the class NonlinearTerm (which again is just the already existing [NonlinearScalarDotGradTerm](http://sfepy.org/doc-devel/src/sfepy/terms/terms_dg.html#sfepy.terms.terms_dg.NonlinearScalarDotGradTerm), I am just playing with it at the moment) and it seems to work just fine and looks simpler in my head. Was there a reason to be like that?

Not sure, maybe it was some preparation for a non-constant advection velocity.
 
>     5. why does the term [NonlinearScalarDotGradTerm](http://sfepy.org/doc-devel/src/sfepy/terms/terms_dg.html#sfepy.terms.terms_dg.NonlinearScalarDotGradTerm) requires the derivative of the function if it is not used anywhere? (at least I don't see it)

It was to be used in the matrix mode (diff_var not None), but never got finished.

**Comment by peppe988** [comment]
ok, thanks again. 

When you talk about matrix and residual mode, are you referring to the tangent matrix K and r in http://sfepy.org/doc-devel/ebcs_implementation.html#implementation? 

But if that is the case every term in sfepy which is dependent on the unknown function either linear or non-linear, should have both modes? So that I can build K and r for the Newton solver, right?

I guess the specific term [NonlinearScalarDotGradTerm](http://sfepy.org/doc-devel/src/sfepy/terms/terms_dg.html#sfepy.terms.terms_dg.NonlinearScalarDotGradTerm) needed just the residual mode because, in the framework of DG methods, you assemble the equation differently from a simpler Newton method?

Sorry if I am bombarding you with questions, but I am trying to understand everything before implementing something new. If these are simple questions that require studying a little bit more of the generic FEA theory, feel free to just refer me to some good learning resources.

**Comment by rc** [comment]
> When you talk about matrix and residual mode, are you referring to the tangent matrix K and r in http://sfepy.org/doc-devel/ebcs_implementation.html#implementation?

Essentially yes. It might be better explained [here](https://arxiv.org/abs/2107.04121) - see Section 4.
 
> But if that is the case every term in sfepy which is dependent on the unknown function either linear or non-linear, should have both modes? So that I can build K and r for the Newton solver, right?

Yes.
 
> I guess the specific term [NonlinearScalarDotGradTerm](http://sfepy.org/doc-devel/src/sfepy/terms/terms_dg.html#sfepy.terms.terms_dg.NonlinearScalarDotGradTerm) needed just the residual mode because, in the framework of DG methods, you assemble the equation differently from a simpler Newton method?

It used an explicit time-stepping (using known values from a previous step), so no matrix was assembled.

> Sorry if I am bombarding you with questions, but I am trying to understand everything before implementing something new. If these are simple questions that require studying a little bit more of the generic FEA theory, feel free to just refer me to some good learning resources.

No problem. 

The two modes (residual and matrix) basically mean that a term should implement also its derivatives w.r.t. the state variables present. Currently it is done manually, but other codes often uses the automatic differentiation and the like. (I have a very preliminary JAX-based prototype for the elasticity term on the way).

**Comment by peppe988** [comment]
Perfect, thank you. I have tried to implement my term after reading the paper and the second example here (http://sfepy.org/doc-devel/developer_guide.html#examples). I am still using dot_sequences, maybe I'll move to einsum later. 

But anyway, the solution does not converge which I think is a problem of how I implemented the tangent matrix. Since my term in the weak form is this: 
$$\int_{\Omega} f(p)\nabla q \cdot \nabla p $$
I have tried to calculate the tangent as 
$$\partial_p\int_{\Omega} f(p) \nabla q \cdot \nabla p  =\int_{\Omega} f(p) \nabla q \cdot \partial_p(\nabla p)  + \int_{\Omega}  \partial_p f(p)\nabla q \cdot \nabla p $$

Where if I interpreted correctly from the example the term $\' \partial_p(\nabla p) \'$ is equivalent to differentiate the base functions?
[Sfepy_issue.zip](https://github.com/sfepy/sfepy/files/11736605/Sfepy_issue.zip)

**Comment by rc** [comment]
What you wrote holds in the continuous case. But in FEM, you have $p(x) \approx N(x) p$, $\nabla p(x) \approx \nabla N(x) p = G(x) p$, so also $f(p) \approx f(N p)$ and(!) $\partial_p f(p) \approx \partial_p f(N p) \partial_p (N p) = (\partial_p f(N p)) N$. Be careful with transpositions etc. I wrote it in a lazy way... This is where index notation (einsum) comes handy :)

PS: `val_qp = fun...` not `val_qp = dfun` as you have in grad_state matrix mode.

**Comment by rc** [comment]
Above $N$ is `vg.bf` (same for all cells), $G$ is `vg.bfg`.

**Comment by peppe988** [comment]
> Above N is `vg.bf` (same for all cells), G is `vg.bfg`.

No worries it was clear, thank you!


> What you wrote holds in the continuous case. But in FEM, you have p(x)≈N(x)p, ∇p(x)≈∇N(x)p=G(x)p, so also f(p)≈f(Np) and(!) ∂pf(p)≈∂pf(Np)∂p(Np)=(∂pf(Np))N. Be careful with transpositions etc. I wrote it in a lazy way... This is where index notation (einsum) comes handy :)
> 
> PS: `val_qp = fun...` not `val_qp = dfun` as you have in grad_state matrix mode.

Oh sure, what a mistake I was doing. Also, f(p) is no more a vector, so swapaxes made absolutely nonsense, haha. 

Anyway, now it converges, I think it will be worth testing it. The code is at the end.

I tried solving the problem in http://sfepy.org/doc-devel/examples/diffusion-poisson_field_dependent_material.html?highlight=dependent, and it seems to work. 

If you want I can also implement the matrix mode for [NonlinearScalarDotGradTerm](http://sfepy.org/doc-devel/src/sfepy/terms/terms_dg.html#sfepy.terms.terms_dg.NonlinearScalarDotGradTerm). I think I have understood how it works but first let me know if my term is actually correct!

[Sfepy_issue.zip](https://github.com/sfepy/sfepy/files/11750323/Sfepy_issue.zip)

**Comment by rc** [comment]
Yes, it converges! You could simplify the term: there is really no need to distinguish 'grad_state', 'grad_virtual', so I suggest you keep the 'grad_state' code. You can also revert back to dot_sequences, as you ended up with "einsumming" just two arrays - not sure which is faster :)

It would be nice to have such a term in terms_diffusion.py (named for example dw_nl_diffusion - it is not really "grad_grad" - in the strong form it is "div(f(p) grad(p))").

**Comment by peppe988** [comment]
Sure. I have added also a non-linear volume term since I needed it anyway. Everything seems to work, but let me know if there are problems.


[NonlinearDiffusionsTerms.py.zip](https://github.com/sfepy/sfepy/files/11762119/NonlinearDiffusionsTerms.py.zip)

**Comment by rc** [comment]
Would you like to make a pull request? I could guide you in the conversation under it.

**Comment by peppe988** [comment]
it would be great, what's the procedure?

**Comment by peppe988** [comment]
Pulled the request! 

Actually I have another question. 

I would also like to generalize the new terms for two coupled variables. The Newton method can be extended easily by transforming the derivative  w.r.t. the variable to a matrix of derivatives, but I guess it will not be that simple. Can geo.integrate and the surrounding functions accept a generic term like the one I have in mind?

**Comment by rc** [comment]
How do the two-variables look? It is certainly possible to have several state variables in a single term (see for example dw_convect_v_grad_s). You just need to provide the derivatives w.r.t. all the state variables, the rest (Newton, ...) will work automatically.

**Comment by peppe988** [comment]
I am trying to apply these two new terms with a more generic function:
$$f(p1, p2)=\frac{1}{\sqrt{1+p1^2+p2^2}} $$
Where p1 and p2 are real and defined in the same domain, and solve two different PDEs with the aforementioned term coupling them.

I was trying to implement it in a similar way but i get this error, 
[Sfepy_issue.zip](https://github.com/sfepy/sfepy/files/11787580/Sfepy_issue.zip)
:

```
Traceback (most recent call last):
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/bin/sfepy-run", line 8, in <module>
    sys.exit(main())
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/scripts/simple.py", line 330, in main
    app()
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/applications/application.py", line 29, in call_basic
    return self.call(**kwargs)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/applications/pde_solver_app.py", line 232, in call
    post_process_hook_final=self.post_process_hook_final)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/problem.py", line 1469, in solve
    status=status)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/solvers/ts_solvers.py", line 36, in _standard_ts_call
    status=status, **kwargs)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/solvers/ts_solvers.py", line 75, in __call__
    vec = nls(vec0)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/solvers/nls.py", line 260, in __call__
    vec_r = fun(vec_x)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/evaluate.py", line 78, in eval_residual
    vec_r = self.problem.equations.eval_residuals(vec)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/equations.py", line 675, in eval_residuals
    self.evaluate(mode='weak', dw_mode='vector', asm_obj=out)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/equations.py", line 608, in evaluate
    term_mode=term_mode, asm_obj=asm_obj)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/equations.py", line 833, in evaluate
    ret_status=True)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/terms/terms.py", line 1487, in evaluate
    fargs = self.call_get_fargs(_args, kwargs)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/terms/terms.py", line 1312, in call_get_fargs
    fargs = self.get_fargs(*args, **kwargs)
  File "/Users/giuseppecolletta/Desktop/Sfepy_issue/sfepy-example.py", line 128, in get_fargs
    vg2, _ = self.get_mapping(var2)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/terms/terms.py", line 1080, in get_mapping
    integration = self.geometry_types[variable.name]
KeyError: 'phi1'
```

**Comment by rc** [comment]
Did you attach the correct code?

**Comment by peppe988** [comment]
Oh I am sorry, I gave you an old version. Here is the right one:
[Sfepy_issue_19_06.zip](https://github.com/sfepy/sfepy/files/11790214/Sfepy_issue_19_06.zip)

**Comment by rc** [comment]
You need to use `'state_1'` instead of `'state1'` etc. so that the arguments are recognized as state variables. Then in comparisons replace `diff_var == state1.name:` with `diff_var == var2.name:` etc. Then it at least runs (but does not converge) so you will be able to debug it.

**Comment by peppe988** [comment]
Perfect, sorry I did not know there was a convection to respect! I think I have solved the problem, I did a mistake while calculating the derivative and now it converges. Let me run a few tests and I think I can commit a new term :)

**Comment by rc** [comment]
Glad it helped. As for the new term, these two-variable ones seem a bit too specialized. Maybe after your publication is done, you might add them with the accompanying example?

**Comment by peppe988** [comment]
Sure! Thank you for all the fruitful discussions.

**Comment by peppe988** [comment]
Sure! Thank you for all the fruitful discussions.
